### ISSUE TITLE
JS error in calendar editor

### ISSUE THREAD

**Issue by PunchcardCoder** [bookingactivities/booking-activities#1]
All of a sudden, bookingactivities crashes on chrome60 on some PCs. Here's the relevant bit of the console log for the calendar editor:
global-functions.js?ver=1.0:25 Uncaught TypeError: Cannot read property 'left' of undefined
    at bookacti_is_mouse_over_elem (global-functions.js?ver=1.0:25)
    at bookacti_open_or_close_trash (templates-functions.js?ver=1.0:270)
    at HTMLDocument.<anonymous> (templates.js?ver=1.0:14)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.1:3)
    at HTMLDocument.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.1:3)
bookacti_is_mouse_over_elem @ global-functions.js?ver=1.0:25
bookacti_open_or_close_trash @ templates-functions.js?ver=1.0:270
(anonymous) @ templates.js?ver=1.0:14
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.1:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.8.1:3

And there is no calendar on the product page. Again the console log:
(index):293 Uncaught ReferenceError: bookacti is not defined
    at (index):293
(anonymous) @ (index):293
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".layout-golden--one__right" failed, no elements found.
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".blog__post--l5" failed, no elements found.
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".front-product-category__card" failed, no elements found.
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".image__pic--left" failed, no elements found.
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".widget__footer__widget" failed, no elements found.
library.min.js?ver=20160625:10 ScrollReveal: reveal on ".front-feature-blocks .feature-block__inner" failed, no elements found.
booking-system.js?ver=1.0:25 Uncaught ReferenceError: bookacti is not defined
    at HTMLDivElement.<anonymous> (booking-system.js?ver=1.0:25)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDocument.<anonymous> (booking-system.js?ver=1.0:20)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
(anonymous) @ booking-system.js?ver=1.0:25
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
(anonymous) @ booking-system.js?ver=1.0:20
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

**Comment by yoancutillas** [comment]
Hi @PunchcardCoder,

This is quite strange:
- The first error come from a function that does not exist anymore since 1.1.0
- The second error come from a variable that only exists since 1.1.0

It seems that you have files from mixed versions.
Can you please delete the booking-activities folder and replace it with the proper lattest version from wordpress.org:
https://downloads.wordpress.org/plugin/booking-activities.latest-stable.zip

**Warning:** Do not use 'uninstall' command from your admin panel, because it will also delete your data.

Thanks

**Comment by yoancutillas** [comment]
Hi @PunchcardCoder, 
Have you resolved this issue?

**Comment by PunchcardCoder** [comment]
Here's what worked for me: got a fresh version from wordpress.org:
https://downloads.wordpress.org/plugin/booking-activities.latest-stable.zip and copied that into the existing bookingactivities folder. I did not uninstall the malfunctioning version for fear of inadvertently deleting event and ticket data. The fresh copy did the trick. Everything works without loss of data.

**Comment by yoancutillas** [comment]
Ok, great! Thank you
