### ISSUE TITLE
Mode de réservation "cascade" avec shortcode

### ISSUE THREAD

**Issue by dkolski** [bookingactivities/booking-activities#10]
Bonjour,

Est-il possible d'afficher le mode de réservation "cascade" à l'aide du shordcode ?

merci d'avance,

Daniel

**Comment by bookingactivities** [comment]
Bonjour,

Oui, ajoutez le paramètre `method="waterfall"` au shortcode.
Ex: `[bookingactivities_form calendars="1" method="waterfall"]`

_Cette réponse ne s'adresse qu'aux possesseurs du [module Display Pack](https://booking-activities.fr/fr/downloads/pack-affichage/)._

Cordialement,
Yoan Cutillas

**Comment by dkolski** [comment]
Bonjour Yoan,

Merci pour le shortcode. Je n'avais pas trouvé l'info dans la documentation.

Comme discuté précédemment, j'utilise plusieurs activités que je mappe dans différents produits sous woocommerce. J'ai pu récupérer le nom de l'item produit que j'affiche dans une collone de la page réservation. 
Ceci est possible car il ya un lien entre la réservation et la commande woocomerce.

Y a-t'il un moyen de faire "à peu près" la même chose en utilisant des shortcodes  sur des pages distinctes équivalentes à des produits .
Dans ce cas cela pourrait être une classe ou un ID dans le shortcode qui serait sauvegardé avec la réservation.

Merci d'avance,

Daniel

**Comment by bookingactivities** [comment]
Bonjour,

Vous pouvez ajouter un champs invisible au formulaire généré par le shortcode avec le filtre PHP `bookacti_booking_form_fields` ([controller/controller-shortcode.php](https://github.com/bookingactivities/booking-activities/blob/master/controller/controller-shortcodes.php)).

En revanche vous devrez récupérer, sauvegarder et afficher vous même cette information.

Notez que ce filtre sera bientôt obsolète avec la version 1.5 qui intégrera un nouvel éditeur de formulaire. Cette version préparera également l'arrivée d'un module complémentaire permettant justement d'intégrer des champs personnalisés qui s'afficheront dans leur propre colonne de la liste des réservations.

Je vais également sans doute ajouter la colonne "Nom du produit" à la liste des réservations dans la 1.5, pour les utilisateurs de WooCommerce.

Cordialement,
Yoan

**Comment by bookingactivities** [comment]
Bonjour,

La version 1.5 est désormais sortie :
- La colonne "Produit" a été ajoutée à la liste des réservations
- Vous pouvez créer des formulaires de réservation différents comportant les même(s) planning(s) et activité(s)

Le module [Advanced Forms](https://booking-activities.fr/fr/downloads/formulaires-avances/) est également disponible : 
- Vous pouvez facilement lier n'importe quelle information à votre réservation

Cela devrait donc répondre à l'ensemble de vos besoins.
Je vais fermer ce ticket, mais si vous avez d'autres demandes n'hésitez pas à en ouvrir un nouveau.

Cordialement,
Yoan Cutillas
