### ISSUE TITLE
Potential Threat

### ISSUE THREAD

**Issue by GMDOnline** [bookingactivities/booking-activities#100]
Hi, 
I have had various reports from users of my website that their My anti-virus says its blocking some connections on the site. It says there's a JS:Dropper-AACC  trojan hidden in a bunch of things under wp-content/plugins/booking-activities/js

**Comment by yoancutillas** [comment]
Hello, if you think that a plugin has been corrupted, you should simply replace the plugin with a clean copy of it. 
- download a clean copy of Booking Activities here: https://wordpress.org/plugins/booking-activities/ 
- unzip it
- delete the booking-activities folder in wp-content\plugins\ via FTP 
- upload the clean copy of booking-activities that you have just downloaded instead

However, this may happen again and again until you find what is injecting malicious code in your files.
