### ISSUE TITLE
Bug: ical Calendar seems not to work | Multisite-specific (??)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#101]
I love(d) the ical export feature.

**What happened:**
However, about 5-6 months ago, it stopped working for me.

**What I tried:**
I tried creating new ical links and using those, but the new links also fail to work.

I am using Thunderbird, but we have found that the ical links no longer work for Google Calendar as well.

Also, if I try to go to the link for the ical calendar (in the browser), it says "Invalid key."

**Noteworthy:**
I am somewhat suspicious that it has something to do with my site being multisite, but unsure.

I do not see anything I think would be meaningful in the logs, but I am happy to email those sorts of things, if they are needed.

Thanks!

**Comment by yoancutillas** [comment]
I can reproduce the issue on a multisite install.

Can you try to replace in wp-content\plugins\booking-activities\model\ [model-global.php line 71](https://github.com/bookingactivities/booking-activities/blob/1.11.4/model/model-global.php#L71)
`$query = 'SELECT user_id FROM ' . $wpdb->prefix . 'usermeta WHERE meta_key = "bookacti_secret_key" AND meta_value = %s;';`
with 
`$query = 'SELECT user_id FROM ' . $wpdb->usermeta . ' WHERE meta_key = "bookacti_secret_key" AND meta_value = %s;';`

Then can you go to Booking Activities > Bookings > Export Bookings > Ical tab > click "Reset" button > Click "Export" button and see if it works?

**Comment by pikurasa** [comment]
> I can reproduce the issue on a multisite install.

Great. That makes my life easier trying to explain the issue.

I will test your patch later. Thanks!

**Comment by pikurasa** [comment]
I tried your code and it did fix the issue.

Thank you!

**Comment by yoancutillas** [comment]
Great, thanks for the feedback! This fix will be included in the next version.
