### ISSUE TITLE
Booking Activities doesn't work

### ISSUE THREAD

**Issue by billies289** [bookingactivities/booking-activities#104]
On the form page, after I selected the event.
Hit book button.
Your plugin doesn't recognize event has been selected.

How do I fix that please

See attached screenshot.
![Screenshot_2021-07-09-19-11-56-11_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/87190369/125084625-522d1a00-e0fc-11eb-8df5-fdd74db3972c.jpg)

**Comment by yoancutillas** [comment]
Hello, this problem may be due to a conflict with another plugin / theme.
Can follow the instructions below “Booking Activities doesn’t work as it should” here: https://booking-activities.fr/en/documentation/faq/ ?

**Comment by billies289** [comment]
I've tried your plugin in 3 different themes an all of them have the same
problem.

It's not realistic to just use your plugin alone ..

Regards,

**Comment by yoancutillas** [comment]
Make sure that Booking Activities is the only plugin active when you test the themes, to make sure that the conflict come from the theme only.

If Booking Activities is the only plugin active and it is working with the Twenty Seventeen theme, then the conflict come from the theme.

However, it sounds strange that the error occured three times in a row,
Can you give me the links to download the three themes you have tested? (if they are available for free)
