### ISSUE TITLE
Feature Request: Done Prenotations

### ISSUE THREAD

**Issue by 2ale2** [bookingactivities/booking-activities#105]
Hi. I just want to ask if there is a way to show a user all the prenotations he has already done when he logs in under the calendar or anywhere. Thank you.

**Comment by 2ale2** [comment]
I just notice how to do that, thank you. I love you all.

**Comment by yoancutillas** [comment]
Ah ah :) thank you for your feedback
For posterity, you can display your customers' bookings list with the `[bookingactivities_list]` shortcode ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/display-customers-bookings-list-on-the-frontend/)).
