### ISSUE TITLE
"Moved" Bookings cannot be found in calendar

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#107]
I have experienced this issue multiple times now.

The steps to reproduce seem to be:
1. Create an activity in admin calendar
2. book activity
3. move activity in admin calendar, either by dragging it or selecting "move"
4. result: activity will be visible when viewing "bookings" (e.g. from admin panel) but not visible from the admin calendar

This results in the inability to move the activity again if needed.

If there is any more info you think you need from me, any tests, please let me know.

Thank you!

**Comment by yoancutillas** [comment]
Hello, I didn't reproduce the issue on my dev site, can you tell me:

1. What version of Booking Activities (and its add-ons) are you using? (If not 1.12.0, can you update it (and its add-ons) and try again?)
2. When you move a booked event in the calendar editor, a dialog appears to let you know that its bookings will be rescheduled, and to offer to send your customers a notification. Is it the case on your end?
3. Can you reproduce the issue with all your plugins deactivated except Booking Activities (and its add-ons), and the theme Twenty Seventeen activated?

**Comment by pikurasa** [comment]
>     What version of Booking Activities (and its add-ons) are you using? (If not 1.12.0, can you update it (and its add-ons) and try again?)

I am on Version 1.12.0 and add-ons are up-to-date. I was experiencing it with previous versions as well as with this update.

>     When you move a booked event in the calendar editor, a dialog appears to let you know that its bookings will be rescheduled, and to offer to send your customers a notification. Is it the case on your end?

Yes, I receive the dialogue.

>     Can you reproduce the issue with all your plugins deactivated except Booking Activities (and its add-ons), and the theme Twenty Seventeen activated?

I will try this later, but I have not experienced many of the conflict-related issues I was experiencing before. Also, I have been just using storefront theme nowadays.

Did you check the issue on your multipress dev? I wonder if it is specific to that.

I also wonder if there is something in the database that is being flagged incorrectly. Is there some data that flags an activity as "hidden" or something like that.

At any rate, I will try to simplify and reproduce on a test sub-site I have when I have the chance.

**Comment by yoancutillas** [comment]
I just tried on a multisite install and could not reproduce the issue either,
I will need an access to a dev site where I can reproduce the issue on a minimal config (no other plugins, Twenty Seventeen theme).

I think that the problem you experience is that the bookings are not rescheduled.
The calendar in Booking Activities > Bookings doesn't display the current events (the one you have in the calendar editor). It displays your bookings as events. So if you move an event, but still have bookings for the old event, then the old event will still appear on the bookings calendar so you can see that there still are bookings for that old event (even if it doesn't exists anymore).
