### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by cutecase** [bookingactivities/booking-activities#11]
Bonjour,
J'ai des PHP Warning avec B.Activities.
[Apr 16, 15:28:37] PHP Warning: Invalid argument supplied for foreach() in /wp-content/plugins/booking-activities/controller/controller-woocommerce-backend.php on line 82

Est-ce un problème avec BA ou bien est-ce en raison d'un mauvais paramétrage de ma part ?

**Comment by bookingactivities** [comment]
Bonjour,

Merci pour ce rapport de bug, je viens de corriger l'erreur. Elle se produit lorsque vous modifiez la quantité d'un produit qui n'est pas une réservation sur le panneau d'admin. Il ne devrait pas y avoir de répercussions sur le bon fonctionnement de Booking Activities et de WooCommerce.

La correction sera disponible dans la prochaine mise à jour.

Cordialement,
Yoan Cutillas
