### ISSUE TITLE
Single "Summary" Notification for Bulk Bookings, Single Customer

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#111]
A few times I have booked for a customer ~12+ events with "send booking notification" box checked.

This results in 12 separate emails to both the customer and the admin.

I am concerned that such emails:
* Are annoying
* Flag my email address as potential spam
* clutter everyone's inbox and makes event bookkeeping/audits/billing more difficult

I know I can always make the 12+ events into a group before booking, but it is tempting to skip that extra step.

It would be nice if, instead of separate notification emails, it sent only a single email "booking summary" to the customer and admin.

**Comment by yoancutillas** [comment]
Thank you for your request, 
I too thought this could be improved when developing the multiple booking feature, but I couldn't find a smart solution at that time. Since then it is on the road map, I add your vote, thank you!

**Comment by yoancutillas** [comment]
Released in 1.16
