### ISSUE TITLE
Possible Issue with WC and BA

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#115]
I just updated WC database and saw the following error in the logs (* wp-admin/admin.php?page=wc-status&tab=logs):

![Screenshot at 2021-10-13 09:56:42 BA causing WooCommerce Update Issue](https://user-images.githubusercontent.com/13454579/137147966-e71d526a-cc5f-48d4-b99b-8fa4b54def64.png)

Unsure what this means myself, but hoping the feedback is helpful.

**Comment by yoancutillas** [comment]
The Licenses and Updates add-on may have not been properly updated,
Can you remove the wp-content/plugins/ba-licenses-and-updates folder (via FTP) and upload a fresh copy of it instead ([direct download link](https://booking-activities.fr/wp-content/uploads/downloads/public/ba-licenses-and-updates.zip)) (you need to extract the zip first).

Make sure the other add-ons are up to date, and clear any caching sytem you are using too.

Then, can you 
1. In the wp-config.php file, replace:
define('WP_DEBUG', false);
with:
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
2. Reload any page of your website
3. Check if the error still appears in the wp-content/debug.log file (if it appeared)
