### ISSUE TITLE
WC Calendar: Picked Event Unit name missing space 

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#116]
Hi,
Thanks for keeping up the enhancements for BA.  I have noticed a glitch in the front end, when a customer picks/selects an event, the picked event notice shows the unit name without a space.  Below is snapshot from your demo site and also from our website for your reference. Thanks and appreciate your support...
![ba-booking-selected](https://user-images.githubusercontent.com/30695308/140585213-1fb50a2f-afda-405e-81e5-ad341dc62b43.jpg)

![ba-booking-selected2](https://user-images.githubusercontent.com/30695308/140585235-23a189a8-c5d7-42b8-8146-99e74e95cf08.jpg)

![ba-booking-selected3](https://user-images.githubusercontent.com/30695308/140585255-e4cfc519-98e2-4cfc-85b7-96ec35df4fe7.jpg)

**Comment by yoancutillas** [comment]
Thank you!
The fix will be published in the next release.
