### ISSUE TITLE
Adding custom email address each activity - Admin notifications recipients

### ISSUE THREAD

**Issue by Messa1** [bookingactivities/booking-activities#118]
Would be nice if I can add for each activity a custom mail and not need to create first a user.
So that the field also allow comma separated email address

![Admin notifications recipients](https://user-images.githubusercontent.com/3908658/142198437-5e8d7c72-0855-4e76-8581-5cf3ac6527bb.png)

**Comment by yoancutillas** [comment]
Thank you for your request,
but it wouldn't work for Push and SMS notifications.

Can you elaborate why do not wish to create a user?

**Comment by Messa1** [comment]
Ah - Oky I got that. Now I know why you choose user there.
For me (my customer) it's more work to add users for all events that just send them information about there courses.
Cause they don't want that trainer can edit events or other things in the system.

I just use now - a woocommerce hook to trigger for each item a mail (woocommerce_order_status_....)
That works for now - but as i wrote for us it's much work to add users.

**Comment by yoancutillas** [comment]
Thanks for the additional info, I wish I could help you find a solution to the root of the problem. Glad you made the custom code work!
