### ISSUE TITLE
Security issue with [bookingactivities_login form]

### ISSUE THREAD

**Issue by IlPadrinoo** [bookingactivities/booking-activities#119]
When a form [bookingactivities_login form="xxx" redirect_url=""] is in the trash and displayed on fonrtend, user can login with WITHOUT password. Just enter email address and you are login. This trouble exists with ADMIN ACCOUNT too.
Users : be careful
Devs : please do something

**Comment by yoancutillas** [comment]
Hello, this is an non-default option in Booking Activities > Booking forms > your form > "User data (Login / Registration)" field settings > Login tab > "Password required" option.

![required-password-option](https://user-images.githubusercontent.com/9415030/142391814-e9622cd8-9b47-4763-ad6d-f15e392d51f7.PNG)

If you find a security issue, please always contact the author privately to report it (contact@booking-activities.fr).
