### ISSUE TITLE
Poids des javascripts

### ISSUE THREAD

**Issue by cutecase** [bookingactivities/booking-activities#12]
Bonjour,

Je n'utilise BA que sur 3 pages de mon site.

Il s'avère que les javascripts utilisés par BA sont vraiment très nombreux et que leur poids total cumulé est conséquent, ce qui pénalisent tout le site en terme de performances, de nombre de requêtes, de ranking, etc.

Y a-t-il un moyen d'éviter que tous les javascripts de BA soient systématiquement chargés sur l'ensemble du site ?

**Comment by bookingactivities** [comment]
Bonjour,

Oui, vous pouvez ajouter ce code à votre fichier functions.php de votre thème (enfant):

```
/**
 * Enqueue Booking Activities scripts on desired pages only
 * @param array $pages_to_load
 * @param array $pages_not_to_load
 * @return boolean
 */
function bookacti_enqueue_booking_activities_scripts_on_desired_pages_only( $pages_to_load, $pages_not_to_load ) {
	$enqueue_scripts = true;
	if( empty( $pages_to_load ) ) {
		if( ! empty( $pages_not_to_load ) 
			&&	(  ( is_page( $pages_not_to_load ) || is_single( $pages_not_to_load ) )
				|| ( in_array( 'home', $pages_not_to_load ) && ( is_home() || is_front_page() ) ) ) ) {
			$enqueue_scripts = false;
		}
	} else if( ! is_page( $pages_to_load ) && ! is_single( $pages_to_load )
			&& ! ( in_array( 'home', $pages_to_load ) && ( is_home() || is_front_page() ) ) ) {
		$enqueue_scripts = false;
	}

	if( $enqueue_scripts ) { return false; }

	// Do not enqueue BA scripts
	remove_action( 'wp_enqueue_scripts', 'bookacti_enqueue_high_priority_global_scripts' );
	remove_action( 'wp_enqueue_scripts', 'bookacti_enqueue_global_scripts' );
	remove_action( 'wp_enqueue_scripts', 'bookacti_enqueue_frontend_scripts' );
	
	return true;
}

/**
 * Defines the pages where Booking Activities scripts will be loaded
 */
function bookacti_enqueue_booking_activities_scripts_conditionally() {
	// FILL ONE OF THIS ARRAY
	$pages_to_load		= array(); // Load Booking Activities scripts only on these pages ('home' for homepage)
	$pages_not_to_load	= array(); // Load Booking Activities scripts everywhere but on these pages ('home' for homepage)

	if( ! $pages_to_load && ! $pages_not_to_load ) { return false; }

	bookacti_enqueue_booking_activities_scripts_on_desired_pages_only( $pages_to_load, $pages_not_to_load );
}
add_action( 'wp_enqueue_scripts', 'bookacti_enqueue_booking_activities_scripts_conditionally', 5 );
```

Remplissez le tableau `$pages_to_load` avec la liste des slugs de vos pages, séparés par des virgules. Voici où trouver les slugs : 
![page-slug](https://user-images.githubusercontent.com/25784216/38965815-d8e005fa-43b9-11e8-9e0e-7a877f49c926.PNG)

Mettez `'home'` pour la page d'accueil.
Ex : `$pages_to_load = array( 'home', 'my-page-1', 'my-product' );`

Cordialement,
Yoan Cutillas

**Comment by cutecase** [comment]
Bonjour Yoan,

Superbe ! Merci de votre réponse.

Je pense que, pour une prochaine version, ce serait bien d'intégrer cette fonctionnalité dans les réglages de BA.

Belle journée,
Philippe


--





by SurpresiTernura, Unip. LDA


Philippe Feryn
Tél. : 00 351 243 055 398

www.cutecase.fr
www.facebook.com/cutecase.fr

cutecase@cutecase.fr

**Comment by bookingactivities** [comment]
Oui bonne idée, mais en l'état ce n'est pas très pratique pour les sites comportant beaucoup de pages ou evoluant très vite.
L'idéal serait que Booking Activities soit capable de détecter les pages sur lesquels on a besoin de lui, il faut que j'y réfléchisse :)

Cordialement,
Yoan Cutillas
