### ISSUE TITLE
Add Additional Email for Notifications

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#120]
(If there is already a way to do this, then please let me know. The solution is not obvious to me.)

I have a customer who wants the notification reminders sent to his email as well as to another email (and maybe even a third email).

In fact, the more I think about it, the more I realize I probably will be asked about this more and more as time goes on.

This may be related to https://github.com/bookingactivities/booking-activities/issues/118 but unsure...

I don't mind adding the other addresses as separate "users", but I would like to link the additional email addresses to the original user so that I don't have to specify it every booking, if possible.

**Comment by yoancutillas** [comment]
There is no way to add recipients for emails sent to a customer (except custom code).
#118 is related to emails sent to administrators, and indeed, you can easily add an admin recipient, overall, per activity and per notification.

A workaround would be that your customer set up a automatic action on his / her emailing client to transfer the emails coming from your site to the additional addresses.

**Comment by pikurasa** [comment]
> A workaround would be that your customer set up a automatic action on his / her emailing client to transfer the emails coming from your site to the additional addresses.

I agree that this would solve the issue.

However, it puts the burden on the customer, and solutions on the website are usually preferable where they can be done.

**Comment by yoancutillas** [comment]
Hello, this can be achieve now with the [Advanced Forms](https://booking-activities.fr/en/downloads/advanced-forms/) add-on ([docs](https://booking-activities.fr/en/blog/advanced-forms-1-4-send-the-notifications-to-all-participants/)).
