### ISSUE TITLE
Admin Notes for Manual Credit Edits

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#122]
I expect this to be a simple, yet powerful, addition:

For this feature ( https://github.com/bookingactivities/booking-activities/issues/94 ), please add a field for an admin to write a line of text of "notes". This will help bookkeeping as admins will need to look back and see why they made manual edits, and it would be great if they could see their notes all in the same place.

I am unsure if admins need a feature to edit their notes after initial publication of their credit updates, but they certainly need to be able to add notes the first time.

**Comment by yoancutillas** [comment]
I have noted your feature request, thank you.

The booking pass logs are all displayed on the same page (the booking pass edit page), so I am not sure to understand this part:

> it would be great if they could see their notes all in the same place

can you elaborate?

**Comment by pikurasa** [comment]
> can you elaborate?

No elaboration needed. I think you get it. "On the same page" is fine.

Thanks!

**Comment by pikurasa** [comment]
This feature is nice, but I do think you need to have inputs for:
* add x number of credits
* subtract x number of credits

It looks a little weird that the total magically changes, and I am a little concerned that a user may do something at nearly the same time as an admin, which would cause some unnecessary editing. Using an add/subtract system would avoid that in many cases.

**Comment by yoancutillas** [comment]
I understand, thank you, I have noted you feature request and opened a new ticket.

The admin notes feature from this ticket has been released in Prices and Credits 1.7.2
`* Tweak - Add a custom message to the log entry when updating booking pass settings`
