### ISSUE TITLE
Booking form Filter only worked  first time after creation 

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#125]
It seems that I can successfully filter an activity only ONCE after the booking form has been created (using the link from the calendar editor) 
After this I tried to pick, unpick, select all, and the reset option (which shows all the activities again) 
I unload all other plugins, change theme tot 2020 and used 4 different browsers. Without any results. 

To reproduce:
create calendar
create activities 
create booking form through the link provided (at the calendar editor)
calendar options (in booking form) -> filter
1st time it does filter the selected activity
2nd time it does not.

I hope its just something i do not understand because i would love to use your plugin on our website
[https:hetamsterdams](https://www.hetamsterdamskleibedrijf.nl/

Kind regards,
Ray

**Comment by yoancutillas** [comment]
Duplicate: https://wordpress.org/support/topic/booking-form-filter-only-worked-first-time-after-creation/
