### ISSUE TITLE
Customers to Opt-out of Email Notifications

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#127]
Some customers would like to opt-out of email notifications.

It would be nice if they could have an option to do that from their dashboard, and maybe with a checkmark that they acknowledge that they will "keep track of my own schedule" (or something like that).

**Comment by yoancutillas** [comment]
Thank you for your request, I add your vote.
I assume this is for the [Notification Pack](https://booking-activities.fr/en/downloads/notification-pack/)'s scheduled notifications only (reminders...) ([described here](https://booking-activities.fr/en/docs/user-documentation/get-started-with-notification-pack-add-on/send-automatic-notifications-before-or-after-the-bookings/))

**Comment by SophieWeb** [comment]
If this is the way “pending for votes” works, can you add mine?

**Comment by yoancutillas** [comment]
Hello Sophie, it is, I add your vote, thank you!

**Comment by SophieWeb** [comment]
Thanks so much for adding this feature to the Notification Pack!
Users can now choose in the account details if they want to receive SMS or emails.
Maybe the SMS settings should be hidden if SMS is not enabled, but that’s very minor.

**Comment by yoancutillas** [comment]
You are welcome!
I'll try to do that in a future update, thanks.

Have a happy new year!
