### ISSUE TITLE
Single notification for upcoming group of events

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#128]
There are many instances (for what I do) where it would be preferable to receive only a single notification for an upcoming "group of events" (e.g. if the event will happen daily, over the course of a week).

In the meantime, I do see a clunky workaround where I can set things that are _generally booked as a group_ off from notifications from admin.php?page=bookacti_settings&tab=notifications&notification_id=customer_scheduled_default

From that same dashboard, however, it would be nice to also select group of events on/off and select which groups of events receive notifications.

**Comment by yoancutillas** [comment]
Assuming your request is about [Notification Pack](https://booking-activities.fr/en/downloads/notification-pack/)'s scheduled notifications ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-notification-pack-add-on/send-automatic-notifications-before-or-after-the-bookings/)):

There is a "Send only once per group" option in the notification settings that let you choose wether to send the notification only once for the group (based on the first event of the group) or once per event in the group.

If you want to turn it ON for certain groups, and OFF for others, move the groups of events in different group categories in the calendar editor, and then create two notifications. Configure the first notification to be sent only for the first group category with the "Send only once per group" option ON, and the second notification to be sent only for the second group category with the "Send only once per group" option OFF.
