### ISSUE TITLE
Booking without registration new users

### ISSUE THREAD

**Issue by marekmaro** [bookingactivities/booking-activities#13]
Hello, 
Booking without registration only required fields the name, secondname, number, etc.

**Comment by bookingactivities** [comment]
Hello,

Users need to be registered to make a booking.
Since version 1.5 it is seamless, they just have to give their email address in the booking form and the registration is made at the same time as the booking. (You have an option to generate passwords).

Regards,
Yoan Cutillas

**Comment by mjas82** [comment]
Hi, I have the same issue - booking form has been set up and currently requires customers to create a password. How do I disable this option so that customers can checkout without needing to set up an account and create their own password? Thanks

**Comment by bookingactivities** [comment]
Hello @mjas82,

In your form editor, click on the setting wheel in the "Login / Registration" field.
A dialog appears, go to "Options" tab, and check the "Generate password" option.
Validate the dialog.

Now, when your customers will check the "create an account" box, they won't need to enter a password. It will be automatically generated for them. They will receive an e-mail to allow them to reset the password.

Booking Activities currently needs your customers to have an account to handle bookings.
But you can use these settings, to have a seamless registration process: 
![seamless-login-settings](https://user-images.githubusercontent.com/25784216/43741370-6809bd74-99ce-11e8-80d4-f71135e6ec8a.PNG)
You can also change the "Create an account" text to something like "This is my first booking".

Booking Activities will also support booking without account at all in the near future.

Regards,
Yoan Cutillas

**Comment by mjas82** [comment]
Thanks for the really quick reply - I can see how to do this now in some of my activity booking forms but not all. They were set up by somebody else and don't have any login / register options. Still can't get rid of the account password box though. Any idea when the guest checkout option might be available?

Thanks again

**Comment by bookingactivities** [comment]
If there is no login / register field, I guess that this form is bound to a WooCommerce product.
If this is the case, then, yes, you need to wait until Booking Activities supports WC "Guest checkout" option. It will be released before the end of the year.

Regards,
Yoan Cutillas

**Comment by bookingactivities** [comment]
Hello,

Now, with Booking Activities 1.6, you can book without user account at all.
And the WooCommerce "Guest checkout" option is supported.

Regards, 
Yoan Cutillas
