### ISSUE TITLE
Cancellation and coupon

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#132]
Perhaps a silly question,

Since the core plugin without the addons give the option in the cancelation tab for a customer action like a coupon ,does that mean an automated coupon option is available by cancelation, or do i need to use the addon?  Although its selected in the cancelation tab it does not show up as an option when a customer cancels (only email option)

**Comment by yoancutillas** [comment]
There are no silly question here :) You don't need add-ons:
- purchase a booking via WooCommerce checkout ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/display-calendars-on-product-page/), [demo](https://demo.booking-activities.fr/en/shop/calendar/)),
- Make sure the order is "Complete" and paid (it must be written "Paid on 14 february..." on the order edit page on the backend)
- go to your booking list on the frontend
- cancel the booking, then click the "Request a refund" button, you should be able to select the "Coupon" option in the refund dialog

**Comment by rayedgar** [comment]
I have manually set in the booking to to PAID and subscribed. It does not give me the option as the subscriber to receive a coupon only the email option is there. I am already using WC coupons. perhaps this happens because it wasnt really gone through the payment system?

<img width="677" alt="Screenshot 2022-02-15 at 08 31 24" src="https://user-images.githubusercontent.com/6242489/154013697-f3c0f827-1b71-4bef-b1d8-4cbd5918715c.png">
<img width="1045" alt="Screenshot 2022-02-15 at 08 29 23" src="https://user-images.githubusercontent.com/6242489/154013701-2e79c935-341c-4738-997d-44efe1b6181c.png">
<img width="1037" alt="Screenshot 2022-02-15 at 08 29 10" src="https://user-images.githubusercontent.com/6242489/154013707-09bede1a-1f62-4970-9fb5-569ba0e5e915.png">

**Comment by yoancutillas** [comment]
Can you make sure the **order** is paid (the **booking** "paid" status doesn't affect it):

![order-paid](https://user-images.githubusercontent.com/9415030/154030982-ea40d909-3311-4ea0-a01c-88dfcaed76a2.PNG)

**Comment by rayedgar** [comment]
Works perfect when order is paid through WC  (manual setting status to paid within booking system did not work as you already mentioned) Great!
