### ISSUE TITLE
Saving issues when setting up

### ISSUE THREAD

**Issue by PranaRunBienEtre** [bookingactivities/booking-activities#135]
Hi all,

Having an issue with this plugin.
I have the main one + advanced forms + prices & credits.

As soon as I save a setup, it resets itself.
Has anyone experienced this ?

I've switched to the recommended wordpress theme "Twenty Seventeen" and deactivated all plugins to see if the issue could come from those but it has not changed a thing.

Thanks in advance for your help.

**Comment by PranaRunBienEtre** [comment]
Example in Passes : I apply the pass to a certain activity by selecting it and then saving. The page reloads and all is reset by itself.

**Comment by yoancutillas** [comment]
Hello, 

Please deactivate all your plugins and activate the Twenty Seventeen theme during these tests.

1.
Can you let me know your versions of: Booking Activities, Prices and Credits, Advanced Forms, and Wordpress?

2.
Can you also make sure that you are not using Object Caching tool (maybe at the server level) (Redis, Memcached...) or deativate it?

3.
- Replace in wp-config.php
```
define('WP_DEBUG', false);
```
with:
```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```
- Reproduce the problem
- Send me the wp-content/debug.log file (if it has appeared)

**Comment by PranaRunBienEtre** [comment]
Hi,

Thanks for your support. It seems the issue came from cache.
FYI, the theme and all plugins had been deactivated before writing. ;)

**Comment by yoancutillas** [comment]
Thank you, it's a really good habit to set up a reduced test case before reporting!

For information, an object cache tool caches the database queries results. So if a plugin like Booking Activities retrieves data from the database, it returns the same result before and after the data has been updated. Object cache cannot be natively compatible with all plugins, and unfortunately Booking Activities is not compatible with object cache for now.
