### ISSUE TITLE
Réglages du calendrier ne sont pas pris en compte

### ISSUE THREAD

**Issue by AudreyCha** [bookingactivities/booking-activities#138]
Bonjour,

J'ai créé des formulaires de réservation dans Booking activities mais lorsque je change les paramètres du calendrier (par exemple pour n'afficher qu'une seule activité ou modifier l'heure de début d'affichage), ils ne sont pas pris en compte. J'ai réessayé cinquante fois, en mettant à jour évidemment, mais le formulaire revient comme avant mes modifs... Comment faire ?
Merci

**Comment by yoancutillas** [comment]
Bonjour Audrey,
Il est possible que vous utilisiez un outil d'Object Cache (tel que Redis, Memcached, etc.), soit en tant que plugin, soit au niveau de votre hébergement. Booking Activities n'étant pas compatible, pouvez-vous le désactiver et essayer à nouveau ?
