### ISSUE TITLE
Only X available

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#140]
Is there a way to, just like in woocommerce set a filter to only show a few in stock (with a threshold)  or no show option?

ideally:
1) show nr in stock
2) only show when threshold is below x
3) no show (ofcourse that can be done with css)

**Comment by yoancutillas** [comment]
Yes, you can find the option in Booking Activities > Booking forms > your form > Calendar settings > Display tab > "Hide availability if greater than"

**Comment by rayedgar** [comment]
Thats great!, however i see that indeed the quantity is shown depending on the setting but the Particle displayed after the number of available places  is not hiding when needed.

**Comment by rayedgar** [comment]
Yes, this helps. Many thanks.
