### ISSUE TITLE
Can't change button text 'Book'

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#141]
Sorry to ask another question again! ;) 

I cannot see to change the text of the booking button (front end)
Although there are quite allot of translations options in the settings. There does not seem to be one for that main button?

I have tried to change it in css:
.bookacti-submit-form.button:before { content: 'new title';} but that does not seem to work.

Any workarounds?

**Comment by rayedgar** [comment]
Found it! sorry

**Comment by yoancutillas** [comment]
Here is the solution for anyone viewing this thread: 
Go to Booking Activities > Booking forms > your form > go to the "Submit button" settings > "Button text"

With WooCommerce:
Go to Booking Activities > Settings > Messages tab > "Add to cart button label on "Activity" products pages only."
