### ISSUE TITLE
Only one event allowed to book

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#143]
Hi,

Would it be possible to restrict the booking calendar to only one booking per account?
i.o.w. i would also like to use your calendar to create a signuplist where the subscribers are allowed to book only once on one of the selected events.

**Comment by yoancutillas** [comment]
Hello Ray, no this would be up to custom, this custom custom can help you started, you will need to set up you own conditions: #74

**Comment by rayedgar** [comment]
great thanks!
