### ISSUE TITLE
Different cancellation & reschedule options per calendar

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#144]
I guess it's not possible but i try anyway:

I use two kind of calendars:
1) Events that are purchased (they are NOT able to reschedule, but can ask for refund)
2) Events where  its free to signup for an event. (They ARE able to reschedule and cancel,  only one person per calendar?)

I would like to have subscribers of the signuplist (2) to be able to reschedule or cancel (the cancellation terms would be different)

To be able to have unique settings for each calendar would make the BA plugin even more flexible.

**Comment by yoancutillas** [comment]
If the activities are different, you can prevent some activities to be cancelled / rescheduled:
go to Booking Activities > Calendar editor > your activity (1.) settings > Availability tab > "Changes are allowed for bookings starting in at least" = 999 days

However, any further customizations would need custom code.

**Comment by rayedgar** [comment]
Great that works! many thanks
