### ISSUE TITLE
Field for SKU number that will also show up at invoice and booking

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#147]
Future request:
Field for SKU product number (unique number for each activity) that will also show up at invoice and booking.

**Comment by yoancutillas** [comment]
You can display the activity ID 

in the booking list on the frontend ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/display-customers-bookings-list-on-the-frontend/)):
`[bookingactivities_list columns="booking_id,activity_id,events,quantity,status,actions"]`

in the booking list on the backend:
Go to Booking Activities > Bookings > Screen options > Check the "Activity" box to make the "Activity" column appear

In the exports:
Go to Booking Activities > Bookings > Export bookings > Add the "Activity ID" column and generate the export.

In the notifications:
Go to Booking Activities > Settings > Notifications tab > your notification settings > add the {activity_id} tag in the email message.

WooCommerce doesn't include a native invoice feature, so including any Booking Activities data in a third party invoice plugin would be up to custom code.

Would it solve the issue?

**Comment by rayedgar** [comment]
Thank you. Ay! it would be exactly needed on the WC invoice. Using the activity id would not be an unique number. since the activities are instances from the master activity? Basically, in an ideal situation, every instance has its own id. In our situation, all the activities are courses. And we need to separate the different courses with a unique ID.  I now use a 'wrong' method of creating unique activities for every course. The problem with this is that the rescheduling would not allow to change to another activity without custom code.

**Comment by yoancutillas** [comment]
In Booking Activities "_instances from the master activity_" are called "events".

You can do the same with the Events ID:

In the booking list on the frontend ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/display-customers-bookings-list-on-the-frontend/)):
[bookingactivities_list columns="booking_id,event_id,events,quantity,status,actions"]

In the booking list on the backend:
Go to Booking Activities > Bookings > Screen options > Check the "Title" box to make the event "Title" column appear (this won't display the event ID however)

In the exports:
Go to Booking Activities > Bookings > Export bookings > Add the "Event ID" column and generate the export.

In the notifications:
Go to Booking Activities > Settings > Notifications tab > your notification settings > add the {booking_event_id} tag in the email message.

Would it work for you?

**Comment by rayedgar** [comment]
Thats great. If i could inject this als on the WC invoice it would be even better. 

Many thanks, yoancutillas

**Comment by yoancutillas** [comment]
You're welcome :)

**Comment by yoancutillas** [comment]
By the way, recurring events have the same ID, so if you need a distinct ID for each occurrences you need to unbind them:
Go to Booking Activities > Calendar editor > mouse over the repeated event and go to its settings > Unbind > select "Unbind each occurrence" > Unbind.

In that case, each event will have distinct settings, so changing one will no longer affect the others.
Note that you can see the event ID in its settings dialog title.
