### ISSUE TITLE
Manually create order & booking

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#148]
We have a customer who did not order through WC and BA. So we have to put it in manually. We do want to create an invoice through WC.  And creating a manual booking in WC does not book things in BA. and in BA changing a status does not create an invoice.

What's the best way to do this?

**Comment by yoancutillas** [comment]
Hello Ray, you can create a booking and a WC order via the backend thanks to the [Order for Customers](https://booking-activities.fr/en/downloads/order-for-customers/) add-on ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-order-for-customers-add-on/order-for-a-customer-from-backend/)). WC doesn't have a native "invoicing" feature, so I can't tell about creating invoices.

**Comment by rayedgar** [comment]
Thank you.
