### ISSUE TITLE
Calendar list in Descedning order?

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#150]
Is there a way to show the Calendar list in descending order?

**Comment by yoancutillas** [comment]
It appears not unfortunately: Booking Activities' calendar library (Fullcalendar v3) doesn't seem to have that option yet.
So it would require other kinds of workarounds with custom code for FullCalendar. You can find some solutions with a [quick search](https://www.google.com/search?q=fullcalendar+reversed+list+view), and / or add your vote here: https://github.com/fullcalendar/fullcalendar/issues/3647.
