### ISSUE TITLE
Hide activity when fully booked

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#153]
Is there a way to hide an activity/event when it's fully booked (0 left)?

**Comment by yoancutillas** [comment]
Yes, with CSS in Appearence > Customize > Additionnal CSS:
`.bookacti-event-unavailable { display: none !important; }`

**Comment by rayedgar** [comment]
Hello Yoancutillas,

I think that only removes the activity but not the header in list.

⁣

Hartelijke groet,
Ray Edgar​

On 25 Jun 2022, 14:10, at 14:10, yoancutillas ***@***.***> wrote:
>Yes, with CSS in Appearence > Customize > Additionnal CSS:
>`.bookacti-event-unavailable { display: none !important; }`
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bookingactivities/booking-activities/issues/153#issuecomment-1166269992
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by yoancutillas** [comment]
Indeed it is only hidden with CSS, the only way to remove the header in the list view if there are no events to display is to remove the event at the source, with javascript custom code.
