### ISSUE TITLE
extra short codes for flexible layout 

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#155]
I guess a future option? 

Perhaps an advance short code mode:
Split form-short code into 3 elements? 
[calendar], [activity info selected], [quantity, payment etc]

This would give great flexibility and freedom to layout it onto elements. 

Running 4 months on BA and working like a charm!
thanks

**Comment by yoancutillas** [comment]
Thank you, glad Booking Activities is helping you!

This doesn't seem possible as the form fields needs to be included a single specific `<form></form>` element. Moreover, some javascript processes are run automatically and rely on the form structure.

However, you can 
- change the fields order (just drag and drop the fields) in Booking Activities > Booking forms > your form
- add "Free text" fields between your fields (Booking Activities > Booking forms > your form > Add a field > Free text > OK) (they allow you to add HTML)
- add / change the form layout with custom code thanks to the hooks provided in code

**Comment by rayedgar** [comment]
thank you
