### ISSUE TITLE
Link Woocommerce product to single activity / group activity

### ISSUE THREAD

**Issue by NicoG33** [bookingactivities/booking-activities#157]
Hello,

Is it possible to associate directly to woocommerce product, a single activity / group activity without display booking form ?

For example, once product selected, related activity / group activitiy is automatically selected. For activities that have single date, it will avoid to display calendar and to select single activity.

Also on activity definition, is it possible to add meta / attributes like for example (location, speaker,…) ?

thanks

**Comment by yoancutillas** [comment]
Hello, the booking form is compulsory unfortunately. The customer needs to select the event on the calendar.

About the meta / attributes, you can use the WC product attributes.
The [Display Pack](https://booking-activities.fr/en/downloads/display-pack/) add-on also allows you to display additional info when you mouseover / click an event ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-display-pack-add-on/set-additional-event-information-tooltip/), [demo](https://demo.booking-activities.fr/en/shortcodes-integration/)).
