### ISSUE TITLE
Vue par défaut - Liste année

### ISSUE THREAD

**Issue by supermarioh2** [bookingactivities/booking-activities#16]
Bonsoir,

j'ai un problème au niveau d'affichage des activitées en combinaison avec woocommerce / Booking Activities.
Au fait je définis la vue par defaut sur 'Liste année' mais rien ne s'affiche. En cliquant sur 'listes mois' et en recliquant sur 'liste année' les activitées sont alors affichées.

S'agit t'il d'un bug ou d'une mauvaise configuration de ma part?

Version Wordpress: 4.9.6
Woocomerce: 3.4.1
Booking Activities: 1.5.3

Merci pour une réponse rapide,
Mario

**Comment by bookingactivities** [comment]
Bonjour Mario,

Pouvez-vous suivre les instructions sous "Les évènements n’apparaissent pas sur le calendrier" sur cette page: 
https://booking-activities.fr/fr/documentation/faq/
Effectuez les tests
- "Avez-vous une erreur javascript?" et 
- "Votre CSS cache-t-il les évènements?" uniquement

Cordialement,
Yoan Cutillas

**Comment by bookingactivities** [comment]
Bonjour Mario,

Je vais fermer ce ticket pour l'instant, mais n'hésitez pas à le rouvrir ou à en ouvrir un nouveau si vous rencontrez à nouveau ce problème.

Cordialement,
Yoan Cutillas
