### ISSUE TITLE
Keep an active bookable for a fixed period.

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#161]
Hi,
2 questions:

Is there a way to keep an activity bookable for a x period after the date? 
We have 8 week courses and students are allowed to start at the second week. 

It would be cumbersome to keep track manually to disable an activity (no button for that?) to disable, the only way I can think of is to change the amount of places in the activity to the amount booked?

**Comment by yoancutillas** [comment]
Hello Ray,
There is no automated way to do that but,
you can go to Booking Activities > booking forms > your form > Availability tab > 
Opening = the date of the first event of the 8-week group
Display past events = ON
Make past events bookable = ON

Then, you will need to turn OFF the "Make past events bookable" option manually.

**Comment by yoancutillas** [comment]
Yes, to disable an event you need to change its availability to the amount booked. Or you can delete it.
