### ISSUE TITLE
[BUG] Start time not showing when selecting an event

### ISSUE THREAD

**Issue by Zeit08** [bookingactivities/booking-activities#164]
Dear devs,

I have not found a way to show the start time in the event summary. See screenshot, it shows only the end time.
![bug](https://user-images.githubusercontent.com/45097367/192350992-c5ceec6a-8f52-4b30-b13c-0c3f419124a4.png)

Expected behaviour: 01/01/2022 -> 14.00 - 17.00
Actual behaviour: 01/01/2022 -> 17.00

Thank you for your great plugin and for your time reading this.

_V 1.15.3_

**Comment by yoancutillas** [comment]
Thank you!
You probably just need to add the time format (H.i) in Booking Activities > Settings > Messages tab >
Complete date and time format = l j F Y H.i
Short date and time format = d/m/Y H.i
Time format = H.i

**Comment by Zeit08** [comment]
You're right, the H.i was missing in the short date format
