### ISSUE TITLE
Trim empty days toggles off when click ok on the dialog box

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#165]
Hi,
When trying to enable Trim empty days option, it gets toggled off when I click ok on the dialog box!  Is this normal, not sure whats happening.
Video screenshot [https://imgur.com/a/wHBO4RZ](url)
![Booking forms ‹ Capitano Oman — WordPress - Google Chrome 2022-10-07 01-11-44](https://user-images.githubusercontent.com/30695308/194421217-bd3c4412-19a4-416d-bc98-dd0ef90e9422.gif)

**Comment by yabdali** [comment]
Thanks for your suggestion, I tried disabling some of the plugins that I suspected they may cause this issue but still keep seeing the same issue. I had to change it via DB update to the object (form field).  Would it be possible to set this value as the default value since it makes sense to show the next available activity by default?

**Comment by yoancutillas** [comment]
It's already active by default: https://github.com/bookingactivities/booking-activities/blob/1.15.4/functions/functions-booking-system.php#L341

No problem, don't hesitate to resume the debugging instructions if you need more help.
