### ISSUE TITLE
Sticky header problem

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#168]
I seem to have a sticky header  in which the Z-index is not set right. See movie.
I noticed your css , fc-list-sticky is doing this. How can i unstick this?

https://user-images.githubusercontent.com/6242489/196962340-f38ab661-b12c-4abc-8df7-a0100b6f5457.mov

**Comment by yoancutillas** [comment]
Hello Ray,
Indeed, that's a new feature of FullCalendar v5, that's the default behavior. You can unstick it with CSS in Appearence > Customize > Additional CSS:
`.fc .fc-list-sticky .fc-list-day>* { position: relative !important; }`

**Comment by rayedgar** [comment]
That worked. Many thanks for your fast solution!
