### ISSUE TITLE
Login Email details

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#169]
HI,

In the login section  on the frontend is the option to recover the password. iI all works fine. An email is sent. But i cannot find the styling option in the list of notifications emails?

**Comment by yoancutillas** [comment]
Hello Ray, that's because it is not a Booking Activities email. It's a Wordpress default email, so you cannot customize it via Booking Activities, it might be possible via a third party plugin or code ([quick search](https://www.google.com/search?q=wordpress+custom+email+reset+password)).

**Comment by rayedgar** [comment]
I thought as much. Will look into this email templates of WC. Thank you

**Comment by yoancutillas** [comment]
It's not the WooCommerce email that is sent, but the Wordpress default email, so customiziing WC template won't work for now.
I have changed the code to send the WC email instead of WP's in the next version (1.15.5) (the release date is not scheduled yet).
