### ISSUE TITLE
Seems to be a conflict but can't locate source

### ISSUE THREAD

**Issue by RRSnel** [bookingactivities/booking-activities#17]
Hi, I just installed this plug in and running it with wooCommerce. I am using WordPress 4.9.7 running Storefront theme. It looks great but there seems to be a couple of bugs. After creating booking forms, when I go to the booking form menu,  they are not visible to edit. All I see is the page title and add new button. I know these forms exist because they are still available from the product page to choose.
Also, when I test book a product and go to cart, all the usual payment details have disappeared - see screenshot. If I delete the booked product, everything reappears so there seems to be some sort of template override happening. I am using Woocommerce Storefront as a template. 
![screenshot from 2018-08-01 12-31-28](https://user-images.githubusercontent.com/12794510/43519375-18c54b8e-9587-11e8-9273-e4c530ef9575.png)
Normally it looks like this:
![screenshot from 2018-08-01 12-36-28](https://user-images.githubusercontent.com/12794510/43519503-95d0e070-9587-11e8-8b81-fc6ebc47537d.png)

I have tried disabling other plugins to spot a conflict but I don't have much installed yet - only woocommerce and jetpack. I also tried changing themes but that made no difference.

**Comment by bookingactivities** [comment]
Hello,

Thank you for your detailed report.

I have tried StroreFront theme, it's working fine on my side. The problem may come from your configuration. Can you tell me your:
- PHP version
- MySQL version
- Booking Activities version
- WooCommerce version

Try to follow the process under "Booking Activities doesn’t work as it should" on this page: https://booking-activities.fr/en/documentation/faq/

Can you also give me your site URL so I can check the error on your site? (if you want to keep it private, send it to contact@booking-activities.fr)

Regards,
Yoan Cutillas

**Comment by RRSnel** [comment]
Thank you for your reply.
Server version: 5.6.39 - MySQL Community Server (GPL)
My  PHP version: 5.6.30
PHP extension: mysqli cur mbstring
Booking Activities Version 1.5.6
WooCommerce Version 3.4.4

It is a brand new installation and only a test website so far. I will email you the live URL. 
I have since swapped to Twenty Seventeen as theme but there has been no difference so I guess it's nothing to do with the theme (yes I had already run through that faq before posting here).
Here is a  screenshot of the empty booking form page  in admin, if it helps.
![image](https://user-images.githubusercontent.com/12794510/43591449-48875ec2-966b-11e8-8dfc-b45618b22258.png)

**Comment by bookingactivities** [comment]
Thank you, 
This is strange, this kind of behaviour only happens when there is a plugin conflict or when the environment is not up to date, but everything looks OK.

You have deactivated all you plugins except Booking Activities and WooCommerce and activated Twenty Seventeen theme and the error still occurs?

- Can you send me your PHP error log file?
- Would you give me an administrator access to your website (by email) so I can investigate?

Else,
- Can you try to totally remove Booking Activities and re-install it? (you will loose your calendars, forms, and bookings)

Regards,
Yoan Cutillas

**Comment by RRSnel** [comment]
Yes I deactivated all the plugins (I only have one or two apart from
WooCommerce). Here is the error log file. I have added you as an admin -
you should have received a mail about that to your own email? Let me know
if not. I will try reinstalling after you have had a look if you can't see
anything odd.

**Comment by bookingactivities** [comment]
Thank you very much for your trust.

It seems that the PHP extension "mbstring" isn't activated. 
Can you activate it and try again? (you may need to ask your web host to do it for you)

Regards,
Yoan Cutillas

**Comment by RRSnel** [comment]
That was it!! I was able to activate it from my cPanel and voila,
everything works. Wonderful, thank you so much!
And thank you for a great plugin, it is just what we needed.

Thank you for the help and time
Best regards
Rebecca

**Comment by bookingactivities** [comment]
Great! Thank you!

I wish you the best for you and your booking site.

Regards,
Yoan Cutillas
