### ISSUE TITLE
Secret key export

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#170]
HI,

After updating the export link in  (export bookings->generate export link) i get either' invalid secret key' error or an empty list.
I know updates could take some time. But normally they appear immediately in google docs.

I use the following formula: 
=QUERY(IMPORTDATA("THESECRETKEYCOPIED");" select * order by Col1 asc")

I have used the reset button, and now it seems i cannot go back to an older version in google docs?

Is this a bug?

**Comment by rayedgar** [comment]
it seems to work now, sorry for  this.

**Comment by yoancutillas** [comment]
Hello Ray, no problem.
The reset button invalidates all the previously generated export links.
