### ISSUE TITLE
Allow "group_by=none" in Dashboard » Bookings page

### ISSUE THREAD

**Issue by SophieWeb** [bookingactivities/booking-activities#171]
Hello,

I’ve created a “My bookings” page with a shortcode `[bookingactivities_list group_by="none"]` to display grouped bookings as several lines rather than only one group.

But when clients visit their Woocommerce Dashboard and view the “Bookings” page, they see only a group and not separate lines. I’ve been able to solve it by removing the `bookacti_display_my_account_bookings_tab_content` function in my functions.php file and replacing it with a modified function including the `[bookingactivities_list group_by="none"]` shortcode. Is there a better way to do this?

**Comment by yoancutillas** [comment]
Hello Sophie,
Yes, you can simply select your “My bookings” page in Booking Activities > Settings > WooCommerce tab > "Bookings page in My Account" option :)

You may need to refresh your permalinks afterwards:
Go to Settings > Permalinks > click "Save changes"

**Comment by SophieWeb** [comment]
Thanks Yoan, it works perfectly!
