### ISSUE TITLE
Display start calendar from a fixed date ?

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#172]
We have bookings that are currently all booked.
To avoid that the user has to scroll or down to see the latest available ones, it would be very useful to be able to display the calendar from a date in the future. (so we skip a long list of booked activities) 

Is that possible? If not it would be a useful feature. 

I don't think there is a way to, not displaying certain activities manually? (perhaps a nice addition to add a do not display button?)

Thanks again!
Ray

**Comment by yoancutillas** [comment]
Hello Ray,

Yes, you can display the calendar from a fixed date manually in Booking Activities > Booking forms > your form > Calendar settings > Availability tab > "Opening" option.

You can choose the activities to display in Booking Activities > Booking forms > your form > Calendar settings > Filters > "Activity" option (click the "+" icon to select multiple values).

However, there is no way to automatically hide the unavailable events. I note your feature request, thank you!
