### ISSUE TITLE
Bought products not bound to activity

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#173]
Hi,

Oh dear! I forgot to bound the activity in the product settings.
The product has been bought by quite a few customers.
But they are not being booked by BA because of this..

What can i do to insert the already bought products into BA?

**Comment by yoancutillas** [comment]
Hello Ray,

With the [Order for Customers](https://booking-activities.fr/en/downloads/order-for-customers/) add-on, you can add a booking and bind it to the order from the backend: [docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-order-for-customers-add-on/order-for-a-customer-from-backend/).

Without that add-on, you can display a booking form on a page (with its shortcode) and ask your customers (by email) to make a booking corresponding to their order. However, the booking won't be bound to the order.

**Comment by rayedgar** [comment]
Clear! thank you.
