### ISSUE TITLE
I can't edit a field: "Invalid nonce...."

### ISSUE THREAD

**Issue by elsurell** [bookingactivities/booking-activities#174]
Hi! I have created some calendars with different fields. When I try to edit a field (in all calendars), I can’t do it. Appears a message like: "Invalid nonce. Please reload the page and try again". I have tried to reaload the page many times, but I could never edit the fields, and I have to create a new one if I want to modify any field.
<img width="438" alt="Captura de pantalla 2022-12-20 a les 17 24 07" src="https://user-images.githubusercontent.com/121121637/208725977-a2f3a294-f3a5-42cb-bc90-799fde0bab73.png">

Why? Thanks a lot

**Comment by yoancutillas** [comment]
Hello, thank you for reporting, can you update the Advanced Forms add-on to 1.2.28 and try again?

**Comment by elsurell** [comment]
Hi Yoan, with 1.2.28, now it works fine
Thanks a lot
Pere

Missatge de yoancutillas ***@***.***> del dia dt., 20 de des.
2022 a les 19:35:

**Comment by yoancutillas** [comment]
Thank you for your confirmation!

**Comment by elsurell** [comment]
Hello, the events appears duplicated in all calendars, and I don’t know
why. I have tried to fix it, selecting different options, but it doesn’t
work.

This is one of  the links:
https://somguies.cat/cursos-i-formacio/curs-esqui-de-muntanya-iniciacio/

Can you help me?

Thanks
