### ISSUE TITLE
Events appears duplicated in all calendars

### ISSUE THREAD

**Issue by yoancutillas** [bookingactivities/booking-activities#175]
Hello, the events appears duplicated in all calendars, and I don’t know why. I have tried to fix it, selecting different options, but it doesn’t work.

This is one of  the links:
https://somguies.cat/cursos-i-formacio/curs-esqui-de-muntanya-iniciacio/

Can you help me?

Thanks

>
> Message ID: <bookingactivities/booking-activities/issues/174/1361180234@
> github.com>
>

_Originally posted by @elsurell in https://github.com/bookingactivities/booking-activities/issues/174#issuecomment-1368061238_

**Comment by yoancutillas** [comment]
Hello, 
This may be due to your caching plugin, especially object cache (Redis), can you try to deactivate your cache plugin, and your Object Cache tool and try again?

If it doesn't work, can you try to deactivate all your plugins, except Booking Activities, and activate the theme [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/), and try again?

If the problem occurs even with that configuration, can you send me an export of the database table starting with wp_bookacti_ and wp_options? (at contact@booking-activities.fr)

**Comment by elsurell** [comment]
Hi Yoan, it seems the problem it was object cache (Redis). Now works fine!
I'm using W3 Total Cache, with no problem...
By the way, do you know how can I hide the second row of this table? (item
name of the activity, I don't want appears it)

[image: Captura de pantalla 2023-01-02 a les 20.10.10.png]
Thanks
Pere

Missatge de yoancutillas ***@***.***> del dia ds., 31 de des.
2022 a les 13:32:

**Comment by yoancutillas** [comment]
Thank you for your feedback.

This is probably due to the configuration of the object cache (maybe an option that caches too agressively).
Booking Activities should be compatible with object cache, the [demo website](https://demo.booking-activities.fr/en/shop/calendar/) has Memcached running currently (using SiteGround Optimizer).
