### ISSUE TITLE
Cancel or rescheduling 

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#178]
I use BA for selling activities where i do not want the customer to reschedule or cancel.
I  also use BA for a class list where people sign up for free. For the last one i would like to let them cancel or reschedule themself.

Is there a way to do this?

**Comment by yoancutillas** [comment]
You can prevent some activities from being cancelled / rescheduled:
- in Booking Activities > Settings > Cancellation tab > 
  - turn ON "Allow customers to cancel their bookings"
  - turn ON "Allow customers to reschedule their bookings" 
  - set "Changes are allowed for bookings starting in at least" to "0 days, 0 hours, 0 minutes"
- in Booking Activities > Calendar editor > open the settings of the activities that you don't want customers to be able to reschedule or cancel > Availability tab
  - set "Changes are allowed for bookings starting in at least" to "9999 days, 0 hours, 0 minutes"

So your customers can reschedule and cancel their bookings by default, except for the activities where you set the changes delay to 9999 days.

**Comment by rayedgar** [comment]
Fantastic! thank you so much for your fast response again. 
BA has been running smooth for over a year now. Very happy with it.

**Comment by yoancutillas** [comment]
Great, thanks a lot! Glad you enjoy Booking Activities :)
