### ISSUE TITLE
Notification email based on booking form

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#179]
Probably a feature request:

I use BA for free signups and for paid ones. 
The instructions etc in the confimation email are therefore very different.

Linking different notification emails to booking forms would make it much more flexible.

**Comment by yoancutillas** [comment]
It is possible to create a different notification **per calendar** and / or **per activity** with the [Notification Pack](https://booking-activities.fr/en/downloads/notification-pack/) add-on ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-notification-pack-add-on/create-per-activity-or-per-calendar-notifications/)), but not per booking form. I note your request, thank you.

**Comment by rayedgar** [comment]
OK. that might be an option. Many Thanks!

**Comment by yoancutillas** [comment]
Closed because too similar to existing filtering options.
