### ISSUE TITLE
Pb affichage avec Woocommerce

### ISSUE THREAD

**Issue by 90west** [bookingactivities/booking-activities#18]
Bonjour,

Je suis en train de tester votre plugin qui m'a l'air super et que je vais surement adopter.
Mais j'ai un problème quand j'utilise Woocommerce. dans l'onglet "activité" de la page produit.
Toutes les options ne s'affichent pas.
![2018-08-29_09h15_35](https://user-images.githubusercontent.com/42799029/44773805-c506a000-ab71-11e8-93bd-a5c4a4687155.png)
Et une fois la page validée : le formulaire de réservation ne s'affiche pas.
Avez-vous une idée pour corriger ce problème ?

Merci et bon courage pour la suite.

Jean-Luc

**Comment by bookingactivities** [comment]
Bonjour Jean-Luc,

Merci beaucoup pour votre intérêt envers Booking Activities.

Depuis Booking Activities 1.5, il n'y a qu'un unique champ "Formulaire de réservation" à lier au produit, c'est normal. Toutes les options de personnalisation du calendrier et du formulaire sont dans l'éditeur de formulaire.

Pouvez-vous vérifier que:
1. Votre produit a un prix supérieur à 0
2. Le calendrier s'affiche bien sur l'éditeur de formulaire (menu "Booking Activities" > "Formulaires de réservations" > votre formulaire ("Formulaire n°10" selon la capture d'écran) )

Si c'est bien le cas, suivez les instructions sous "Le calendrier n’apparaît pas" ici: [https://booking-activities.fr/fr/documentation/faq/](https://booking-activities.fr/fr/documentation/faq/) et donnez moi les résultats.

Cordialement,
Yoan Cutillas

**Comment by 90west** [comment]
Merci beaucoup, ça fonctionne !
Juste le problème de prix non indiqué.

Cordialement

Jean-Luc Piaget

**Comment by bookingactivities** [comment]
Bonjour,

Ok, super !
En effet, lorsque le prix n'est pas renseigné, WooCommerce n'affiche pas du tout le formulaire d'ajout au panier (remarquez qu'il n'y a pas de bouton "ajout au panier", ni de champ "quantité"). Or le formulaire de réservation de Booking Activities est intégré au formulaire d'ajout au panier de WooCommerce.

Cordialement,
Yoan Cutillas
