### ISSUE TITLE
Calendar does not display properly in Week/Day view (Wordpress)

### ISSUE THREAD

**Issue by roberto-dridam** [bookingactivities/booking-activities#180]
Hi, I followed all the instructions on the documentation to create a simple calendar and booking form. Then I add the shortcode to the page I want it to be displyed and I get a weird output in week & day display (the Month display looks perfect). Please see screenshots:
![day](https://user-images.githubusercontent.com/122928947/212999842-e603fef4-65a8-412f-9730-51aef6bc5290.JPG)
![week](https://user-images.githubusercontent.com/122928947/212999854-90a7de6d-673e-4e3c-b798-a918c7a5b150.JPG)

I have not done anything else (no css, no change to code). Any ideas????

Thanks!

**Comment by yoancutillas** [comment]
Hello, this is probably due to the CSS of a third party plugin / theme.
Can you follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ ?
