### ISSUE TITLE
Missing 'Text' parameter in notifications

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#181]
Am I missing the Textfield parameter to include in the notification setting? for me very important because i displays vital info for us.

<img width="448" alt="Screenshot 2023-01-20 at 11 25 23" src="https://user-images.githubusercontent.com/6242489/213673175-bab20166-4cd7-48cf-bd58-0b129a6c3571.png">

<img width="203" alt="Screenshot 2023-01-20 at 11 24 53" src="https://user-images.githubusercontent.com/6242489/213673509-5d06f440-356b-4d56-ba5b-9235595e7b97.png">

**Comment by rayedgar** [comment]
basically looking for the tooltip info to include in notifications.

**Comment by yoancutillas** [comment]
Hello Ray, 
You should find this field in the "General" tab of the event / activity / group of events / group category settings, in the calendar editor.

Regarding the {specific_message} and {specific_message_raw} tags, indeed, they should be displayed on the top of the tags list in Booking Activities > Settings > Notifications tab > your notification settings.

Can you make sure Booking Activities (1.15.6) and Notification Pack (1.2.18) are both activated and up to date?

**Comment by rayedgar** [comment]
Hi Yoancutillas,

What i meant is the text 'Einddatum 16 maart' (see image above) which i set on an activity, to be displayed in the e-mail notifications.notifications. There are quite a few content {} to choose from but cannot find one that will display that text 'Einddatum: 16 maart'

**Comment by yoancutillas** [comment]
Yes, the feature to set a text in the activity settings and use it in the notifications is included in the [Notification Pack](https://booking-activities.fr/en/downloads/notification-pack/) add-on ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-notification-pack-add-on/include-event-specific-messages-in-notifications/)).

On your screenshot, the "Event information" field is added by the [Display Pack](https://booking-activities.fr/en/downloads/display-pack/) add-on and is displayed in a tooltip when you mouseover the event on the calendar, there is no tags to add this text in a notification (it is only possible with custom code).
