### ISSUE TITLE
Notification Pack add-on recipients question

### ISSUE THREAD

**Issue by n-a-m-e** [bookingactivities/booking-activities#182]
Sorry if this is the wrong place to ask, but we are using the advanced forms add-on to collect participant details for our events.
The person purchasing is usually not the person attending. Therefore we collect the participants email and phone number with the advanced forms add-on.
Is it possible to use the Notification Pack add-on to send an email or sms to a participants email address or phone number collected with an advanced form field.

I just wanted to ask before I purchase the Notification Pack since it wasn't clear from the information page.

**Comment by yoancutillas** [comment]
No, unfortunately this is not possible, the only way to do that would be with custom code. I note your feature request, thank you.

**Comment by yoancutillas** [comment]
Released in [Advanced Forms](https://booking-activities.fr/en/downloads/advanced-forms/) 1.4 ([docs](https://booking-activities.fr/en/blog/advanced-forms-1-4-send-the-notifications-to-all-participants/)).
