### ISSUE TITLE
Impossible to create new activity type : duration fields are not displayed

### ISSUE THREAD

**Issue by SophieWeb** [bookingactivities/booking-activities#183]
In Firefox 109.0.1, the duration fields are not displayed in the General tab. It’s impossible to create a new activity as these fields are required.

![Editeur de plannings — WordPress](https://user-images.githubusercontent.com/40994425/216293965-a2fec21f-b0ca-4e32-9553-c2c5b48fe72b.jpg)

**Comment by yoancutillas** [comment]
Hello Sophie, thank you for reporting, this is due to the browser add-on "DuckDuckGo Privacy Essentials".
I have reported the issue here: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1679

You can deactivate this add-on, or use another browser / device until it is fixed.

**Comment by SophieWeb** [comment]
Hello Yoan, thanks for the info.
I went to the DuckDuckGo Privacy Essentials Add-on **Preferences** tab and added the site where Booking Activities is installed to the **Unprotected sites** list.
Adding the site to the whitelist works fine.
