### ISSUE TITLE
Duplicate Events in Calendar

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#184]
Hi,
Few weeks ago I noticed that the calendar shown in the product page having duplicate events/activities. I turned off Redis, and cache plugins, flushed CF cache and changed the theme from Neve to Twenty Twenty-Three but I still have the same problem. Appreciate if you can highlight how to troubleshoot further. Thanks
 
![bookinfactdup](https://user-images.githubusercontent.com/30695308/219447825-6818a8ee-bcee-4184-810e-791909b7c038.png)

![bookinfactdup2](https://user-images.githubusercontent.com/30695308/219447882-b4ce3653-6690-431e-a1b2-d89256790e16.png)

**Comment by yoancutillas** [comment]
Hello, thank you for your tests and for reporting!
I could reproduce the issue, it will be fixed in the next update.

As a workaround, go to Booking Activities > Booking forms > your form > Calendar settings > Availability tab > empty the "Opening" and "Closing" options. (if it doesn't work, try to validate the dialog with the "Reset button").

**Comment by yabdali** [comment]
> Hello, thank you for your tests and for reporting! I could reproduce the issue, it will be fixed in the next update.
> 
> As a workaround, go to Booking Activities > Booking forms > your form > Calendar settings > Availability tab > empty the "Opening" and "Closing" options. (if it doesn't work, try to validate the dialog with the "Reset button").

The Reset button did the trick, I had to reconfigure it again. I would need to go and do the same for the rest of the forms.  Is there an easier way to fix this, I have to write down each trip/activity details before pushing the rest so I can remember what it was set to originally.

**Comment by yoancutillas** [comment]
Emptying the "Opening" and "Closing" options should be enough.
Else, empty all the fields in the "Availability" tab only, and turn ON the "Trim" option.
![image](https://user-images.githubusercontent.com/9415030/219624746-410cfe0c-3d9d-4dfe-9249-72da20b29209.png)

**Comment by yoancutillas** [comment]
Released in Booking Activities 1.15.8 and Display Pack 1.4.31
