### ISSUE TITLE
Compatibilité avec lms masterstudy de stylemixtheme

### ISSUE THREAD

**Issue by pokerman007** [bookingactivities/booking-activities#185]
Bonjour,
Mon install est la suivante : 
* wordpress 6.1.1
* licence thème masterstudy + lms masterstudy
* woocommerce dernière version
* licence élémentor
* votre plugin dernière version (installé et activé)
j'ai fait quelques réglages, crée un planning, crée une activité, je retrouve bien le champ activité dans la page du produit woocommerce.
1 quand je veux configurer avec élémentor impossible d'afficher la page
2 lorsque j'actualise en frontend la page une erreur fatale se produit en lien avec votre plugin : 
_"Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /home/clients/da0ce6680ee2ea79fce35e4e7aad3d8e/amformations/wp-content/plugins/booking-activities/controller/controller-woocommerce-frontend.php:1630 Stack trace: #0...."_
en vous remerciant de votre éclairage.
Alexandre

**Comment by yoancutillas** [comment]
Bonjour Alexandre,

D'après l'erreur PHP, le problème est qu'un plugin / thème tiers ne retourne pas un `array` sur le hook [safe_style_css](https://developer.wordpress.org/reference/hooks/safe_style_css/) (voir [code source](https://github.com/bookingactivities/booking-activities/blob/1.15.7/controller/controller-woocommerce-frontend.php#L1630)), mais un `null`.

Vous pouvez identifier le plugin / thème en faute en suivant les instructions sous "Booking Activities ne fonctionne pas comme il le devrait" ici : https://booking-activities.fr/fr/documentation/faq/

Une fois identifié, contactez le support du plugin / thème pour les informer qu'ils doivent retourner un array et non un null sur le hook safe_style_css.

**Comment by pokerman007** [comment]
Bonjour,
Merci pour votre retour. j'ai effectivement décelée quelle était l'extension coupable. et il s'avère que c'est la plus importante de mon site ( lms masterstudy de stylemixtheme) et que je ne pourrai pas la toucher.
dommage car pour un rare plugin français j'aurai aimé aller aubout.
Alexandre

**Comment by yoancutillas** [comment]
Il suffit de leur rapporter le problème comme vous me l'avez rapporté, c'est très simple à corriger, ils pourront probablement le corriger rapidement ou vous donner un fix temporaire :)

**Comment by yoancutillas** [comment]
Bug rapporté ici : https://wordpress.org/support/topic/bug-report-you-must-return-array-on-safe_style_css-hook/
