### ISSUE TITLE
Succesfull booking shows pending in invoice

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#186]
After successful payment the WC invoice sent to customer show status "pending" in the WC completed order email. The invoice in thankyou page shows has status "booked"  The booking in BA itself seems to be fine and is status "booked".

In BA settings; default booking state is set to : Booked and default payment is set to Paid.

Seems to have happened in update 1.1.5.8 checked with older stage environment 1.15.7 and WC 7.3.0 which seems to not show this problem.. 
current setup BA 1.15.9 / WC 7.4.1.  i have this problem with.

I downgraded to 1.15.7 and that seems to give no problem with problem described above, With update1.1.5.8 this started to happen. And can reproduce.
Would it be safe to downgrade 1.15.9 to 1.15.7 on live site?

<img width="1630" alt="Screenshot 2023-03-02 at 11 41 12" src="https://user-images.githubusercontent.com/6242489/222405856-54cc3491-fac8-41b8-9d67-34af035434cf.png">
<img width="935" alt="Screenshot 2023-03-02 at 11 37 32" src="https://user-images.githubusercontent.com/6242489/222405859-d2f07639-1ab3-42af-8f7a-fe026b3a3817.png">

**Comment by yoancutillas** [comment]
Thank you for reporting, I could reproduce and fix the issue. The fix is queued for the next version.
I don't know if it is safe to rollback to 1.15.7, I would recommand applying the fix of the commit mentionned above instead.

**Comment by rayedgar** [comment]
Thank you for the fix. Our live site is running 1.15.9 your fix was for .8 to .10
could i still copy the code?

**Comment by yoancutillas** [comment]
Yes, it's just that the code for these functions has not changed since 1.15.8, that's why the version of the functions bumps from 1.15.8 to 1.15.10.
