### ISSUE TITLE
Preview booking ist in bookings not working anymore

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#187]
It seems that after the update the Preview booking list in bookings (backside)  is not working anymore!

so rollover the activities does not show info.

Older version does work. can reproduce.

<img width="398" alt="Screenshot 2023-03-06 at 10 58 11" src="https://user-images.githubusercontent.com/6242489/223078546-29c93c8f-fc60-4d23-9aa7-a8452716e539.png">

**Comment by yoancutillas** [comment]
Hello Ray, I don't reproduce the issue on my side.

Can you confirm that Booking Activities (1.15.9) and its add-ons are all up to date (see latest versions [here](https://booking-activities.fr/en/add-ons/)).
If you are using custom code, can you try to deactivate it (if it is in your child theme, activate another theme).

I can see that you only display one column: Email. If this column is empty, the tooltip won't appear at all. Can you try to display the "id" column as well? (this column is never empty).

**Comment by rayedgar** [comment]
Hello yoancutillas,

I have latest updates 1.15.9. and displaypack 1.4.31.
I removed all extra code in functions.php
display column setting was a temp workaround to be able copy paste members of class.
could i have made an error copy pasting the fix code from previous fix? i checked and seems okay? could i use the latest full code of the files from github version 1.15.10?

**Comment by yoancutillas** [comment]
Can you:
- Download Booking Activities from here: https://wordpress.org/plugins/booking-activities/
- On your website, go to Plugins > Add new > Upload plugin > Choose file: select the .zip file you just downloaded > Install now > Replace current with uploaded
- Deactivate all your plugins except Booking Activities, its add-ons and WooCommerce
- Activate [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) theme
- In Booking Activities > Bookings > Booking calendar settings > Preview booking list columns, add the "id" column > OK
- Refresh the page, open the Booking calendar settings again and make sure the settings were saved
- Try to mouseover a booked event

and confirm that the issue still occurs?

In that case, I would need an administrator access to a website where I can reproduce the issue (you can send the credentials to contact@booking-activities.fr).

**Comment by rayedgar** [comment]
With all plugins deacivated except BA and Display pack it seems the display  pack is the culprit. Deactivating display pack solves the problem. 
The display pack was due for new license and is paid but still getting message it will expire. Any actions needed there?
I have sent you admin login details. 
Many Thanks.

**Comment by yoancutillas** [comment]
Ah! My bad, this is due to the option in Booking Activities > settings > "Tooltip display timeout (on mouseover)"
Since Display Pack version 1.4.31:
`* Tweak - Use the "Tooltip display timeout (on mouseover)" delay to display the booking list tooltip too`

And this option is set to -1 in your case, that is to say, it is set to not display tooltip at all.

**Comment by rayedgar** [comment]
Ah! Yes! I thought it might be that. Thanks!
