### ISSUE TITLE
Automatic booking approval

### ISSUE THREAD

**Issue by threbicek** [bookingactivities/booking-activities#19]
Hello,

is there option to let client's booking approved automatically?

Thank you.

**Comment by bookingactivities** [comment]
Hello,

Yes, in Booking Activities settings, in the "General" tab, you can set the default booking status to "Booked".

If you use Booking Activities with WooCommerce, bookings are automatically "Booked" if the payment is completed. Else, they remain "Pending" regardless of the previously mentionned setting, until they are paid or an administrator switch the order status to "Complete".

Regards,
Yoan Cutillas

**Comment by threbicek** [comment]
Ah, how could I've missed this. It works exactly how I need to now. 

Thank you very much for such a quick and elaborated reply!

Best regards,
Tomas H.

**Comment by bookingactivities** [comment]
Hello Tomas,

You are welcome! Thank you for your feedback.

Regards,
Yoan Cutillas
