### ISSUE TITLE
24 hours time is mixed with 12 hours time

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#192]
The calendar is set with 12 hours time. But when selected it shows the activity in 12 hours time?
<img width="724" alt="Screenshot 2023-04-10 at 08 49 13" src="https://user-images.githubusercontent.com/6242489/230844159-8bb261ec-c33a-49b4-b6e7-21112bd4cf41.png">
<img width="744" alt="Screenshot 2023-04-10 at 08 44 47" src="https://user-images.githubusercontent.com/6242489/230844169-e91ec673-01e4-43e1-9667-d97aaa4d2335.png">

**Comment by yoancutillas** [comment]
Hello Ray,

The calendar time format is based on the "Site language" in Settings > General.
You can 
- change your Site Language
- make it to be based on the "Time format" option in Settings > General, by changing this option : Booking Activities > General > Calendar localization = "Based on more WP settings (Site Language, Time Format, Week Starts On)"

The time format in the other texts are based on the settings in Booking Activities > Settings > Messages tab > "Complete date and time format.", "Short date and time format." and "Time format.".

**Comment by yoancutillas** [comment]
The time format in the calendar looks 24h,
Now if you want the other texts time format to be 24h, you need to change these options:
Booking Activities > Settings > Messages tab > (for example):
- "Complete date and time format" = l, F jS, Y H:i
- "Short date and time format" = M, jS - H:i
- "Time format" = H:i

**Comment by rayedgar** [comment]
Although the activity are 24 hours. The selected text which show the extra info there the time is shown in 12 hour (AM PM

**Comment by yoancutillas** [comment]
Can you confirm that you have set the values given in my previous post for the "Complete date and time format", "Short date and time format", and "Time format" options?

In that case, if you are using a caching tool, please try to clear your cache.

If the problem still occurs, I will need an adminsitrator access to the website or a development website where I can reproduce the issue (at contact@booking-activities.fr) to debug it.

**Comment by rayedgar** [comment]
Hi,

I tried all of the three suggested time notifications. caching flushed. I will sent you an administrator access

Many thanks!

Op 13 apr. 2023 12:23, om 12:23, yoancutillas ***@***.***> schreef:
