### ISSUE TITLE
BA throws error in pagesource

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#193]
When looking at page source of homepage: https://theceramiccentre.com/

i see this:

<meta name="viewport" content="width=device-width, initial-scale=1">
--
  | <link rel="profile" href="https://gmpg.org/xfn/11">
  | <script>
  | var bookacti_localized = {"error":"An error occurred.","error_select_event":"You haven&#039;t selected any event. Please select an event.","error_corrupted_event":"There is an inconsistency in the selected events data, please select an event and try again.","error_less_avail_than_quantity":"You want to make %1$s bookings but only %2$s are available for the selected events. Please choose another event or decrease the quantity.","error_quantity_inf_to_0":"The amount of desired bookings is less than or equal to 0. Please increase the quantity.","error_not_allowed":"You are not allowed to do that.","error_user_not_logged_in":"You are not logged in. Please create an account and log in first.","error_password_not_strong_enough":"Your password is not strong enough.","loading":"Loading","one_person_per_booking":"for one person","n_people_per_booking":"for %1$s people","booking":"booking","bookings":"bookings","go_to_button":"Go to","ajaxurl":"https:\/\/theceramiccentre.com\/wp-admin\/admin-ajax.php","nonce_query_select2_options":"a97c059c09","nonce_cancel_booking":"bd37b40f72","nonce_refund_booking":"9fc744dd56","nonce_reschedule_booking":"dd7086b2ea","fullcalendar_timezone":"UTC","fullcalendar_locale":"en-gb","current_lang_code":"en","current_locale":"en_GB","available_booking_methods":["calendar","waterfall"],"booking_system_attributes_keys":["id","class","hide_availability","calendars","activities","group_categories","groups_only","groups_single_events","multiple_bookings","bookings_only","tooltip_booking_list","tooltip_booking_list_columns","status","user_id","method","auto_load","start","end","trim","past_events","past_events_bookable","days_off","check_roles","picked_events","form_id","form_action","when_perform_form_action","redirect_url_by_activity","redirect_url_by_group_category","display_data","tooltip_event_info","hide_timepicker","product_by_activity","product_by_group_category","products_page_url"],"event_tiny_height":32,"event_small_height":75,"event_narrow_width":70,"event_wide_width":250,"calendar_width_classes":{"640":"bookacti-calendar-narrow-width","350":"bookacti-calendar-minimal-width"},"started_events_bookable":0,"started_groups_bookable":0,"event_load_interval":"92","initial_view_threshold":640,"event_touch_press_delay":"350","date_format":"l, M, j - H:i","date_format_long":"l, F j, Y H:i","time_format":"l, F j,  H:i","dates_separator":"\u2192\u00a0","date_time_separator":"\u00a0\u2192\u00a0","single_event":"Single event","selected_event":"Selected event","selected_events":"Selected events","avail":"avail.","avails":"avail.","hide_availability_fixed":0,"dialog_button_ok":"OK","dialog_button_cancel":"Close","dialog_button_cancel_booking":"Cancel booking","dialog_button_reschedule":"Reschedule","dialog_button_refund":"Refund","plugin_path":"https:\/\/theceramiccentre.com\/wp-content\/plugins\/booking-activities","is_admin":0,"current_user_id":2,"current_time":"2023-04-18 12:26:48","calendar_localization":"wp_settings","wp_date_format":"d\/m\/Y","wp_time_format":"H:i","wp_start_of_week":"1","price_format":"&euro;&nbsp;{price}","price_thousand_separator":".","price_decimal_separator":",","price_decimal_number":2,"pick_single_or_group_of_events":"Single or grouped with other events.","pick_group_of_events":"Grouped with other events.","calendar_button_list_year":"list year","calendar_button_list_month":"list month","calendar_button_list_week":"list week","calendar_button_list_day":"list day","calendar_button_flexible":"{days} day","calendar_button_multiple_months":"{months} month","tooltip_mouseover_timeout":"350","tooltip_mouseover_default":"auto","no_events":"No events available.","expired":"expired","days":"days","day":"day","error_cart_expired":"Your cart has expired.","add_product_to_cart_button_text":"Add to basket","add_booking_to_cart_button_text":"Book"};
  | </script>

**Comment by yoancutillas** [comment]
Hello Ray, there is no errors here, just PHP passing variables to javascript :)

**Comment by rayedgar** [comment]
Good To hear! many thanks again.
