### ISSUE TITLE
Message d'erreur

### ISSUE THREAD

**Issue by ludovic94** [bookingactivities/booking-activities#194]

**Comment by ludovic94** [comment]
Bonjour,

J'ai installé votre plugin afin de pouvoir à la fois vendre des cours sur mon site avec le plugin Tutor LMS et vendre des coaching en mettant à disposition des créneaux via votre plugin.

Au début tout fonctionnait bien et lorsque je cliquais sur un événement puis sur réserver, le mail partait bien et j'avais bien la réservation.

Dès que j'ai ajouter woocommerce et que j'ai créé un produit pour mettre mon coaching, sur la page en question j'ai le message d'erreur suivant quand je tente de réserver un événement

![image](https://user-images.githubusercontent.com/53654865/233167937-8b8295da-931b-47ab-a958-834e7f98b61f.png)

Pourriez-vous m'aider sur le sujets ?

En vous remerciant pour votre aide.

Ludovic

**Comment by yoancutillas** [comment]
Bonjour,
En effet, il y a un problème de compatibilité connu avec Tutor LMS qui produit cette erreur (Aucun évènement sélectionné) : [Problèmes de compatibilité connus avec des extensions ou thèmes tiers](https://booking-activities.fr/fr/documentation/faq/)

Un utilisateur a réussit à résoudre le problème ici : https://wordpress.org/support/topic/plugin-compatibility-issue-9/
La solution serait de ne pas charger le fichier tutor-front.js sur les pages où un calendrier de Booking Activities est affiché.
