### ISSUE TITLE
When customer books, sometimes 2x the number of spaces is taken

### ISSUE THREAD

**Issue by Amamficat** [bookingactivities/booking-activities#198]
A customer books 3 spaces. They are charged for 3, get an email for 3, but 6 slots are taken up and unavailable for booking. This has been happening for a few months. Not related to cart timeouts.

**Comment by yoancutillas** [comment]
Hello, we would need to be able to reproduce the issue on demand to find its origin.
Can you send me a link to the product page and instructions to reproduce the problem?

If you don't know how to reproduce it, can you still send me a link to the product page? I can try to make some tests.

We can also compare and analyse the orders, can you send me screenshots of:
- at least two orders were the problem occured
- at least two orders where the problem didn't occured
To do that, go to WooCommerce > orders > click the order > here, take a screenshot, I need to see the "Payment via" line, the "Date created" and "Status", all the "Order notes" and all the "Items".
