### ISSUE TITLE
JavaScript onKeyUp undefinied

### ISSUE THREAD

**Issue by mrkv2** [bookingactivities/booking-activities#199]
User
28shortcutsService.js:321 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at onKeyUp (shortcutsService.js:321:31)
56shortcutsService.js:321 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at onKeyUp (shortcutsService.js:321:31)
onKeyUp @ shortcutsService.js:321
Afficher 1 autre frame
Afficher moins
28shortcutsService.js:321 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at onKeyUp (shortcutsService.js:321:31)
28shortcutsService.js:321 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at onKeyUp (shortcutsService.js:321:31)

Il semble que vous rencontriez un problème avec votre fonction JavaScript onKeyUp. 
shortcutsService.js:321 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at onKeyUp (shortcutsService.js:321:31)

**Comment by yoancutillas** [comment]
Bonjour, désolé il y a erreur, ce fichier n'appartient pas à Booking Activities ni a ses modules.
