### ISSUE TITLE
Store Credit Instead of Coupon Code?

### ISSUE THREAD

**Issue by blackhatwarrior** [bookingactivities/booking-activities#20]
Can't we allow customer to convert their booking amount into Store credit instead of a Coupon code? The Coupon code has a limit that it can only be used once for any order at any time but with Store credit multiple orders can be placed until its completely used up. 

Also, When a Coupon code is requested, the order status changes to "Refunded". Don't you think "Refunded" is an inappropriate term in this case? We're not actually refunding money to the customer. It should say Converted to Coupon/Store Credit.

**Comment by blackhatwarrior** [comment]
I am using WooCommerce Smart Coupons plugin which does feature a credit system. I was able to generate Store Credit instead of Coupon by making following changes to functions-woocommerce.php file in Booking Activities plugin.

'type'  => 'smart_coupon',
'usage_limit' => "",

Since your plugin doesn't support templates I can't copy the edited file to a child theme. What is the best to achieve this through Booking Activities API so that I don't have to edit plugin file?

**Comment by bookingactivities** [comment]
Hello,

Do you only need to change that to get it work with WooCommerce Smart Coupons plugins? 

I will add a hook in the next version, in the functions-woocommerce.php file, between the [lines 1919](https://github.com/bookingactivities/booking-activities/blob/master/functions/functions-woocommerce.php#L1919) and 1920:
```
$data['coupon']['code'] = sprintf( $code_template, $user_id, $i );
$data = apply_filters( 'bookacti_refund_coupon_data', $data, $user_data, $item );
```

Add this code now in your copy of Booking Activities. 
Then you will be able to change the coupon data. Add this code in your child theme functions.php:
```
function mytheme_bookacti_refund_coupon_data( $data, $user_data, $item ) {
	$data[ 'coupon' ][ 'type' ] = 'smart_coupon';
	$data[ 'coupon' ][ 'usage_limit' ] = '';
	return $data;
}
add_filter( 'bookacti_refund_coupon_data', 'mytheme_bookacti_refund_coupon_data', 10, 3 );
```

Let me know if it works, or if you need something else,

Regards,
Yoan Cutillas

**Comment by blackhatwarrior** [comment]
That was the only change needed. It seems to be working. Thanks!

**Comment by bookingactivities** [comment]
Great! Thank you for the feedback!

**Comment by blackhatwarrior** [comment]
Hi, Is there any update on inappropriate "Refunded" label?

**Comment by bookingactivities** [comment]
Hello,

I couldn't change it quickly since it is actually not only a matter of display. It will be part of the next major release (1.6), coming end of next month.

Regards,
Yoan Cutillas
