### ISSUE TITLE
WC Product: Activity Duplicate Display on Calendar

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#204]
Hi,
I am facing a problem, the WC product page shows the activity duplicated twice next to each other. If I click on one both are selected. Can you help? 
[https://imgur.com/a/gTf6isE](https://imgur.com/a/gTf6isE)
https://www.capitano.om/discover/tours/best-muscat-dolphins-watching-tour/

**Comment by yabdali** [comment]
Refreshed the page and its working as intended now..

**Comment by yoancutillas** [comment]
Hello, can you send me an export of your database at contact@booking-activities.fr?

If you don't want to send me the whole database export, I need more precisely
- an export of the tables starting with `wp_bookacti_` 
- an export of the rows starting with `bookacti_` in the `wp_options` table

**Comment by yabdali** [comment]
> * export of the rows starting with `bookacti_` in the `wp_options` table
Hi, Sorry for the delay, had to deal with some technical issues with Mariadb export. Attached are the files. Thanks

[wp_bookacti_tables_dump.txt](https://github.com/user-attachments/files/15934387/wp_bookacti_tables_dump.txt)
[bookacti_options.txt](https://github.com/user-attachments/files/15934388/bookacti_options.txt)

**Comment by yabdali** [comment]
Example of the issue can be found here
[https://www.capitano.om/discover/tours/best-muscat-dolphins-watching-tour/](https://www.capitano.om/discover/tours/best-muscat-dolphins-watching-tour/)

**Comment by yoancutillas** [comment]
Thank you for the export files, I could reproduce the bug and fix it, the fix will be included in the next version.

To temporarily fix the issue:
- Go to Booking Activities > Booking forms > your form > Calendar settings > Availability tab
- Empty the "Opening" option, _**or**_ Turn ON the "Display past events" option
