### ISSUE TITLE
A fatal error occurred. Please try to refresh the page. 

### ISSUE THREAD

**Issue by ferrytcb** [bookingactivities/booking-activities#206]
Hi,

I've installed the plugin and I get error messages on the menu item Calendar Editor...
See attached screenshots.
Adding a calendar doesn't work.

![Screenshot 2024-06-24 161156](https://github.com/bookingactivities/booking-activities/assets/25513569/ebeda33c-b9dd-4fa3-9555-61abd4ea0a5a)
![Screenshot 2024-06-24 161204](https://github.com/bookingactivities/booking-activities/assets/25513569/7fcf4832-9756-4447-a9f5-dd52ab7f9f9d)

**Comment by yoancutillas** [comment]
Hello, this is probably due to a javascript conflict with another plugin or theme, can you follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/
