### ISSUE TITLE
Ralentissement sur thème THEGEM et votre extension de réservation

### ISSUE THREAD

**Issue by audace159** [bookingactivities/booking-activities#208]
Bonjour, 
Nous essayons votre extension de réservation, et celle-ci ralentit fortement notre site de plus de 20 secondes à chaque ouverture. Nous avons contacté le fabricant du thème THEGEM et celui-ci nous indique une incompatibilité entre les méga menu du thème et votre extension. Et c'est vrai que dès que l'on désactive votre extension, le site revient à la normale. Pourriez-vous nous aider sur ce point? Je peux volontiers vous envoyer des codes SFTP vers notre serveur d'essai.

Avec mes meilleures salutations

**Comment by yoancutillas** [comment]
Bonjour,

Vous pouvez confirmer que le problème vient d'un conflit avec votre thème en suivant les instructions sous "Booking Activities ne fonctionne pas comme il le devrait" sur cette page : https://booking-activities.fr/fr/documentation/faq/

Si le problème vient bien d'un conflit avec votre thème, il vous faudra malheureusement choisir entre Booking Activities et votre thème.

Si vous le souhaitez, vous pouvez m'envoyer une copie du thème par email à contact@booking-activities.fr (via google drive ou wetransfer par exemple, mais pas en pièce jointe elle serait bloquée) afin que je vérifie de mon côté si le problème se produit.

____

Si cela peut vous aider, 
- il y a une discussion et une vidéo à propos des performance ici : https://github.com/bookingactivities/booking-activities/issues/110#issuecomment-916806505

Voici des solutions que j'ai mis en place sur mes sites et qui ont améliorées leurs performances :
- l'hébergeur Siteground (évitez vraiment OVH, de même, je ne recommande pas Gandi) 
- le plugin Siteground Optimizer avec "Dynamic Caching" et "Memcached" activés,
- le plugin Wordfence avec son pare-feu activé (il améliore la sécurité, mais aussi les performances, en bloquant les robots à l'entrée du site)

Bien sûr, si la source du problème est un conflit avec votre thème, cela ne résoudra pas le problème.
