### ISSUE TITLE
Send attendees list to administrator on day of event

### ISSUE THREAD

**Issue by darrski** [bookingactivities/booking-activities#21]
We have recurring events that customers can sign up for time slots. It would be super nice if the system could compile the list of attendees for a given day and deliver it via email to the administrator. I looked through your Notifications Pack add-on and I don't believe this feature is included.

Regardless, I was using another plugin before this one and this one has been tremendously easier to setup and manage. Bravo!

**Comment by bookingactivities** [comment]
Hello,

Thank you very much!

Indeed, this feature doesn't exists yet, thank you for your request! I add it to the Notification Pack add-on development schedule.

Regards,
Yoan Cutillas

**Comment by darrski** [comment]
Fantastic!

I'll keep an eye out for it.

Thanks,

Alek

**Comment by bookingactivities** [comment]
Hello Alek,

Thank you,
The development priority increase with the number of requests, and with time. There are two requests for this feature for now, so this feature may not be released this year though.

I send a newsletter with a description of the new features when they are released, you can [subscribe on booking-activities.fr](https://booking-activities.fr/en/#mc-embedded-subscribe-form).

Regards,
Yoan Cutillas
