### ISSUE TITLE
SEO and Accessibility: Calendar Date Range in H2

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#211]
Hi,
The calendar dates range header on the product page is rendered as H2.  This is causing some issues as it interferes with the rest of the page headings if there's an H3 between the calendar heading and the Product title. Also, the H2 is not descriptive since it only contains the date range.  Would it be possible to change this by either giving some options like:

1. Option to disable the H2 for the date range
2. Provide an option to input a descriptive name (text) inside the <form> html element tag as H2 custom heading
3. (optional) Provide some semantic HTML tags like the example shared below (at least <section> for the calendar itself

I appreciate your continuous support and efforts, thanks...

`<h2 class="fc-toolbar-title" id="fc-dom-1">Oct 22 – 26, 2024</h2>`

![image](https://github.com/user-attachments/assets/e7d23f0a-fef3-42a7-9d07-428542eaf2cd)

```html
<main>
  <header>
    <h1>Event Calendar</h1>
    <nav>
      <button aria-label="Previous month">←</button>
      <button aria-label="Next month">→</button>
    </nav>
  </header>
  
  <section role="grid" aria-label="Calendar">
    <div role="row">
      <div role="gridcell">
        <time datetime="2023-10-01">1</time>
        <article>
          <h3>Event Title</h3>
          <p>Event Description</p>
        </article>
      </div>
      <!-- More gridcells for other days -->
    </div>
    <!-- More rows for other weeks -->
  </section>
</main>
```

**Comment by yoancutillas** [comment]
You are welcome :) Thank you for helping making Booking Activities better.

I would gladly change this h2, but It looks like the h2 is hardcoded in the FullCalendar calendar's structure ([here](https://github.com/fullcalendar/fullcalendar/blob/v6.1.15/packages/core/src/ToolbarSection.tsx#L38)).

It may be worth creating a ticket on FullCalendar's github page, maybe to suggest replacing the "h2" with a "strong" (?) 
I usually do it myself, but I am not qualified enough in SEO to determined to what extent this can be a problem, I would not be able to explain / stand up for this request to the author.

**Comment by yabdali** [comment]
Sorry, got busy with other stuff. Checked your link. I think its going a long shot to get FC github ticket to fix this, ultimately it should be done so I will need to make some clear description. Meanwhile, I think it can be done using a javascript to replace the H2 tag with H3. Tried doing it with assistance of ChatGPT but its not working, I presume the timing of the script might conflict with the reload event/AJAX call.  Not sure if you can check and identify what could be the issue! I found a partial fix, to modify settings>messages>Instructions displayed before the calendar, added an H2 tag but this requires us to replace the H2 tag of the date range, I tend to agree with you about using strong tag. I see FC still using tables for layout which is an old school approach in the era of response designs....

Thanks alot...

```php
<?php
function change_h2_to_h3() {
    ?>
    <script type="text/javascript">
        jQuery(window).on('load', function($) {
            console.log("Script started"); // Log to check script execution
            $('h2.fc-toolbar-title').each(function() {
                console.log("Found h2:", this); // Log each found h2 element
                var newElement = $('<h3></h3>').html($(this).html());
                $(this).replaceWith(newElement);
            });
            console.log("Script finished"); // Log to confirm completion
        });
    </script>
    <?php
}
add_action('wp_footer', 'change_h2_to_h3');
?>
``` 
![image](https://github.com/user-attachments/assets/421e177b-1cc0-4d70-95da-a15886fd8687)

**Comment by yoancutillas** [comment]
Hi, yes, you would probably need to replace it everytime the view changes / is reloaded, maybe on the [bookacti_calendar_view_render](https://github.com/bookingactivities/booking-activities/blob/1.16.21/js/booking-method-calendar.js#L459) hook.

**Comment by yabdali** [comment]
> Hi, yes, you would probably need to replace it everytime the view changes / is reloaded, maybe on the [bookacti_calendar_view_render](https://github.com/bookingactivities/booking-activities/blob/1.16.21/js/booking-method-calendar.js#L459) hook.

I got it partially working. It only works on simple products, doesn't work with variations. Can you check what I am missing using your demo calendars if you don't mind?

```php
function inject_custom_jquery_script_for_booking_system() {
    ?>
    <script type="text/javascript">
    jQuery(document).ready(function($) {
        console.log('Custom script for modifying fc-toolbar-title is loaded.');

        // Listen for custom event 'bookacti_booking_system_reloaded'
        $('body').on('bookacti_booking_system_reloaded', function() {
            console.log('Calendar content has loaded.');

            // Replace <h2 class="fc-toolbar-title" id="..."> with <strong> tag, retaining the ID
            $('h2.fc-toolbar-title').each(function() {
                var newElement = $('<strong>', {
                    class: 'fc-toolbar-title', // Keep the class
                    id: $(this).attr('id'),     // Keep the existing ID
                    html: $(this).html()        // Keep the inner HTML content
                });
                $(this).replaceWith(newElement);
            });
        });
    });
    </script>
    <?php
}
add_action('wp_footer', 'inject_custom_jquery_script_for_booking_system');
```

**Comment by yabdali** [comment]
I was able to get the issue fixed using the following JS. Do you have any concerns or inputs?

```php
function inject_custom_jquery_script_for_variable_products_with_observer() {
    ?>
    <script type="text/javascript">
    jQuery(document).ready(function($) {
        console.log('Custom script for observing fc-toolbar-title is loaded.');

        function replaceFcToolbarTitle() {
            $('h2.fc-toolbar-title').each(function() {
                var newElement = $('<strong>', {
                    class: 'fc-toolbar-title',
                    id: $(this).attr('id'),
                    html: $(this).html()
                });
                $(this).replaceWith(newElement);
            });
        }

        // Initial replacement on page load
        replaceFcToolbarTitle();

        // Set up a MutationObserver to detect DOM changes
        const observer = new MutationObserver(function(mutations) {
            mutations.forEach(function(mutation) {
                if (mutation.type === 'childList' || mutation.type === 'subtree') {
                    replaceFcToolbarTitle();
                }
            });
        });

        // Observe the body or a specific container with frequent AJAX reloads
        observer.observe(document.body, {
            childList: true,
            subtree: true
        });

        // Clean up the observer when leaving the page (if needed)
        $(window).on('unload', function() {
            observer.disconnect();
        });
    });
    </script>
    <?php
}
add_action('wp_footer', 'inject_custom_jquery_script_for_variable_products_with_observer');

```

**Comment by yoancutillas** [comment]
Hello, sorry I cannot provide support for custom code. The most important is that you succeed to achieve what you wanted :) Thank you for sharing you code for others.

In any case, it would be a temporary workaround, it would be nice to open a ticket on FullCalendar's github for a built-in solution. They can fix it very quickly, the hardest part is to explain why it is an issue and why they should fix it now, that's why I don't open the ticket myself.

**Comment by yoancutillas** [comment]
@yabdali Hi, I have search the current issues at fullcalendar's github, it appears that they do have
- an issue opened to allow to replace the `h2` tag with another `h*` (https://github.com/fullcalendar/fullcalendar/issues/6972)
- an issue opened to actually use a `h*` tag instead of a `div` for the month headings (https://github.com/fullcalendar/fullcalendar/issues/7537)

So it appears that using a `h*` tag rather than a `strong` or `div` tag is intentional, but the `h2` doesn't fit anywhere, that's why we should be able to replace it with another number depending on the page where the calendar is displayed. 

I will upvote the feature request on fuullcalendar's github, and close the ticket here because, in any case, this would be up to custom code because the `h*` tag to use depends on the page where the calendar is displayed.
