### ISSUE TITLE
integration woocommerce

### ISSUE THREAD

**Issue by iwonabp** [bookingactivities/booking-activities#22]
Does integration with woocommerce require a premium plan?
there is no action option in the product edition
![scrn](https://user-images.githubusercontent.com/45593108/49438496-c96cd580-f7be-11e8-9af3-f3f825caee35.png)

I installed a new wordpress on the new website and...
and in the new wordpress, on the new website after installing the plugins, there is no action option.
the "action" is visible when the page is loaded.
it's gone after loading.
how to solve this problem?

thank you in advance for your answer.

**Comment by bookingactivities** [comment]
Hello,

You just need to check the "Activity" checkbox to make the "Activity" tab appear.
On your screenshot it is probably the "Czynność" checkbox. Is the translation incorrect ?

Regards,
Yoan Cutillas

**Comment by iwonabp** [comment]
thank you
I missed the option

**Comment by bookingactivities** [comment]
You are welcome :)

Regards,
Yoan Cutillas
