### ISSUE TITLE
Répétition événement

### ISSUE THREAD

**Issue by Krystelrolland** [bookingactivities/booking-activities#23]
Bonjour,
Votre plugin de base est présenté comme pouvant répéter un événement et exclure des dates. Seulement, l'onglet répétition n’apparaît pas. Je l'avais testé la semaine dernière et ce dernier y était bien. Mais là impossible de configurer une répétition d'événements. Merci de m'indiquer comment résoudre le problème. Cordialement

**Comment by bookingactivities** [comment]
Bonjour,

C'est peut-être dû à un conflit avec un autre plugin ou un soucis de compatibilité.
Qu'avez-vous changer depuis la semaine dernière ?
Avez-vous installé des plugins ? Avez-vous faits des mises à jour ? Avez-vous changé de thème ?

Booking Activities ne supporte pas encore WordPress 5.0, avez-vous fait la mise à jour ?

Essayez de désactivez tous vos plugins. Puis vérifiez si l'onglet répétition apparaît à nouveau.
S'il apparaît à nouveau, réactiver-les un par un en testant entre chaque activation. Si l'onglet disparaît après avoir activer un certain plugin, vous saurez que le conflit provient de celui-ci.

Cordialement,
Yoan Cutillas

**Comment by Krystelrolland** [comment]
Bonjour,
tout d'abord merci pour votre réponse rapide. Je n'ai fait aucune mise à
jour depuis. Je vais tester et revient vers vous.
Cordialement

**Comment by Krystelrolland** [comment]
je viens de tester sur un site d'essais et le bouton est réapparu ! Merci

Le lun. 10 déc. 2018 à 11:13, Krystel Rolland <bolcanstern@gmail.com> a
écrit :
