### ISSUE TITLE
Impossible d'activer le Display Pack

### ISSUE THREAD

**Issue by woolityourslef** [bookingactivities/booking-activities#24]
Bonjour
Ayant acheté récemment le display pack, je n'arrive pas à l'activer (j'ai pourtant a priori tout fait côté Booking Activities) ; en suivant vos tutos, mon soucis est simple, je ne trouve pas d'onglet permettant de saisir la licence dans mon paneau d'admin WP .. 
Je suis allé dans Booking Activities > Règlages , mais pas de champ ou onglet "licence"

Merci de m'aider à résoudre cela

**Comment by bookingactivities** [comment]
Bonjour,

Merci beaucoup pour votre intérêt envers Booking Activities et pour votre achat.

Vous devez installer et activer le plugin Licenses and Updates conjointement à Display Pack et Booking Activities. Il est fourni avec votre achat dans l'e-mail de confirmation de commande, ou sur votre espace [Mon Compte](https://booking-activities.fr/fr/mon-compte/). Vous pouvez également le [télécharger ici](http://booking-activities.fr/wp-content/uploads/downloads/public/ba-licenses-and-updates.zip).

Dîtes moi si cela fonctionne,

Cordialement,
Yoan Cutillas

**Comment by woolityourslef** [comment]
Ok parfait, il est bien actif désormais
Dernière question, comment afficher une liste des événement programmés (j'ai un planning actif, avec des événements, et qui dans les vues, a une vue liste enregistrée, mais je n'arrive pas à l'utiliser sous cette forme sur mon site)

**Comment by bookingactivities** [comment]
Les options que vous paramétrez dans l'éditeur de planning sont utilisées par défaut lorsque vous créez un formulaire. Après cela, chaque formulaire possède ses propres paramètres.

- Allez dans l'éditeur de formulaire de réservation
- Cliquez sur la molette de réglages du champ "Calendrier"
- Allez dans l'onglet "Calendrier"
- Cochez les vues en liste désirée dans l'encart "Vues". Vous pouvez aussi les paramétrer en tant que vue par défaut en fonction de la taille de votre calendrier.

![champ calendrier - vue en liste](https://user-images.githubusercontent.com/25784216/49746328-3e4d7d00-fca1-11e8-9b7e-574a95a52554.PNG)

Vous pouvez aussi cliquer sur le bouton "Réinitialiser" de cette boîte de dialogue pour appliquer les paramètres que vous avez entré dans votre éditeur de planning.
