### ISSUE TITLE
personnaliser les actions au clic sur un événement dans le calendrier

### ISSUE THREAD

**Issue by woolityourslef** [bookingactivities/booking-activities#25]
Bonjour

J'uitlise le Booking Activities dans le cadre d'un ecommerce ; et si tout ok qd je le lie à une fiche produit, j'aimerai pouvoir diffuser un calendrier de tous les événements (mélangés) et que qd on clique sur une activité sur le planning, cela déclenche une URL personnalisé (et non la sélection de l'événement pour demande de réservation) est-ce possible ? si oui, comment ?
Merci d'avance

**Comment by bookingactivities** [comment]
Bonjour,

C'est en cours de développement, la version paraîtra début 2019.
D'ailleurs cela fonctionne déjà sur la version de développement, si vous souhaitez essayer:

https://github.com/bookingactivities/booking-activities/archive/1.7.0-alpha-1.zip

Pour paramétrer les redirections :
- Allez dans l'éditeur du formulaire désiré
- Allez dans les paramètres du champs "Calendrier"
- Onglet "Actions"
- Ici sélectionnez si vous souhaitez redirigez vers une page produit WooCommerce ou vers une autre URL
- Choisissez quand vous souhaitez effectuer la redirection : quand le client clique sur l'évènement, ou quand il valide le formulaire
- Remplissez les URLs / produits liés à chaque activité et chaque catégorie de groupes affichées sur ce calendrier
- Validez la boîte de dialogue

![form action - redirect](https://user-images.githubusercontent.com/25784216/49938798-3b3dd100-fedb-11e8-8888-10d0ef43815f.PNG)

Votre formulaire de réservation redirigera désormais vos clients vers la page souhaitée lorsqu'ils cliqueront sur l'évènement, ou bien lorsqu'ils valideront le formulaire.
Si un autre formulaire de réservation se trouve sur la page de destination, l'évènement désiré sera présélectionné.

Attention toutefois si vous utilisez cette version et que d'autre mise à jour paraissent en 1.6.x, vous ne pourrez pas les faire, vous devrez patientez jusqu'à la 1.7.0.

Cordialement,
Yoan Cutillas

**Comment by bookingactivities** [comment]
La version 1.7 est désormais disponible : 
[https://booking-activities.fr/fr/blog/booking-activities-1-7-actions-formulaire-et-outils-systeme/](https://booking-activities.fr/fr/blog/booking-activities-1-7-actions-formulaire-et-outils-systeme/)
