### ISSUE TITLE
Unable to change Cancel bookings button label

### ISSUE THREAD

**Issue by blackhatwarrior** [bookingactivities/booking-activities#26]
The setting to change "Cancel bookings button label" on Messages page is changing label of the wrong button.

**Comment by blackhatwarrior** [comment]
Temporary Solution:
`add_filter( 'bookacti_translation_array', 'bookacti_custom_translation_array', 20, 1 );
function bookacti_custom_translation_array( $translation_array ) {
    $translation_array[ 'dialog_button_cancel_booking' ] = esc_html__( 'Some Text', BOOKACTI_PLUGIN_NAME );
    return $translation_array;
}`

**Comment by bookingactivities** [comment]
Thank you for the report!
It will be fixed in the next version.

Regards,
Yoan Cutillas
