### ISSUE TITLE
Erreur lors du chargement des événements : "AJAX Une erreur est survenue lors de l’affichage des évènements"

### ISSUE THREAD

**Issue by Shandraz** [bookingactivities/booking-activities#27]
Bonjour,

Je suis face à un problème récemment, il arrive que lorsque je me rend dans la section "Editeur de planning", les événements tentent de se charger (animation qui tourne) puis une ou deux secondes après, une pop up m'avertit d'une erreur : "AJAX Une erreur est survenue lors de l’affichage des évènements".
Ce qui est étrange c'est que ça arrive environ 1 fois sur 2, si je recharge ma page, ça peut marcher ou pas, toujours une fois sur deux, donc actuellement je rafraichi à chaque fois que j'ai l'erreur mais ça devient très lourd... Parfois je n'ai pas le message d'erreur, mais les événements ne sont pas chargés (c'est encore pire puisque j'ai peur de tout avoir perdu quand ça arrive)

Je vous ai mis un screenshot au cas où je n'ai pas été clair ^^

![erreurajax](https://user-images.githubusercontent.com/42546480/52298819-2c781580-2984-11e9-9f12-0c3d82051014.JPG)

Bonne journée !

**Comment by bookingactivities** [comment]
Bonjour,

1. Assurez-vous d'avoir tous vos plugins à jour.
2. Une AJAX error est souvent provoquée par une erreur PHP qui intervient lors de la requête AJAX.
Vérifiez votre fichier de log d'erreurs PHP: regardez si une erreur PHP apparaît lorsque vous avez cette erreur. Si tel est le cas, envoyez moi cette erreur.
3. Vous pouvez également vérifier si un plugin tiers n'interfère pas dans le bon fonctionnement de Booking Activities en suivant les instructions sous "Booking Activities ne fonctionne pas comme il le devrait" ici : [FAQ](https://booking-activities.fr/fr/documentation/faq/)

Cordialement,
Yoan Cutillas
