### ISSUE TITLE
Affichage agenda mois

### ISSUE THREAD

**Issue by woolityourslef** [bookingactivities/booking-activities#28]
Bonjour
j'utilise WPBookingActivities pour un agenda d'ateliers, et j'aimerai que l'agenda accosié aux fiches produits s'affiche sous forme d'agenda mensuel .. hors (malgré le display pack) je ne vois pas d'options autres que agenda jour ou semaine .. y'a-t-il une solution ?
Merci d'avance !

**Comment by bookingactivities** [comment]
Bonjour,

Oui, vous pouvez utilisez l'API de Booking Activities et la [documentation de FullCalendar](https://fullcalendar.io/docs#toc) pour modifier le comportement par défaut via le code.

Par défaut, Booking Activities affiche la vue "Semaine".  Si le calendrier est moins large que le seuil indiqué dans les paramètres (Booking Activities > Réglages > Général > Option "Seuil de la vue responsive des calendriers"), il affichera alors la vue "Jour".

Pour les non-développeurs, le module Display Pack permet effectivement de paramétrer n'importe quelle vue par défaut, en fonction de la largeur du calendrier (plusieurs seuils possibles), et différemment pour chaque formulaire de réservation si nécessaire.

Cordialement,
Yoan Cutillas
