### ISSUE TITLE
Booking weddings

### ISSUE THREAD

**Issue by graeward** [bookingactivities/booking-activities#29]
I like this app very much but I need help. We are a wedding business. A user can book a day wedding or an evening wedding. A day wedding needs an hour and can start anytime between 11 am and 3 pm (preferably on the hour). An evening wedding can start anywhere between 6 pm and 9 pm. There are different prices for day and evening weddings. However, there can only ever be one wedding in any one day. Can you help with this?

**Comment by yoancutillas** [comment]
Hello,

Ok, I can see three problems:
1. You want your customers to choose the starting time
2. There are different prices for day and evening weddings
3. There can only ever be one wedding in any one day


**1. You want your customers to choose the starting time**
With Booking Activities, you can only set events with a predefined starting time.
But you can have two events:
- Day wedding from 11 am to _any time you want_
- Evening wedding from 6 pm to _any time you want_
And then ask you customers when they want you to come exactly.

You can add a "Wedding start" field (for example) thanks to the [Advanced Forms](https://booking-activities.fr/en/downloads/advanced-forms/) add-on ([demo here](http://demo.booking-activities.fr/en/shop/advanced-booking-form/)). It can be a dropdown: 11am, 12am, 1pm, 2pm or 3pm, or a time field with a min and a max value for example.


**2. There are different prices for day and evening weddings**
If you are using WooCommerce, you can create a Variable Product. Each variation can have a different price, and can be bound to a different booking form ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/display-calendars-on-product-page/)). So you can have one booking form for Day weddings, and one booking form for Evening weddings ([demo here](http://demo.booking-activities.fr/en/shop/variable-activity/))

Else, if you want both of them on the same calendar, you can use [Prices and Credits](https://booking-activities.fr/en/downloads/prices-and-credits/) add-on. It will let you set a different price for each activity / event ([demo here](http://demo.booking-activities.fr/en/shop/sales-promo-special-offers/)).


**3. There can only ever be one wedding in any one day**
With Booking Activities, you cannot say "if one event is booked, then another one must become unavailable" unfortunatly.
However, I have created a small script to do that. You can add it to your child theme functions.php file.
Then, you will need to create groups of events that cannot be booked simultaneously in a specific category.
Put the category ID at the specified place in the code (line 12).
Now, when a customer books an event, the other events of the group are automatically fully booked to make them unavailable. (Ignore the bookings made by the user called "system" in the booking list).

I have attached screenshots of how to get the category ID (with the browser console) and two examples of groups of events that take place at the same time.
[book all ressource events.txt](https://github.com/bookingactivities/booking-activities/files/3359351/book.all.ressource.events.txt)
![group1](https://user-images.githubusercontent.com/9415030/60668400-2707f400-9e6c-11e9-955b-dcbe686936e8.PNG)
![group2](https://user-images.githubusercontent.com/9415030/60668402-28392100-9e6c-11e9-8075-825d29e6aa8c.PNG)
![category id](https://user-images.githubusercontent.com/9415030/60668403-2a02e480-9e6c-11e9-8235-ae9dcaea0db9.png)

Regards,
Yoan Cutillas
