### ISSUE TITLE
Time format Missing

### ISSUE THREAD

**Issue by unomobil** [bookingactivities/booking-activities#3]
hi , i have notice that the option to change the : Formatting Date and Time

it only possible to change the: Daynumber, Month, year and start clock.
BUT not the END clock ....

so at the moment its looking like: 4 jan 2018 23.55 -> 11.00am
so an option to change the last clock is needed :-) 

ALSO 
when seeing the full calendar, im not able to select the need event and get at ticket..... I can mark it, but nothing more.....

thank

**Comment by bookingactivities** [comment]
Hello,

To format the event end time, simply use the "Time format" field below the "date format" in Booking Activites 1.3+ settings, "Messages" tab.
![time format](https://user-images.githubusercontent.com/25784216/35715086-04b77728-0803-11e8-80df-ebf2dfb83397.PNG)

For your second issue, can you give me these information:
- Do you mean that when you click an event, and then click on the "Book" button, nothing happen?
- Can you please send me a screenshot to illustrate what is happening?
- Are you displaying this calendar with WooCommerce?
- Else, what shortcode are you using?

Regards,

**Comment by unomobil** [comment]
Hi Thanks for answer.

Ising wordpress :
I have used the custom time option , 
The time i showet right when selecting an event, and showing the time and date of it. 
But in the basket and recep is showing the end time as 12 hours (11.30pm) in-sted of 23.30. 

Michael 
Sendt fra min iPhone

**Comment by bookingactivities** [comment]
Indeed, this is a bug. It will be fixed in the next release, thank you very much for reporting!

Do you still need help with your second issue?

Regards,

**Comment by unomobil** [comment]
Perfect :).  Is there a temporary Way to solv it ? Ihave been looking in the file But was not able tofinde the specific time code :).

**Comment by bookingactivities** [comment]
Sure, in booking-activities/functions/functions-booking-system.php line 959, replace
`$event_end = date_i18n( __( 'h:i a', BOOKACTI_PLUGIN_NAME ), strtotime( $event[ 'end' ] ) );`
by
`$event_end = date_i18n( bookacti_get_message( 'time_format' ), strtotime( $event[ 'end' ] ) );`

Let me know if it works after you change this.

**Comment by unomobil** [comment]
I Think it have ruin my time and date in woocommerce, now all my orders is showing as weird word and special charavter ... 


Michael 

Sendt fra min iPhone

**Comment by bookingactivities** [comment]
Hello,

What format have you put in the Time Format field? Is it conform to [WP i18n date and time formatting](https://codex.wordpress.org/Formatting_Date_and_Time)?

Can you also confirm that if you revert this change, the problem doesn't occur anymore?

Finally, can you send me a screenshot of that weird words?

Regards,

**Comment by bookingactivities** [comment]
Hello,

Did you solve your problem or do you need more help?

Regards,

**Comment by bookingactivities** [comment]
Hello,

I will close thsi topic now, if you have another question, feel free to open a new one.

Regards,
