### ISSUE TITLE
Bulk Action is not available in Bookings view

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#30]
In the bookings view (wordpress administration), it is not possible to select multiple bookings to apply an action except 'Export'. 

It would be nice to select several bookings and change their state together : set to Pending, set to Booked, ...

**Comment by yoancutillas** [comment]
Indeed the bulk actions are not implemented yet unfortunately,
I have had similar requests already, I add your vote, thank you very much!

**Comment by pikurasa** [comment]
I would very much benefit from this feature, too.

**Comment by opcoach** [comment]
I guess my cote has been taken into account too ? ;)

**Comment by yoancutillas** [comment]
Of course :)
The development schedule is getting quite busy, but it doesn't mean that it won't be developed, just a matter of time and priority.

**Comment by urbpdx** [comment]
Would love to add my vote here as well. This has been challenging in the time of COVID with a lot of cancelled and rescheduled events.

**Comment by yoancutillas** [comment]
I have added you vote, thank you.
The next version (1.9, January 2021) will let you cancel all the bookings of an event when you delete it from the Calendar editor.
I am aware that it is only a partial solution though, it doesn't replace this feature request.

**Comment by rayedgar** [comment]
Yes my vote as well!

**Comment by yoancutillas** [comment]
Released in 1.16
