### ISSUE TITLE
In a booking form there should be a 'no filter' option

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#33]
When we create a new activity for a calendar, we must not forget to add it manually in the filter of the correponding form... 

This is complicated, especially when the calendar form displays all the activities... 

It would be nice to add a filter selector in the calendar parameter in the form, in the 'Filters' tab, in the 'Event Sources' group. For instance : Activity : All activities or if we deselect we get the existing selection box... 

![Capture d’écran 2019-09-25 à 00 00 03](https://user-images.githubusercontent.com/1716878/65553698-bb439d80-df27-11e9-8f82-3c3fd6971bbd.png)

**Comment by yoancutillas** [comment]
I agree, I have had other feedback in regards to this, this feature is planned for the next major version 1.8, hopefully before the end of the year, or so.

**Comment by opcoach** [comment]
Hi Yoan, 
I have seen the 'Tous' in the menu. 
For me this is done, I close the issue...
