### ISSUE TITLE
Grouped Events Alone not working

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#35]
I am on version Version 1.7.11 with many of the paid plugins

When I click on "Book grouped events Alone" and click "save", it does not seem to save the state and therefore cannot publish anything like what you have on https://demo.booking-activities.fr/en/shop/groups-of-events/

I have my wordpress as a multisite with subdomains as the child site (currently only one subdomain, but plan to branch out in future). Could it be that there is a bug where this is not being saved to the database (for multipress)?

This does not work for me:
![Screenshot at 2019-11-13 12:15:29 Book grouped events alone not working](https://user-images.githubusercontent.com/13454579/68787624-c8346180-0639-11ea-9ec9-7216f32da245.png)

**Comment by yoancutillas** [comment]
Hello Devin,

I don't know if this is due to the multisite feature (not supported), or a plugin conflict.

Can you try to follow the steps below "Booking Activities doesn’t work as it should" here:
https://booking-activities.fr/en/documentation/faq
and give me the results?

Regards,
Yoan

**Comment by pikurasa** [comment]
> https://booking-activities.fr/en/documentation/faq

Due to the structure of my website, this steps would take a long time to do and would be disruptive. I would probably need to duplicate the data somewhere else in order to avoid a major disruption to visitors of my site.

Is there a different way to report the bugs, like sending logs? That would be less disruptive.

**Comment by pikurasa** [comment]
I did the following and now it works (have no idea which of these caused the issue):

* Updated to latest WP
* Updated all the non-core (licensed updates) BA plugins (sorry, did not see the non-core were not up-to-date)
* Completely deleted WP-ERP (https://github.com/wp-erp/wp-erp) as I found that plugin (and its so-called "pro" plugins to be [completely useless](https://wordpress.org/support/topic/not-ready-for-prime-time-24/) <-- If there was a plugin conflict, this would be it!
* Updated all my other plugins

...and now, it seems to work!

**Comment by yoancutillas** [comment]
Ok, glad it is working now!
Yes, always check if there are updates for the add-ons before you update Booking Activities, they really relies on each other.
