### ISSUE TITLE
Export all Bookings for a calendar as .ics (or caldav)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#38]
I am not wedded to a particular way of solving this, but it would be nice to "sync" the bookings made to my own personal calendar.

I could imagine a few ways of doing this.
* Along with the Woocommerce email that has the booked event, a link to a .ics file for download.
* Download .ics file directly from bookings page

(Am I correct that .ics can only provide a single booking at a time? Perhaps a .zip can be provided with all events from a group?)

* Some option for caldav sync
* Any other clever solutions?

In the meantime, I manually sync my schedule to other calendars that I view more often than the one in BA. This would just be an added convenience for people in my position where the calendar that people are booking from is basically the same calendar for the person who provides the service (or otherwise needs to be present for the activity).

**Comment by yoancutillas** [comment]
Yes you can do that :)
Follow the steps under [2. Export bookings to iCal and Sync on a calendar app](https://booking-activities.fr/en/docs/user-documentation/advanced-use-of-booking-activities/export-bookings-and-events/#export-customer-bookings-ical)

**Comment by pikurasa** [comment]
> Yes you can do that :)

Awesome -- I will try it.
