### ISSUE TITLE
Repeated Activity: `Monthly/Weekly` On every `x` of the month/week

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#39]
I tried to do this the other day:

Repeated Activity `Monthly` on `1st` `Monday`. I can do the `Monthly` part, but cannot specify the `1st` `Monday` part.

It would be nice to have this feature. (As a possible reference) Event Espresso and Event Manager Pro has this feature.

**Comment by yoancutillas** [comment]
Thank you for your request, 
This feature has already been requested, I add your vote :)

**Comment by yoancutillas** [comment]
Released in Booking Activities 1.11
