### ISSUE TITLE
Changement heure événement dans l'email envoyé au client

### ISSUE THREAD

**Issue by amadeo16** [bookingactivities/booking-activities#41]
Bonjour,
Suite à la mise à jour de WordPress 5.3, lorsque qu'un client réserve un événement par exemple de 20h à 21h, et bien dans l'email qui reçoit l'horaire de l'événement devient de 19h à 20h (extension woocommerce)
C'est comme si, il convertissait à l'heure universelle alors que normalement je suis sur le fuseau horaire de Paris.
Par ailleurs la bonne heure qui est affiché dans les détails de l'événement du site et bien sur dans la base de donnée.
Avez une idée comment je peux faire pour que l'email reçu fait référence au bon horaire réservé ?
Merci pour votre réponse
Amadeo

**Comment by yoancutillas** [comment]
Bonjour Amadeo,

Pouvez-vous me donner les informations suivantes :
1. Quel est le fuseau horaire dans Réglages > Généraux > option "Fuseau horaire" ?
2. Quel est le fuseau horaire dans Booking Activities > Réglages > onglet "Général" > option "Fuseau horaire des plannings" ?
3. Le problème se présente-il dans les emails envoyés par WooCommerce (exemple: confirmation de conmande) ?
4. Le problème se présente-il dans les emails envoyés par Booking Activities (exemple: annulation d'une réservation) ?
5. Le problème se présente-il dans la liste des réservations dans Booking Activities > Réservations ?

Cordialement,
Yoan Cutillas

**Comment by amadeo16** [comment]
Bonjour Yoan,

Merci pour votre réponse, voici les réponses aux questions demandées en gras :

1. Quel est le fuseau horaire dans Réglages > Généraux > option "Fuseau horaire" ?
**Paris**
2. Quel est le fuseau horaire dans Booking Activities > Réglages > onglet "Général" > option "Fuseau horaire des plannings" ?
**Paris**
3. Le problème se présente-il dans les emails envoyés par WooCommerce (exemple: confirmation de conmande) ?
**Oui**
4. Le problème se présente-il dans les emails envoyés par Booking Activities (exemple: annulation d'une réservation) ?
**Non, c'est woocommerce qui envoit l'email**
5. Le problème se présente-il dans la liste des réservations dans Booking Activities > Réservations ?
**Non, c'est la bonne heure qui est enregistré dans les réservations booking Activities**

Informations supplémentaires : Le soucis vient d'apparaitre hier matin depuis la mise à jour vers wordpress 5.3.

Merci à vous

Amadeo

**Comment by yoancutillas** [comment]
Je ne reproduis pas le problème de mon côté, pourriez-vous me donner ces renseignements complémentaires : 

1. L'heure s'affiche-t-elle bien dans WooCommerce > Commandes > votre commande > dans la liste des articles ?
Pouvez-vous poster une capture d'écran ici ? (entourez l'heure en rouge)

2. Pouvez-vous poster une capture d'écran ici de l'heure qui s'affiche mal dans l'email de WooCommerce ? (entourez l'heure incorrecte en rouge)

3. Pouvez-vous me donner un lien vers la page produit en question ?

**Comment by amadeo16** [comment]
Merci pour votre réponse, voici les informations demandées : 

1. L'heure s'affiche-t-elle bien dans WooCommerce > Commandes > votre commande > dans la liste des articles ? **Oui elle s'affiche bien**
Pouvez-vous poster une capture d'écran ici ? (entourez l'heure en rouge)
![1 - commande woocommerce](https://user-images.githubusercontent.com/51031080/70548135-571d9680-1b72-11ea-8e08-12c193fcc3e0.png)


2. Pouvez-vous poster une capture d'écran ici de l'heure qui s'affiche mal dans l'email de WooCommerce ? (entourez l'heure incorrecte en rouge)
![2 - email reçu woocommerce](https://user-images.githubusercontent.com/51031080/70548167-643a8580-1b72-11ea-8bed-18563dee88ed.png)

3. Pouvez-vous me donner un lien vers la page produit en question ?
Voici le lien vers le produit lié aux captures d'écran : 
[](https://www.labdcomedie.com/spectacle/cheri-on-se-dit-tout/)

**L'erreur est présente avec tous les autres produits.**

Bien à vous

Amadeo

**Comment by yoancutillas** [comment]
Je suis désolé je ne parviens pas à reproduire ce bug, je vous propose un dernier test :

- Allez dans Booking Activities > Réglages > onglet "Messages"
- Notez les valeurs des trois premiers champs afin de me les transmettre plus tard : Format de date complet, Format de date court, Format des heures
- Videz ensuite complètement ces trois champs
- Enregistrez les modifications
- Mettez à présent ces valeurs : 
     - Format de date complet: `l j F Y H:i`
     - Format de date court: `jS M - H:i`
     - Format des heures: `H:i`
- Enregistrez les modifications

Si cela fonctionne suite à ce changement, pouvez-vous m'envoyer les valeurs initiales des champs?

Sinon, j'aurai besoin d'un accès administrateur afin d'effectuer des tests directement sur votre site. Si vous êtes d'accord, vous pouvez m'envoyer les informations de connexion à contact@booking-activities.fr.

**Comment by yoancutillas** [comment]
Corrigé dans la version 1.7.13
