### ISSUE TITLE
Column 'Paid' status in Bookings list

### ISSUE THREAD

**Issue by mindoj1** [bookingactivities/booking-activities#42]
Do I remember correctly there was an column named 'Paid' in the 'Bookings' list? Seems after update to 1.7.13 it disappeared.

**Comment by yoancutillas** [comment]
Hello,

It should still be there:
- Go to Booking Activities > Bookings
- Click on "Screen options" in the top right-hand corner of the page
- Check the "Paid" column and it will appear

Regards,
Yoan Cutillas

**Comment by mindoj1** [comment]
Thanks a lot, you are right of course! I somehow missed that option.
