### ISSUE TITLE
Should not limit the height on activities area

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#44]
The layout for calendar edition should be reconsidered. Both group and activities should have handles to set the height. The current global handle does not resize both areas correctly and the activities area has a limited height which is not really handy. 

<img width="506" alt="CalendarActivitiesLimitedHeight" src="https://user-images.githubusercontent.com/1716878/70951554-fefbfe00-2063-11ea-8133-69fc280ad551.png">

**Comment by yoancutillas** [comment]
Ok thank you for your report,
It will be possible to resize them in the next version (1.7.14), in [compatible browsers](https://developer.mozilla.org/fr/docs/Web/CSS/resize#Compatibilit%C3%A9_des_navigateurs).
