### ISSUE TITLE
Fatal error when updating planning (since new release...)

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#46]
When I try to update a planning I get this error :

Une erreur fatale s’est produite. Veuillez essayer de rafraîchir la page. Si l’erreur persiste, suivez le processus sous « Booking Activities ne fonctionne pas comme il le devrait » ici : FAQ.
Utilisateurs avancés, vous pouvez arrêter le chargement et libérer les champs pour tenter de résoudre votre problème :   + bouton à cliquer pour 

Planning edition is not operational and data are not well displayed after this error...

**Comment by yoancutillas** [comment]
I don't reproduce this issue on my side;

1. Can you:
- Deactivate all your plugins except Booking Activities
- Activate [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/) instead of your theme
- Go to Booking Activities > Calendar editor
- Reproduce the error
- Tell me if the error still occurs

2. If it still occurs:
- Go to Booking Activities > Calendar editor
- Reproduce the error
- [Open your browser console](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers#answer-77337)
- Send me a screenshot of the error diplayed in the console

**Comment by opcoach** [comment]
I don't have twenty seventeen theme anymore... 

May be you could directly connect on my web site (you have an account ? )... 

Try to add a 'meetup soirée' in the 'formation' planning...  You will get the error...

**Comment by yoancutillas** [comment]
Sorry I didn't save the credentials to log in,
Can you install Twenty Seventeen to make both tests first?
I'd rather not step into your website unless I can't help you otherwise.

**Comment by opcoach** [comment]
Ok I will try...

**Comment by opcoach** [comment]
Here is the screenshot of the console error list...  

I had the same error with the twenty seventeen theme... 

I switched back to generate press and here is the console and the error in admin page : 

<img width="1072" alt="Capture d’écran 2020-01-22 à 16 37 56" src="https://user-images.githubusercontent.com/1716878/72908367-acce8c80-3d35-11ea-90a2-a0f905a1cec6.png">

**Comment by opcoach** [comment]
I can give you private access on the web site if you need it

**Comment by yoancutillas** [comment]
Can you confirm that all your plugins except Booking Activities were deactivated too?

It looks like one of your event is corrupted (event.end is null).

Can you 
- Go to phpMyAdmin (from your webhost admin panel)
- Select your database
- Go to the "SQL" tab
- Execute this query : `SELECT * FROM wp_bookacti_events WHERE start IS NULL OR end IS NULL OR start > end OR repeat_from > repeat_to OR ( repeat_freq != 'none' AND ( repeat_from IS NULL OR repeat_to IS NULL ) )`
- Tell me if there is a result
- If not, send me an export of the wp_bookacti_events table (click on the wp_bookacti_events table on the left, and go to the "Export" tab)

**Comment by opcoach** [comment]
I forgot to deactivate all the plugins :) Anyway, when they are deactivated, I've got the same error... 

So here is the export of the event table... I exported in csv and sql in case.... Both files are in zip, because sql and csv are not supported here....
[inter_bookacti_events.zip](https://github.com/bookingactivities/booking-activities/files/4098923/inter_bookacti_events.zip)

**Comment by yoancutillas** [comment]
I can see no problem in that table. I will need to reproduce your complete calendar setup to localize the error.
Can you send me an export of these tables:
- wp_bookacti_activities
- wp_bookacti_events
- wp_bookacti_event_groups
- wp_bookacti_exceptions
- wp_bookacti_groups_events
- wp_bookacti_group_categories
- wp_bookacti_meta
- wp_bookacti_permissions
- wp_bookacti_templates
- wp_bookacti_templates_activities

**Comment by yoancutillas** [comment]
Do you still need help with that issue?

**Comment by opcoach** [comment]
Well it seems to work now with the new release. I will close it and reopen if I get it again. 
Thanks.
