### ISSUE TITLE
The notification's title does not transform variables

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#47]
In the notification title if we put a variable name like {user_firstname} or {booking_title} the transformation is not made. 

For instance title with 'Votre réservation de {booking_title} est en attente' should be transformed into "Votre réservation de Salle 2 est en attente"

It works for the content of the email. But for different kind of reservation it would be really nice to be able to display the type of reservation in the title.

**Comment by yoancutillas** [comment]
This will be integrated in he next release 1.7.17, thank you for reporting.
