### ISSUE TITLE
Notification messages should be different for each kind of planning

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#48]
I have 2 plannings : 

* one for rooms
* one for training

I would like to have different notifications either for rooms or for training... Notification is for all planning and depends of the event : 'customer canceled a booking' whatever the booking (room or training..).

**Comment by yoancutillas** [comment]
Thank you for your request, I have noted it in the Notification Pack add-on backlog, pending for votes to increase the development priority.

**Comment by yoancutillas** [comment]
Released in [Notification Pack 1.2](https://booking-activities.fr/en/blog/notification-pack-1-2-per-activity-notifications-scheduled-notifications/).
