### ISSUE TITLE
Name of event should be defined in a planning

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#49]
For an activity it is possible to define the text of its unit. For instance : place, réservation, participant, ... 

But it is not possible to define the name of an event in a planing. 

- In my 'training' planing, the events are 'training'
- In my 'room' planing, the events are 'rooms'

This name should be also defined as a variable and usable in the text or title of notifications. 

What I would like to receive in a title of an email : 

  John Doe reserved the **room** Salle 2 from 2/2/20 to 3/2/20
or
   John Doe reserved 2 **seats** for the training GIT starting the 2/2/20

**Comment by yoancutillas** [comment]
Can you define the aim of this feature?
As I understand it, the purpose would be to replace the word "event" in 
- "Selected event" when you select an event
- the various error messages appearing if the booking cannot be made
Is this what you intended?

I cannot add a unit per calendar because 
- booking forms can display event from multiple calendars
- the same activity can be displayed on multiple calendar, it is not possible to know from wich calendar it was booked

However, it is possible to use the activity unit instead, in the notification too. It will require to add a unit name field in group categories settings too.

**Comment by opcoach** [comment]
The activity unit is not really the same. 

For instance : 
 in the 'room' planning, I will have :  name of event : room, unit : place
in the 'training' planning,  name of event is : 'Training', unit is 'seat'

The goal of this feature is to know in the mail title what is booked exactly. My admin receives 2 kind of emails : for room and training, and it is not possible to distinguish them unless by reading the email content....   Instead of having an email with 'Nouvelle réservation !', we could have :  A '_room_' has been booked by X for the 3/4/2020 or  The '_training_' abcd can interest Mr X  ... 

This bug is bound to the issue #47

**Comment by yoancutillas** [comment]
Ok thank you for the clarification, I didn't understand the difference between both.
It sounds a little bit specific to me, I note your request and wait for votes.

For now, you can add custom notification tags by code:
```
// Add tags to notifications
function my_theme_add_notification_tags( $tags, $notification_id ) {
	$tags[ '{my_tag}' ] = 'My tag description.';
	return $tags;
}
add_filter( 'bookacti_notifications_tags', 'my_theme_add_notification_tags', 100 , 2 );

// Set additionnal notification tags values
function my_theme_set_notification_tags_values( $tags, $booking, $booking_type, $notification_id, $locale ) {
	$tags[ '{my_tag}' ] = 'my tag value';
	return $tags;
}
add_filter( 'bookacti_notifications_tags_values', 'my_theme_set_notification_tags_values', 100, 5 );
```

In your case, you can replace `'my tag value'` by `'room'` or `'training'` according to the `$booking->form_id` for example.

**Comment by opcoach** [comment]
Ok ! Cool :) I guess I should put this code in the functions.php file ? 

Or could I put it in my Interindep.php plugin file ?

**Comment by yoancutillas** [comment]
Yes, the custom code is generally found in the child theme functions.php,
But if you have created a WordPress plugin, you can add it to its files, it should work too.

**Comment by yoancutillas** [comment]
Now that you can use tags in notifications titles, you can use the following title "{activity_title} has been booked", so you know what has been booked without opening the email. I assume this solves the issue. For anything more specific, it will be down to custom code like above for now.
