### ISSUE TITLE
Default booking state - Issue

### ISSUE THREAD

**Issue by unomobil** [bookingactivities/booking-activities#5]
Default booking state, is showing all bookings as BOOKET, after n order has Been maid and paid, even as it set to PENDING, under settings.

**Comment by bookingactivities** [comment]
Hello,

This default state applies only for bookings made through the booking form generated with the shortcode [bookingactivities_form ...]. Or when you use WooCommerce with free products.

Booking Activities manages the booking states itself with WooCommerce orders:
- If the order is made but not paid yet, the bookings are pending
- If the order is completed, the bookings are booked
- A paid orders containing only bookings is automatically completed, and then its bookings are booked
- If an order contains bookings and non-virtual products is paid, the order is still processing, but the bookings are booked

Regards,

**Comment by unomobil** [comment]
Ooohhh

I have testet with a free activity :) 

But even if it a free or paid, customer shoud not receive a booked e-mail automatic, as the owner first want to confirm the activity, in case that there is to little bookings on the event and need to cancel.  


TIPS. 
Is it possible to implement an print out function so (i) Can print out an list with all the people who is ordered a ticket on a specific event .  Payment status, firstname, lastname, phone number ? That Will be really greate :). 

Also a place for the event is needed, at the moment i have to write it in the description ...

Nice plugin you have made :).

Michael 


Sendt fra min iPhone

**Comment by bookingactivities** [comment]
Thank you, I am glad you appreciate it.

You can disable "Booked" notifications in Booking Activities settings, "Notifications" tab.

You can also totally remove the default behaviour of turning activities to "booked" when an order is completed by adding this code in your (child) theme's functions.php:

```
remove_action( 'woocommerce_order_status_completed', 'bookacti_turn_temporary_booking_to_permanent', 5 );
remove_action( 'woocommerce_order_status_pending_to_processing', 'bookacti_turn_non_activity_order_bookings_to_permanent', 5 );

function your_theme_id_bookacti_turn_temporary_booking_to_permanent( $order_id, $order ) {
  bookacti_turn_temporary_booking_to_permanent( $order_id, $order, 'pending', 'paid' );
}
add_action( 'woocommerce_order_status_completed', 'your_theme_id_bookacti_turn_temporary_booking_to_permanent', 5, 2 );
```

Thank you for your suggestion about the print function. I add it to the development schedule, but there is a lot of high priority development before.

Regards

**Comment by unomobil** [comment]
Thanks, i Will use that,  so i have full controller befor informing user of the the booking .
