### ISSUE TITLE
Javascript error TypeError: i is null fullcalendar.min.js:8:14156

### ISSUE THREAD

**Issue by Kr1sp3r** [bookingactivities/booking-activities#50]
Hi, I just installed your plugin and am trying to view a WooCommerce booking page but the calendar doesn't load. The Console shows:-
TypeError: i is null fullcalendar.min.js:8:14156
    build https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:8
    setDate https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:7
    renderView https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:10
    initialRender https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:10
    render https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:10
    fullCalendar https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:12
    jQuery 2
    fullCalendar https://www.thecatandwolf.com/wp-content/plugins/booking-activities/lib/fullcalendar/fullcalendar.min.js?ver=1.7.16:12
    bookacti_set_calendar_up https://www.thecatandwolf.com/wp-content/plugins/booking-activities/js/booking-method-calendar.min.js?ver=1.7.16:1
    bookacti_booking_method_set_up https://www.thecatandwolf.com/wp-content/plugins/booking-activities/js/booking-system-functions.min.js?ver=1.7.16:1
    <anonymous> https://www.thecatandwolf.com/wp-content/plugins/booking-activities/js/booking-system.min.js?ver=1.7.16:1
    jQuery 2
    <anonymous> https://www.thecatandwolf.com/wp-content/plugins/booking-activities/js/booking-system.min.js?ver=1.7.16:1
    jQuery 4

Hoping someone can help as this plugin is looking promising.

**Comment by yoancutillas** [comment]
Hello, 
This is probably due to a javascript conflict with antother plugin or with your theme.
Can you follow the instructions below "Booking Activities doesn’t work as it should" here : [https://booking-activities.fr/en/documentation/faq/](https://booking-activities.fr/en/documentation/faq/)

**Comment by Kr1sp3r** [comment]
Hi, 

I deactivated all plugins except Booking Activities and WooCommerce, problem is still there. Left them all deactivated and changed the Theme to Twenty Seventeen, still there. 

Wordpress 5.3.2
WooCommerce 3.6.3
PHP 7.2.26
Booking Activities 1.7.16

**Comment by yoancutillas** [comment]
Can you give me the URL of the page where I can see the error?

**Comment by Kr1sp3r** [comment]
The page is hidden from public view as is it not finished. But I will open it now. https://www.thecatandwolf.com/product/reiki-session-1-hour/

**Comment by yoancutillas** [comment]
Thank you,

Keep all your plugins deactivated and Twenty Seventeen activated, then:

1.
Do you encounter the same error in Booking Activities > Booking forms > _your form_?

2.
Can you try to 
- Go to Booking Activities > Booking forms > _your form_
- Go to the "Calendar" field settings
- Validate the dialog with the "Reset" button

**Comment by Kr1sp3r** [comment]
There was no Booking Form to begin with. I guess that must have been the problem. Sorry if I wasted your time.

**Comment by yoancutillas** [comment]
No problem, glad you could solve this issue!

That's because of a backward compatibility feature. Since Booking Activities 1.5, creating a booking form is compulsory.
The backward compatibility for booking forms automatically generated (before 1.5) will soon be dropped.
