### ISSUE TITLE
Allow for users to request a reschedule (regardless of price)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#52]
I have BA setup with WooCommerce to give discounts for bulk registrations.

However, this means that users cannot reschedule without admin assistance because only the admin can "ignore price check".

It would be nice if there was a way for users to "request a reschedule regardless of price" that the admin could later approve.

**Comment by yoancutillas** [comment]
Noted, thank you for request! now pending for votes.

**Comment by blackhatwarrior** [comment]
The above code doesn't seem to work on the frontend anymore. 

Customer is getting this error: `The selected event doesn't have the same price as your current booking.`

Any solution?

**Comment by yoancutillas** [comment]
bapap_allow_to_reschedule was renamed to bapap_booking_can_be_rescheduled_to in 1.4.16. Code updated.

**Comment by yoancutillas** [comment]
Released in Booking Activities 1.16, and Prices and Credits 1.8.7
