### ISSUE TITLE
Admin user should be able to change a booking's owner

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#53]
As an administrator, it is possible to change the current status, the date or the quantity of any booking. 
That would be very handy to be able to change also the **booking's owner**. I do it by changing the ownerId in the database, but this is of course not safe... 

Basicaly, I need to change or create some booking for customers (because they just send me a list of days to book and they don't want to manage it), so I want to create them as administrator and then to change the owner.

**Comment by yoancutillas** [comment]
Hello, you can actually create bookings from the admin panel with the [Order for Customers](https://booking-activities.fr/en/downloads/order-for-customers/) add-on.

**Comment by opcoach** [comment]
Ok, I haven't seen that. 

So I close this issue. 

Thanks
