### ISSUE TITLE
Use the user_display name in the 'Customer' combo in the query filter

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#54]
In the 'booking' form, there is a query filter containing the "Customer" field. Names are displayed using user_
<img width="1157" alt="UserDisplayName" src="https://user-images.githubusercontent.com/1716878/73661312-2487aa00-469a-11ea-8a5e-b91556ea68d5.png">
login instead of user_displayName.

**Comment by yoancutillas** [comment]
Thank you for your feedback,
The display name can be either the login, or a combination of the first name and the last name. I will display the three of them in the next update: first name, the last name and the login.

But you can customize it with the API, for example:
```
function my_theme_change_user_selectbox_label( $args, $raw_args ) {
	$args[ 'option_label' ] = array( 'display_name', ' (', 'user_email', ')' );
	return $args;
}
add_filter( 'bookacti_user_selectbox_args', 'my_theme_change_user_selectbox_label', 20, 2 );
```
