### ISSUE TITLE
Book for Customers and Woocommerce (User Expectation)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#55]
A few days ago, I tried to book for a customer from BA (instead of WooCommerce). I found that, since I did not book via WC, the purchase did not show up in WC data.

This is behavior fine, but I think that there should be a notification telling the admin to expect this.

Otherwise, if there is a way to choose the product from the dashboard, that would be even better. However, I assume that would be a lot more work.

**Comment by yoancutillas** [comment]
You can do that with the [Order for Customers](https://booking-activities.fr/en/downloads/order-for-customers/) add-on:

1.
Create a booking from the backend (Booking Activities > Bookings > Add new)
Keep a note of the new booking ID.

2.
Create an order from the backend (WooCommerce > Orders > Add order)
Then click Add item(s) > Add product(s) > Choose the product to add and its quantity > Add
Finally, mouseover the newly created item > click "Bind a booking" > entrer the corresponding booking ID > OK

**Comment by pikurasa** [comment]
Ok, I get it now.

I think that the "discoverability" could be improved.

Finding Step 1 in your comment is not too hard, but without the documentation it is hard to find Step 2. The easiest first fix could be to display a link to the documentation you have provided in this comment.

**Comment by yoancutillas** [comment]
Ok, will do, thank you for your feedback.

**Comment by pikurasa** [comment]
Just tried it now. It did take me a second to understand that the reason I was getting an error was because I needed to select "booking group" not "booking".
