### ISSUE TITLE
Display event title / availability on multiple lines in Basic views

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#57]
In my project, on the attached page you can see that daily activities are displayed using only 1 line...  while there is enough space in the cell... 

How can we change this ?  Have a global parameter to say : display activities on X lines anyway ? wrap the text automatically ? 

<img width="954" alt="ImproveActivityDisplay" src="https://user-images.githubusercontent.com/1716878/73828875-51ef6780-4802-11ea-8321-8988d30a8bad.png">

**Comment by opcoach** [comment]
I found a workaround to reduce the size : remove the unit when activity is on one day. But it is not enough...

**Comment by yoancutillas** [comment]
I have already tried to do that, but it breaks the rendering. I have opened a github issue to report the bug, and I couldn't find a workaround for now.

See this thread for reference: [https://github.com/fullcalendar/fullcalendar/issues/4751](https://github.com/fullcalendar/fullcalendar/issues/4751)

**Comment by yoancutillas** [comment]
This will be fixed when Booking Activities will update FullCalendar to v5. This is planned, but for a longer term, so I close the issue for now.
