### ISSUE TITLE
The calendar display no longer works since 1.7.17 

### ISSUE THREAD

**Issue by Stefko22** [bookingactivities/booking-activities#59]
Hello ! thank you in advance for your help. Problem since version 1.7.17 : The calendar display no longer works. I sent an email to support but nobody answers ... Thank you

**Comment by yoancutillas** [comment]
Hello,
Sorry I didn't receive your support request before yesterday.

- The calendar is not displayed at all, or only its events?
- Does the problem occur on the backend, in Booking Activities > Booking Forms > _your form_?

**Comment by Stefko22** [comment]
Bonjour et merci pour la réponse rapide :-)

Le calendrier ne s'affiche pas du tout dans la page.
Il n' y a pas de problème dans la partie administration du site le problème
ne se pose que dans la page réservée aux personnes qui souhaitent réserver
un rendez-vous.

Merci d'avance pour votre aide.
Stéphane



Le lun. 10 févr. 2020 à 11:17, yoancutillas <notifications@github.com> a
écrit :

**Comment by yoancutillas** [comment]
Pouvez-vous mettre à jour Booking Activities (et ses add-ons si vous en utilisez) et
1.
- Aller dans Booking Activities > Formulaires de réservation > votre formulaire
- Aller dans les paramètres du champ "Calendrier"
- Cliquer sur le bouton "Réinitialiser"
- Vérfier si cela fonctionne à nouveau

2. Sinon,
- Vous rendre sur la page où le problème se produit
- Ouvrir la [console de votre navigateur](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers#answer-77337)
- M'envoyer une capture d'écran de la console si une erreur apparait

**Comment by Stefko22** [comment]
Bonjour et merci pour le message

J'ai testé comme vous me l'avez demandé mais cela ne change rien.

Voici une capture vidéo de ce qui se passe :

https://screencast.com/t/JPjfReNDT

Faites bien attention au moment ou je raffraichis la page on voit que ça
commence à charger puis plus rien, il n'y a rien qui s'affiche...

Je remets l'ancienne version pour que ça fonctionne en attendant que vous
trouviez d'ou cela provient...

Merci pour tout,
Stéphane

Le lun. 10 févr. 2020 à 12:31, yoancutillas <notifications@github.com> a
écrit :

**Comment by yoancutillas** [comment]
Pouvez-vous me donner l'URL de la page où se situe le problème et mettre à jour Booking Activities le temps que j'effectue quelques tests afin d'identifier la source du problème.

Si la page du calendrier est inaccessible au public, vous pouvez m'envoyer des informations d'identification par e-mail.

**Comment by Stefko22** [comment]
Bonjour et merci pour la réponse rapide.

Voici le lien du site d'une amie qui utilise aussi le plugin et chez qui
cela ne fonctionne plus comme chez moi :

https://www.muriel-joulian.com/reservation-seance-daccompagnement-individuelle/

L'agenda ne s'affiche pas, le plugin est à jour...

Merci pour tout,
Stéphane

Le mer. 12 févr. 2020 à 11:09, yoancutillas <notifications@github.com> a
écrit :

**Comment by yoancutillas** [comment]
Pouvez-vous effectuer ces deux dernières vérifications :
1. Assurez vous que le shortcode est bien de la forme `[bookingactivities_form form="1"]` et non pas `[bookingactivities_form calendars="1" activities="1,2"]`, ni `[bookingactivities_form]`
2. Suivez les instructions sous "Booking Activities ne fonctionne pas comme il le devrait" sur [cette page](https://booking-activities.fr/fr/documentation/faq/) afin de vérifier si le problème vient d'un conflit avec un plugin / thème tiers.

Le cas échéant, j'aurais besoin d'un accès administrateur à votre site pour poursuivre le débuggage, si vous êtes d'accord, vous pouvez m'envoyer les identifiants par email à contact@booking-activities.fr.

**Comment by Stefko22** [comment]
Bonjour et merci pour le message

Je vous envoie un accès admin sur un clone j'ai testé et désactivité les
plugins mais cela ne change rien...

Merci d'avance,
Stéphane Colle

Le jeu. 13 févr. 2020 à 10:19, yoancutillas <notifications@github.com> a
écrit :
