### ISSUE TITLE
calendar layout on product page problem

### ISSUE THREAD

**Issue by carorgetan** [bookingactivities/booking-activities#6]
Hello,

In my website, products to book pages  (using woocommerce plugin)  , the calendar layout is not correct. It is not wide enough, it occupies half of the page width instead of all of it. I've read this was fixed in version 1.3.3 , but this is the version that I'm using... How can I change the width of the calendar?

thx!
Regards,
Carolina Rodriguez-Getan

**Comment by carorgetan** [comment]
![image](https://user-images.githubusercontent.com/12698454/36545512-5c84f32c-17e9-11e8-8340-7884b32771d7.png)

**Comment by bookingactivities** [comment]
Hello Carolina,

Thank you for using Booking Activities.

1.3.2 made calendar **editor** full width only.
But frontend calendars are always full width. It is actually your theme that separates the images from the product info in two columns.

I have provided a solution in this post:
https://wordpress.org/support/topic/location-of-the-calendar-section/

This is the very lines of code I am using for Booking Activities Demo website. I hope it will help you in your integration work.

Regards, 
Yoan Cutillas

**Comment by carorgetan** [comment]
Hello,

I tried and it worked! Thank you very much for your help.

Regards,
Carolina Rodriguez-Getan
