### ISSUE TITLE
Inheritance Design Consideration

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#60]
One reason I really like BA is the ability to structure events into different groups as well as "group categories".

This being said, I really wasted a lot of time inputting data into **single events** (i.e. price) that I later override by creating a **group**. Just recently, I also discovered that I could specify price for a **group categories**, which I assume the groups inherit.

I will leave this open ended with a question: How can we make this inherited design feature more obvious to new users?

**Comment by yoancutillas** [comment]
Thank you for your feedback,
How about adding a text in the event / group of event settings dialog:
"You can set a default price in the activity / group category settings."?

**Comment by pikurasa** [comment]
Certainly, I think that would help future users.

When I have the chance, I will send some screenshots from a theming plugin which has a similar inheritance structure. It may be informative.

**Comment by yoancutillas** [comment]
Ok thank you,
And I'll add the notice in next release.

**Comment by yoancutillas** [comment]
Released in Prices and Credits 1.4.9
