### ISSUE TITLE
Temporal "Transposition" for Groups of Events

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#61]
I have many events (and groups) that repeat almost verbatim every two months.

It would be nice to be able to copy groups of events into a new group, starting from another time (typically in the future). Once copied, other small changes can be made to the new copy.

If this feature already exists, please let me know. I noticed "import from calendar", but that suggests something different to me, and I am rather risk-averse at the moment with my live site.

**Comment by yoancutillas** [comment]
The features to duplicate a group of events (to another date), and to repeat groups of events are planned. They still need to be designed, but the idea is to offer the same options as single events.

**Comment by yoancutillas** [comment]
Released in Booking Activities 1.12 ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/repeat-a-group-of-events/)).
