### ISSUE TITLE
Improvement to CSS for group of event selection in Mobile 

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#62]
The dialogue for Group of Event selection is not as "mobile friendly" as it could be.

https://demo.booking-activities.fr/en/shop/groups-of-events/

For one, I think the dialogue should fill the width of the screen of a mobile device.

(Many of my clients register using their phones. They have shown me first-hand their experience.)

**Comment by yoancutillas** [comment]
Thank you for reporting,
the dialog is actually 400px wide,
I will add two CSS thresholds, at 320px and 360px, which match the popular screen sizes.

**Comment by pikurasa** [comment]
This is better--great!

I have two more improvement ideas.

Radio buttons are a little hard for someone just using their thumbs. I recommend removing the radio buttons.

I do not know exactly what should be done with the text, but I think it can be improved. Maybe bigger text, and it should wrap around. The left <--> right scrolling should be entirely removed.

![Screenshot at 2020-05-03 07:38:18](https://user-images.githubusercontent.com/13454579/80913272-f7977180-8d32-11ea-8811-38e898ec1db7.png)

**Comment by yoancutillas** [comment]
It is possible to click on the group title title to select it, no need to target the radio button.
Well I personnally think that it is more readable to have 1 event per line, displayed smaller than the group title. I will wait for more feedbacks, but you can change it with custom CSS meanwhile. Nothing definitive though, don't hesitate to share screenshots of your version.
