### ISSUE TITLE
Option to Hide Price

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#63]
I have a calendar that I publish on one of the pages on my site using https://demo.booking-activities.fr/en/shortcodes-integration/

It is nice, but for this particular page I would like to hide the price.

Having the price displayed on the page makes it look like I just care about money, which is not my intention.

**Comment by yoancutillas** [comment]
I note your feature request, thank you. You cna use one of these workarounds:
___
You can hide them with CSS, in Appearence > Customize > Additional CSS:
- For a page: `.page-id-122 .bookacti-price-container { display: none; }` (`122` is the page ID)
- For a post: `.postid-176 .bookacti-price-container { display: none; }` (`176` is the post ID)

___
With CSS too, 
- First go to Booking Activities > Booking Form > _your form_
- Go the the "Calendar" field settings > Display tab > Set "no-price" in the "Class" option
- Add this CSS code in Appearence > Customize > Additional CSS:
`.no-price .bookacti-price-container { display: none; }`

___
Alternatively, if all your events have the same price, you can set the form price:
- Go to Booking Activities > Booking Form > _your form_
- Go to the form settings (click on the gear next to "Form editor")
- Set the desired price in the "Price" option (if the form is bound to a product, the product price is used instead on the product page)

If the event price is the same as the form price, the price won't be displayed, assuming you display it elswhere on the page.

**Comment by pikurasa** [comment]
Super helpful. Thanks

**Comment by yoancutillas** [comment]
Released in Prices and Credits 1.6.0
