### ISSUE TITLE
Convenient Rebooking Feature for Clients? 

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#65]
A client asks me "is it possible to rebook the same event without having to click through everything again and again?"

I cannot really imagine what the design for this would be, but I do have groups of events that occur every two months and many clients keep the same schedule.

Context: I am using the WC integration method.

Ideas:
* Similar events created by copy method (possibly https://github.com/bookingactivities/booking-activities/issues/61) are tracked.
* Client rebooks via a one-click method on "My Accounts Page" or via email link.
* Admin is given some "rebooking" tools.

@yoancutillas as I expect this request to be a little bit "niche", please let me know how realistic this is. That being said, anything to make this more convenient would be appreciated.

At the moment, I spend a lot of time booking on behalf of my clients who do not want to click through registration on the website.

**Comment by yoancutillas** [comment]
I am not sure, the customers will need to go through the checkout anyway.
So instead of using this path:

> Shop > Product page > Select the event / group of events > Book button

The customer would use this path:

> My account > Bookings tab > Rebook button > Confirm the preselected event / group of events

___

However, you can preselect an event / group of events, and even prefill a booking form via the URL:
- You can preselect an event / a group of events by adding parameter to the URL of the page where the calendar is displayed. For example: 
     - Preselect a group of events: https://demo.booking-activities.fr/en/shop/groups-of-events/?bookacti_group_id=7
     - Prefill a whole booking form: [example](https://demo.booking-activities.fr/en/shop/advanced-booking-form/?bookacti_group_id=single&bookacti_event_id=399&bookacti_event_start=2036-06-08+08%3A20%3A00&bookacti_event_end=2036-06-08+12%3A20%3A00&phone_emergency=0102030405&nap_time=11%3A10&extras=2&bonus=0&bonus=1&free_comment=Prefilled+comment&participants_nb=2&participants%5Bgender%5D%5B0%5D=boy&participants%5Bfirst_name_participant%5D%5B0%5D=Yoan&participants%5Bfavorite_color%5D%5B0%5D%5B%5D=none&participants%5Bfavorite_color%5D%5B0%5D%5B%5D=red&participants%5Bpaid_outings%5D%5B0%5D=cinema&participants%5Bgender%5D%5B1%5D=boy&participants%5Bfirst_name_participant%5D%5B1%5D=Pikurasa&participants%5Bfavorite_color%5D%5B1%5D%5B%5D=none&participants%5Bfavorite_color%5D%5B1%5D%5B%5D=blue&participants%5Bfavorite_color%5D%5B1%5D%5B%5D=yellow&participants%5Bpaid_outings%5D%5B1%5D=none&quantity=2)
- With Notification Pack, you can add an event/group of events-specific text to your emails.

So you can add the link to the next event / group of events in your emails.

**Comment by pikurasa** [comment]
This is helpful. I will try some of these.

**Comment by pikurasa** [comment]
I have notification pack, but guess I have not fully explored its features... The clients do like the event reminders, however.

**Comment by yoancutillas** [comment]
Nice to know, thanks!

**Comment by yoancutillas** [comment]
I don't know what to do more for that issue, so I'll close it for now, but don't hesitate to open it again if you can think of a solution to improve it.
