### ISSUE TITLE
Error on booking

### ISSUE THREAD

**Issue by agcodelab** [bookingactivities/booking-activities#66]
I configured a calendar and a booking form for each woocommerce products, but when I try to test the booking system I always get the following message:

"The amount of desired bookings is less than or equal to 0. Please increase the quantity."

Even if it is set to 1.

**Comment by yoancutillas** [comment]
Hello,

This is probably due to a conflict with your theme, or with another plugin.
Can you follow the instructions below "Booking Activities doesn’t work as it should" [on this page](https://booking-activities.fr/en/documentation/faq/) and let me know the results?
