### ISSUE TITLE
Undefined index error

### ISSUE THREAD

**Issue by mjas82** [bookingactivities/booking-activities#68]
Hi, My site has started displaying the following error on the frontend on our event booking pages

Notice: Undefined index: hide_timepicker in /homepages/39/d670423831/htdocs/WP-Root/wp-content/plugins/ba-display-pack/controller/controller-forms.php on line 40

I've managed to temporarily 'fix' this by removing the code on line 40 but not sure that this is the best long term fix or if I'll end up breaking anything by doing so! Running the latest versions of wordpress and avada theme, all plugins fully updated.

website is borderlandsoutdoor.com and the error appears on https://www.borderlandsoutdoor.com/product/next-step-navigation/ among other pages

Any thoughts on this?

Thanks

**Comment by yoancutillas** [comment]
Hello,

Yes, sorry, that's a bug a fix will be released in the next version. Thank you for reporting!

Here is a temporary fix to apply in /wp-content/plugins/ba-display-pack/controller/controller-forms.php:
- replace `$defaults[ 'allow_tooltip' ]` with `$defaults[ 'calendar' ][ 'allow_tooltip' ]` lines 39 and 61
- replace `$defaults[ 'hide_timepicker' ]` with `$defaults[ 'calendar' ][ 'hide_timepicker' ]` lines 40 and 62

**Comment by mjas82** [comment]
Thanks for the quick reply. 
I've just tried that but the error seems to have come back. The full line of code on line 40 now reads
$field_data[ 'hide_timepicker' ] = in_array( $raw_field_data[ 'hide_timepicker' ], array( 'never', 'single_event' ), true ) ? $raw_field_data[ 'hide_timepicker' ] : $defaults[ 'calendar' ][ 'hide_timepicker' ] ;
As I've replaced the default text at the end. 

Error message Undefined index: hide_timepicker in /homepages/39/d670423831/htdocs/WP-Root/wp-content/plugins/ba-display-pack/controller/controller-forms.php on line 40 is showing on the frontend. The error message displayed twice previously but only appears once now, so seems to have partially fixed it.

**Comment by yoancutillas** [comment]
My bad,
replace line 40 and 62 with:
`$field_data[ 'hide_timepicker' ] = isset( $raw_field_data[ 'hide_timepicker' ] ) && in_array( $raw_field_data[ 'hide_timepicker' ], array( 'never', 'single_event' ), true ) ? $raw_field_data[ 'hide_timepicker' ] : $defaults[ 'calendar' ][ 'hide_timepicker' ];`

and replace line 39 and 61 with:
`$field_data[ 'allow_tooltip' ] = isset( $raw_field_data[ 'hide_timepicker' ] ) && in_array( $raw_field_data[ 'allow_tooltip' ], array( 0, 1, '0', '1' ), true ) ? intval( $raw_field_data[ 'allow_tooltip' ] ) : $defaults[ 'calendar' ][ 'allow_tooltip' ];`

**Comment by mjas82** [comment]
Thanks, that seems to have done it

Appreciated

**Comment by yoancutillas** [comment]
Fixed in Display Pack 1.4.11 and Booking Activities 1.8.0.
