### ISSUE TITLE
Add activity to an existing group

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#69]
Sometimes I make a group, and then find out that I forgot to add a single activity. It would be nice to be able to add activities to an existing group.

**Comment by yoancutillas** [comment]
Hello, you can actually do that ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-booking-activities/create-groups-of-events/)):

- Click on the name of the group, all the events of the group will be selected.
- If you want to add or remove an event from the group, select / deselect it.
- Then click the setting wheel of the group to open a dialog
- Here you can change the name of the group, its category and its price (only with Prices and Promotions add-on).
- Check the grouped events list
- Confirm by clicking on the “OK” button

**Comment by yoancutillas** [comment]
Do you need more help with it?

**Comment by pikurasa** [comment]
> Do you need more help with it?

I was able to do it just now. I think this feature is rather difficult to discover, and the docs are probably not as clear you think they are...

I think that 1) you should add to your documentation the specific question of "how to add an activity to an existing group", and 2) Perhaps under the "events list" section of the edit dialogue, put a short tip for how to do this.

What I was expecting:

I was expecting a plus button under "events list" to add something.

Else...

I was expecting a plus button to appear in place of the setting wheel after I select more activities than are in the group currently selected.

**Comment by yoancutillas** [comment]
Thank you for your feedbacks, I have noted your improvement suggestions and I will try to add some in a future release.
Indeed, the documentation needs to be redesigned.
