### ISSUE TITLE
Problème d'affichage

### ISSUE THREAD

**Issue by vikingviolet** [bookingactivities/booking-activities#7]
Bonjour,

Votre plugin est très bien fait et très interessant,

Cependant à l'activation il modifie l'apparence du thème que j'utilise (game addict de skywarriors)

voici les screen le premier avant activation , le second après

http://prntscr.com/iofpii
http://prntscr.com/iofpmz

Merci d'avance pour votre retour

Excellente journée

**Comment by bookingactivities** [comment]
Bonjour,

Merci pour le compliment sur Booking Activities.
Je pense avoir localisé le code qui pose problème.

Pouvez-vous essayer la dernière version de développement de Booking Activities pour valider que votre problème est corrigé :
https://github.com/bookingactivities/booking-activities/archive/dev.zip

S'il ne l'est pas, essayez également d'ajouter ce code au fichier functions.php de votre thème (enfant) : 
```
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_scripts', 30 );
function my_theme_enqueue_scripts() {
	wp_dequeue_style( 'jquery-ui-bookacti-theme' );
}
```
Cordialement,

**Comment by vikingviolet** [comment]
Merci pour votre réponse rapide !

aucun résultat avec la nouvelle archive
Cela à fonctionner avec l'ajout de code

merci beaucoup

**Comment by bookingactivities** [comment]
Ok, merci pour votre retour.  
Pour information, votre thème doit utiliser son propre theme jQuery UI, ce qui génère un conflit avec celui de Booking Activities.

Ravi d'avoir pu vous aider.
Cordialement,
