### ISSUE TITLE
"Are started events bookable?" seams not working anymore

### ISSUE THREAD

**Issue by MacGeyer** [bookingactivities/booking-activities#72]
This option is working on one of my website in version 1.7.20
This option doesn't work on another website using Version 1.8.4 + Advenced Forms 1.2.9 + Display Pack 1.4.12 + Notification Pack 1.1.7
I didn't find any new configuration introduced by the optional plugins, is this a bug ?

**Comment by yoancutillas** [comment]
Make sure the "Calendar timezone" is properly set in Booking Activities > Settings > General.

Then you also need to set your calendar opening to a past date (before the beginning of the event) in Booking Activities > Booking forms > your form > Calendar settings > Availability tab > Opening option.

The past events won't be displayed (if you don't turn the corresponding option on), but the started events will if the Opening date is before their starting date.

**Comment by MacGeyer** [comment]
Right setting "Opening option" to current date or before make it work as expected, but I didn't had to do this with my previous version ...

**Comment by yoancutillas** [comment]
Thank you for your feedback,
Yes, the availability period takes into account the date **and time** since 1.8.
Leaving the Opening field empty means "now", so the calendar begins at the current time and therefore exclude the started events.
