### ISSUE TITLE
Most of email are sent but some are never sent.

### ISSUE THREAD

**Issue by MacGeyer** [bookingactivities/booking-activities#73]
User is registered but the email is never sent, we use our own mail server to relay the emails, and no hit is found in our logs.

**Comment by yoancutillas** [comment]
You encounter a problem with the "New account" email only?

Can you make sure that the "Send new account email" option is turned ON in:
Booking Activities > Booking forms > User data (Login / Registration) settings > Registration tab

If you still don't receive the email, can you follow the instructions below "I don’t receive the notifications" on that page: https://booking-activities.fr/en/documentation/faq/
Especially the instructions below:
- Do other emails sent by WordPress work?
- Do notifications work when they are not deferred?
(If you encounter a problem with the other emails too, follow all the instructions.)

**Comment by MacGeyer** [comment]
Sorry for the delay, I didn't mean user registration but some reservation emails aren't sent.
In my website no registration is needed, user have only to set the email and the name to set a reservation, arround 95% of the emails are sent but some are not.
It's not a spam problem because the PHP code doesn't hit my local SMTP server

**Comment by yoancutillas** [comment]
This looks like a WP Cron error,

Can you follow the instructions below "I don’t receive the notifications" > "Do notifications work when they are not deferred?" on that page: https://booking-activities.fr/en/documentation/faq/

(In shorts, turn OFF the Booking Activities > Settings > Notifications tab > "Asynchronous notifications" option)
