### ISSUE TITLE
Bookers Unable to Edit Their Bookings

### ISSUE THREAD

**Issue by fmevans** [bookingactivities/booking-activities#77]
Some users are claiming to to have received confirmation emails from BA.

There is:
https://booking-activities.fr/en/faq/i-do-not-receive-the-notifications/

HOWEVER: neither confirmation emails nor the bookings form are giving users the ability to _edit_ their bookings after they have made them (e.g. to cancel a booking). This is despite having set:

**Activity parameters>Availability>Changes are allowed for bookings starting in at least**

...to 2 days

Can this be fixed? Thank you :)

**Comment by yoancutillas** [comment]
Hello,

 Sorry, I have answered to your previous email, but I just copy the answer here, so everyone can benefit of it.

1.
- Disable the "Asynchronous notifications" option in  Booking Activities > Settings > Notifications tab  
- Make sure the "Booking status turns to "Pending"" or " Booking status turns to "Booked"" notification are enabled (according to the "Default booking state" option in Booking Activities > Settings > General)
- If you are using WooCommerce, enable the "Send when an order is processing" or "Send when an order is completed" option in the previously mentioned notification settings

2.
The customers will be able to cancel, reschedule or request a refund from their booking list only, they cannot do that from the email.
- The customers' booking list can be displayed thanks to the [bookingactivities_list] shortcode (docs)
- The customers will need to be logged in to see their booking list, so it is recommended to display a login form on the same page (docs)
However, you can add a link to the booking list in the email, so your customers can cancel them from there.
