### ISSUE TITLE
Canceling an event by organizer and notifiying participants

### ISSUE THREAD

**Issue by lelex79** [bookingactivities/booking-activities#78]
Hello, 

I'm trying to setup booking activities on a sport association website to let members book an activity. The number of participant is limited which is OK with the plugin but as it's outdoor sport, it might be canceled "last minute" because of weather conditions. 

I'm trying to figure out how I could cancel the occurence of an event and have all the people registered for this event receiving a mail to let them know that this event is particular event is canceled?

Indeed I can cancel every attendee one by one and then they are notified or I can cancel the event itself but then nobody is notified.

**Comment by yoancutillas** [comment]
Released in Booking Activities 1.10
