### ISSUE TITLE
help with cancellation options

### ISSUE THREAD

**Issue by itordable** [bookingactivities/booking-activities#79]
Hello

I have activated the cancellation option in the general options, but when I put the shortcode [bookingactivities_list], the actions box comes out empty, what could be the problem?

Thanks and great job with this plugin

Regards

**Comment by pikurasa** [comment]
I encountered the same issue. I changed it to `{event_booking_list}`or `{booking_title}` and it worked.

That being said, I think there is some bug here as I cannot seem to get `{booking_list}` to work in some cases...

**Comment by yoancutillas** [comment]
Thanks a lot!

- Log in as the customer who made these bookings (bookings without account cannot be changed)
- Make sure your bookings are not past
- In Booking Activities > Settings > Cancellation tab > Set the "Changes are allowed for bookings starting in at least" option to 0 days 0 hours 0 minutes
- In Booking Activities > Calendar editor > your activity (or group category) settings >Availability tab > Empty the fields of the "Changes are allowed for bookings starting in at least" option.
- If you are using a cache plugin or another cache system, clear your cache

**Comment by itordable** [comment]
Hello

It was an error in the configuration of the activities. Already solved.

Thank you very much
