### ISSUE TITLE
Problème d'activation de licence et autres questions

### ISSUE THREAD

**Issue by dkolski** [bookingactivities/booking-activities#8]
Bonjour,

Je viens de faire l'acquisition de la licence Display Pack et je voudrais vous soumettre les points suivants :

1) La date de ma **licence Display Pack** achetée aujourd'hui ne s'affiche pas correctement dans l'admin du site (2 avr 2018 au lieu de 2019.)

 L'écran de création de planning voit bien la licence achetée  mais la licence non activée. voir (copies d'écran jointes). 

![screenshot-2018-4-2 editeur de plannings golf in one wordpress](https://user-images.githubusercontent.com/10338982/38209066-6192c3ce-36b3-11e8-9438-049effa7f332.png)

2) En phase de développement, je rencontre un problème pour **annuler des activités liées** dans le planning. Message indiquant qu'il y a des réservations alors que celles-ci ont été annulées.

3) N'est-il pas possible d'**annuler plusieurs réservations** en même temps ?

4) Je souhaite créer un planning de réservation avec des **séances toutes les 30 minutes tous les jours ouvrables**. J'ai utilisé la méthode suivante qui est très consommatrice de temps :
 a) ajout de l'activité sur 1er créneau de la 1ère journée
 b) activitation de la répétition journalière sur période choisie (x semaines)
- Itération de a) et b) pour les 12 créneaux de la journées 
- opération à renouveler pour chaque nouvelle période de x semaines
N'y-aurait-il pas un moyen plus automatique pour faire la même chose ?

Merci d'avance pour vos réponses.

Cordialement, 

Daniel

**Comment by bookingactivities** [comment]
Bonjour,

Merci pour votre achat.
Pouvez-vous avant tout éditer votre message de sorte à cacher votre clé de licence dans la première image ?

1.
C'est un problème local (étrange), votre licence est bien active jusqu'en 2019 et vous pouvez bien utiliser le Display Pack dès à présent sans restrictions. Pouvez-vous essayer de désactiver puis réactiver la licence ? Cela devrait actualiser la date. Si cela ne fonctionne pas, pouvez-vous me donner votre version de PHP et de MySQL ?

2. 
En effet, le problème est d'ors et déjà corrigé dans la version de développement, je vais faire une mise à jour corrective sous peu.

3.
Non, les actions groupées ne sont pas implémentées, c'est prévue dans le planning de développement, mais à faible priorité pour l'heure.

4. 
Vous pouvez dupliquer un évènement (répété ou non) en maintenant la touche ALT appuyée lorsque vous le déplacez. Outre cela, il n'existe aucun moyen automatisé de remplir votre calendrier.

Cordialement,

**Comment by dkolski** [comment]
Merci pour votre réponse rapide. 

Je vais essayer et vous tiens au courant. 


Amicalement,

Daniel

**Comment by dkolski** [comment]
Bonjour,

1-Problème de licence : J'ai fait la manip de désactivation et ré-activation. Le problème subsiste toujours. Le Display Pack fonctionne avec Woocommerce en mode cascade mais pas en mode direct sans passer pas Woocommerce.
Lorsque je retoune sur l'onglet licence des réglages, le no de licence apparaît avec le bouton "activer la licence". (voir copie écran)

![pb licence ba](https://user-images.githubusercontent.com/10338982/38316472-1c9e642a-382b-11e8-9e89-faa34e710a00.jpg)

Version PHP : 5.6  Version SQL : 5.5  Hébergeur : OVH (Ci-joint l'état système
[Etat système.txt](https://github.com/bookingactivities/booking-activities/files/1876335/Etat.systeme.txt)
 
2-3 Noté

4- La manip avec ALT fonctionne bien. J'avais essayé mais comme il n'y a pas d'indicateur visuel je n'avais pas été jusqu'au bout.

Nouvelle question :

5- J'ai 2 activités distinctes (cours et loisirs) avec des tarifs différents utilisant une même ressource (simulateur de golf).
Je n'ai pas trouvé d'autre solution que de créer 2 produits Woocommerce utilisant le même calendrier et la même activité. Le problème est que ces activités ont des plages horaires communes et distinctes (ex cours pas à certaines heures ou pas l'apres-midi).
Que préconisez-vous ?

Merci d'avance

**Comment by dkolski** [comment]
Re-Bonjour,

1 - J'ai fait les manips indiquées sans succès.

Lorsque je clique sur "Activer la licence" l'icône passe au vert avec le message "la licence est activée" mais la date d'expiration indiquée est la date du jour.
Si je clique sur l'icône verte (ou rouge), j'ai un message d'etteur me proposeant de vérifier l'état de la license. Lorsque j'accepte, j'obtiens un message d'erreur  "La clé de licence est inactive" et l'icône passe (ou reste) au rouge..
Lorsque j'ai le message "licence activée" après avoir cliqué sur "activer la licence", j'ai une indication de licence non activée dans la fonction de modification de planning - onglet agenda.

Cordialement, 

![ba-ecr1-a](https://user-images.githubusercontent.com/10338982/38366889-77b63836-38e1-11e8-80e1-adc9eed12ca5.jpg)
![ba-ecr1-b](https://user-images.githubusercontent.com/10338982/38366890-77d7a70a-38e1-11e8-8f27-4bf2987ee577.jpg)
![ba-ecr2](https://user-images.githubusercontent.com/10338982/38366891-77f52028-38e1-11e8-95bb-97995a03ded4.jpg)

**Comment by bookingactivities** [comment]
Bonjour,

Merci pour votre réponse et les captures d'écran. 
En revanche, prenez soin de toujours cacher votre clé de licence sur les captures d'écran.
Je ne parviens pas à reproduire l'erreur. 

Essayez de mettre à jour MySQL vers la version 5.6 au minimum, Wordpress et par extension Booking Activities ne supporte pas les versions inférieures, ce peut être la cause de l'erreur. Puis réessayez d'activer la licence.

Si cela ne fonctionne pas, il est également possible que ce ne soit qu'un problème d'affichage, on va vérifier en base de données :

Pouvez-vous activer à nouveau votre licence jusqu'à ce que l'icone vert ✔ apparaisse (cf.: comme sur votre première capture d'écran).
Puis allez dans votre base de données, cliquez sur la table (prefix)_options, recherchez toutes les lignes contenant "badp_" dans la colonne "option_name" et envoyez moi une capture d'écran (en cachant la clé de licence).

Voici comment effectuer la recherche :
![recherche-bdd](https://user-images.githubusercontent.com/25784216/38398772-082eb506-3981-11e8-8b0b-ef095461d302.PNG)

Et voici la capture à envoyer :
![resultat-recherche-bdd](https://user-images.githubusercontent.com/25784216/38398781-0eefde06-3981-11e8-8100-3ce89728323b.PNG)

Coridalement,

**Comment by dkolski** [comment]
Voici la copie d'écran de la base ainsi que de la page licence:

![ba-ecr3](https://user-images.githubusercontent.com/10338982/38399312-f3968376-3949-11e8-9593-137da3b66f30.jpg)

![ba-ecr4](https://user-images.githubusercontent.com/10338982/38399381-645c363c-394a-11e8-9906-51573d312eb1.jpg)

J'essaierai de migrer SQL vers 5.6 mais il faut le faire manuellement sur cette version chez OVH. 

====

Concernant le point 5, j'ai essayé avec la première option avec les différentes activités sur un planning unique. 
- Activité Simulateur seul  associée à Produit Séance Simulateur
- Activité Simulateur ou Cours associée à Produits Séance Simulateur et Cours
- Activité Cours Seul associée à Produit Cours
Le client réserve une séance simulateur ou un cours (utilisant le simulateur) 
Cela fonctionne bien avec Woocommerce.
Par contre dans l'écran réservation, le nom de l'activité ne suffit pas à savoir ce qui a été réservé dans le cas de l'activité avec le "ou" car c'est le nom de produit qui est determinant (Cours ou Séance Simulateur) 
=> Y a t'il moyen de rajouter une colonne dans la liste des résa (comme cela se fait sur l'écran des commandes de Woocommerce avec les hooks 'manage_edit-shop_order_columns' et 'manage_shop_order_posts_custom_column' plus du code associé pour renseigner les colonnes.

![ba-ecr5](https://user-images.githubusercontent.com/10338982/38399963-d57cd2ec-394d-11e8-8431-c32e8690d381.jpg)


Cordialement,

**Comment by bookingactivities** [comment]
1.
Merci pour ces info et captures, pouvez-vous cacher votre clé de licence dans la première capture également ?
Ok, pour l'instant, ce qui est en base de données est contradictoire avec les informations affichées, qui sont pourtant basées sur ce qui est en base de données. J'attends de voir si les résultats avec MySQL 5.6 sont identiques avant de poursuivre.

5.
Oui, c'est le même principe. Utilisez les hooks (avec add_filter) :
- `bookacti_booking_list_columns` pour ajouter une colonne
- `bookacti_booking_list_columns_order` pour définir la position de votre colonne
- `bookacti_booking_list_booking_columns` pour remplir votre colonne

Vous trouverez ces filtres dans le fichiers [booking-activities/class/class-bookings-list.php](https://github.com/bookingactivities/booking-activities/blob/master/class/class-bookings-list.php)
Vous trouverez des exemples d'utilisation (colonnes "téléphone" et "email") dans [booking-activities/controller/controller-woocommerce-bookings.php](https://github.com/bookingactivities/booking-activities/blob/master/controller/controller-woocommerce-bookings.php)

**Comment by dkolski** [comment]
Je vais faire la migration SQL vers 5.6 mais ça semble compliqué sur hébergement OVH...

Merci pour réponse au point 5.

J'aurais quelques remarques concernant l'affichage de l'activité sur les différents écrans Woocommerce (panier/checkout/commande reçue) où est formattage n'est pas très bon et pas facilement modifiable en css car les mêmes classes utilisées. Je vous ferai les copies d'écran.
Dois-je continuer sur ce thread ou en créer un nouveau ?  

Merci pour votre support

**Comment by bookingactivities** [comment]
Bonjour,

Ok, merci pour votre persévérance et votre temps, je ne parviens pas à reproduire ni à comprendre l'origine de ce bug. Nous allons donc activer manuellement la licence et vérifier que les mises à jours automatiques fonctionnent.

**Activation manuelle**
Pour activer la licence manuellement, maintenez la touche CTRL appuyée en cliquant sur le bouton "Activer la licence". Une pop up s'affiche, vous indiquant la procédure à suivre pour activer manuellement votre licence. Dans votre cas, c'est déjà fait (vous pouvez toutefois vérifier que le site associé soit le bon), cliquez sur OK. 
Cela devrait remplir correctement les champs dans votre base de données, vous pouvez vérifier dans votre base de données, modifier la date d'expiration au 02 avril 2019 (cela n'impacte que les notifications de rappels). Vous devriez avoir les champs
badp_license_key : votre licence
badp_license_status : valid
badp_license_expiration : 2019-04-02 23:59:59

Avec cela, l'avertissement n’apparaîtra plus sur la boite de dialogue des paramètres du planning, et votre licence apparaîtra comme activée dans les paramètres de Booking Activities, avec la bonne date d'expiration.

**Vérification des mises à jour automatique**
Dans le fichier ba-display-pack/ba-display-pack.php modifiez les numéros de version à la ligne 6 et à la ligne 39 avec des numéros inférieurs. Mettez 1.2.0 par exemple.

Ensuite sur votre panneau d'admin dans Tableau de bord / Mises à jour, cliquez sur le bouton "Vérifiez à nouveau"
![wp-mises-a-jour-verifier-a-nouveau](https://user-images.githubusercontent.com/25784216/38449750-7b02676c-3a4e-11e8-84d7-ce5b674e7d4d.PNG)

Vérifiez alors si la mise jour du module Display Pack vous est proposée:
![mise-a-jour-display-pack](https://user-images.githubusercontent.com/25784216/38449770-c90f26ac-3a4e-11e8-9eef-fb3862362a92.PNG)

6.
J'entendrais avec plaisir vos retours et propositions sur l'affichage des évènements réservés dans un autre thread. Ce sera plus pratique pour les personnes effectuant des recherches à l'avenir. Je vais également modifier le titre de ce thread en "Problème d'activation de licence et autres questions".

Cordialement,

**Comment by dkolski** [comment]
Bonjour,

Lorsque je maintiens la touche CTRL et que je mets la souris sur le bouton Activer la licence,  une petite icône apparaît bien dans le bouton mais lorsque je clique, seul le menu contextuel s'ouvre.
(je suis sur MAC !)

Du coup, j'ai modifié à la main les paramètres dans la base :
-badp_license_key : votre licence
badp_license_status : valid
badp_license_expiration : 2019-04-02 23:59:59 (à la place de badp_version)

L'affichage est correct sur la page licences mais si je re-demande la vérification en clqiuant sur licône verte, j'ai à nouveau le message de licence invalide avec la date du jour. Dans la base, je retrouve le statut "invalid" mais avec la bonne date de licence. Il me suffit de repasser l'état à "valid". pour que  l'affichage redevienne normal.

![ba-ecr8](https://user-images.githubusercontent.com/10338982/38454180-4a94149a-3a62-11e8-97c6-f24bd2e1f101.jpg)


Par ailleurs, la modification du no de version de BA display pack ne force pas la demande de mise à jour.

![ba-ecr9](https://user-images.githubusercontent.com/10338982/38454181-4ab15cda-3a62-11e8-9f80-36f9e785ddc6.png)

Cordialement,

Daniel

**Comment by bookingactivities** [comment]
Bonjour Daniel,

Merci pour ces informations.
Avez-vous également cliqué sur "Vérifier à nouveau" ? (cela supprime le cache de vérification des mises à jours des  plugins). Si vous voulez le faire manuellement pour vérifier, supprimez les champs `_site_transient_update_plugins` et `edd_sl_{votre_cle_de_licence}` de la table `{prefix}_options`. 
![plugins-update-transient](https://user-images.githubusercontent.com/25784216/38461900-035c3f7a-3b17-11e8-8bcf-d29dd7399e81.PNG)
Et vérifiez à nouveau si la mise à jour vous est proposée.

Si la mise à jour ne vous est pas proposée, les mises à jour automatiques ne fonctionnent pas malgré l'activation manuelle. Il semble que votre serveur et le miens parviennent à communiquer, mais que les infos transmises ou réceptionnées soient mauvaises. Pour l'heure vous devrez donc effectuer les mises à jour manuellement en téléchargeant les versions à jour du Display Pack directement depuis votre espace [Mon Compte sur booking-activities.fr](https://booking-activities.fr/fr/mon-compte/).

Pour continuer le debugage, j'aurais besoin d'un accès administrateur à votre site pour effectuer des tests approfondis. Si c'est ok pour vous, vous pouvez m'envoyer les codes à contact@booking-activities.fr. 

Cordialement,
Yoan Cutillas

**Comment by dkolski** [comment]
Bonjour,

Je n'ai pas obtenu de résultats concluants avec la manip manuelle.

Je vous ai envoyé les codes d'accès.

Cordialement,


Daniel

**Comment by bookingactivities** [comment]
Bonjour,

Bien reçu, je regarderai cela dès que possible.

Cordialement,
Yoan

**Comment by bookingactivities** [comment]
Bonjour Daniel,

J'ai modifié le code du module d'activation de licence pour pouvoir d'avantage debugguer. 
J'ai pu constater que le serveur de Booking Activities bloquait mon adresse IP quand il est joint depuis votre site. Je voudrais m'assurer que c'est également le problème que vous rencontrez.

Pouvez-vous allez sur la page d'activation de licence sur votre panneau d'admin puis essayez d'activer la licence.
Si vous rencontrez ce message d'erreur cliquez sur le lien "Show the error page" : 
![activation-error-other-page](https://user-images.githubusercontent.com/25784216/39028760-5a9ba1ce-4493-11e8-9ebf-251b23961f95.PNG)

Cela ouvrira un nouvel onglet avec la page ayant été chargée à la place de la page voulue. Pour ma part, j'obtiens cette page : 
![booking-activities-imunify360](https://user-images.githubusercontent.com/25784216/39028811-a4859dee-4493-11e8-8194-f4466abe12fd.PNG)

Pourrez vous me dire si vous obtenez la même, ou bien m'envoyer une capture d'écran de la votre ?

Cordialement,
Yoan Cutillas

**Comment by dkolski** [comment]
Bonjour Joan,

Oui, j’obtiens exactement le même message d’erreur. 

Amicalement,

Daniel

**Comment by dkolski** [comment]
OVH

**Comment by bookingactivities** [comment]
Bonjour Daniel,

Effectivement vous me l'aviez déjà dis trois fois, à nouveau je vous prie de m'excuser.
Pouvez-vous le donner l'adresse IP de votre serveur, en privé si vous préférez, mon hébergeur va la mettre en liste blanche.

Cordialement,
Yoan Cutillas

**Comment by dkolski** [comment]
Joan,


L’adresse IP correspondant à mon hébergement est 213.186.33.4. 
Est-ce bien l’adresse du serveur ?

Amicalement,

Daniel 


Daniel Kolski 
daniel.Kolski@gmail.com 
dk-tech.fr


Le 21 avr. 2018 à 03:54, bookingactivities <notifications@github.com> a écrit :

Bonjour Daniel,

Effectivement vous me l'aviez déjà dis trois fois, à nouveau je vous prie de m'excuser.
Pouvez-vous le donner l'adresse IP de votre serveur, en privé si vous préférez, mon hébergeur va la mettre en liste blanche.

Cordialement,
Yoan Cutillas

**Comment by bookingactivities** [comment]
Bonjour Daniel,

Le problème est résolu, votre licence est bien activée et les mises à jours fonctionnent.
Le problème était donc que mon serveur qui avait blacklisté le votre. Merci de votre aide et de votre patience.

Cordialement,
Yoan Cutillas
