### ISSUE TITLE
Allow admin to also display events not yet booked in the Bookings' view

### ISSUE THREAD

**Issue by bthieblot** [bookingactivities/booking-activities#80]
FR: J'aimerais pouvoir autoriser un administrateur à pouvoir afficher aussi les événements avec 0 réservations dans le calendrier présent sur la page de réservation, avec un paramètre modifiables à partir de la pop-up. Je regarde pour une PR.

EN: I would like to allow admin to also display events with 0 booking in the bookings' view's calendar, configurable via the pop-up.

**Comment by yoancutillas** [comment]
Le calendrier sur la page des réservations affiche en réalité les réservations sous forme d'évènements, contrairement aux autres calendriers qui affichent les évènements. Il n'est donc pas possible d'afficher les évènements non réservés sur ce calendrier malheureusement.
