### ISSUE TITLE
Compatibility issue with WordPress Plugin - WP Travel Engine

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#82]
Hi,
I have a problem, Booking Activities plugin  doesn't seem to work when I have WordPress Plugin - WP Travel Engine activated. When I disable WP Travel Engine plugin, I am able to click on the calendar editor and configure the calendar perfectly.  Below is a screenshot with some JS error as it looks like!  Appreciate your help and support, thanks. 
![Booking Activities2](https://user-images.githubusercontent.com/30695308/92434820-e0213700-f1b1-11ea-9382-e5ed5b9584e6.PNG)

**Comment by yoancutillas** [comment]
Hello,
Unfortunately I cannot provide support for plugin conflicts,
It looks like the conflict comes from the select2 library, both plugins probably include and use a different version, hence the conflict.
You can try to deactivate the select2 lib from WP Travel Engine, if they have an option, or by code (remove the wp_enqueue_script call).
