### ISSUE TITLE
Feature Request: Reschedule to a different Activity

### ISSUE THREAD

**Issue by n-a-m-e** [bookingactivities/booking-activities#83]
We have the same course running at multiple locations. We have a calendar set up for booking in with a separate activity for each location.

Sometimes when we need to reschedule someone they would like to attend the course at a different location. Is it possible to change the calendar on the rescheduling popup to allow rescheduling to a different activity?

**Comment by yoancutillas** [comment]
An administrator can reschedule to the same activity, from any calendar, from the backend.
A customer can reschedule to the same activity, from the same booking form, from the frontend.

You can withdraw the same-activity protection with custom code .

Add this code in you child theme functions.php, or with a plugin like Code Snippets:
```
// Allow administrators to see any activities in reschedule calendars
function my_theme_show_administrators_any_activity_in_reschedule_calendar( $atts ) {
	if( $atts[ 'id' ] === 'bookacti-booking-system-reschedule' && ! empty( $_POST[ 'is_admin' ] ) && is_super_admin() ) {
		$atts[ 'activities' ] = array();
	}
	return $atts;
}
add_filter( 'bookacti_formatted_booking_system_attributes', 'my_theme_show_administrators_any_activity_in_reschedule_calendar', 100, 1 );

// Allow administrators to reschedule to any activities
function my_theme_allow_administrators_to_reschedule_to_any_activity( $return_array, $booking, $event_id, $event_start, $event_end, $context ) {
	if( $return_array[ 'error' ] === 'reschedule_to_different_activity' && ! empty( $_POST[ 'is_admin' ] ) && is_super_admin() ) {
		$return_array[ 'status' ] = 'success';
		unset( $return_array[ 'error' ] );
		unset( $return_array[ 'message' ] );
	}
	return $return_array;
}
add_filter( 'bookacti_booking_can_be_rescheduled_to', 'my_theme_allow_administrators_to_reschedule_to_any_activity', 100, 6 );
```

Remove `&& ! empty( $_POST[ 'is_admin' ] ) && is_super_admin()` in both functions if you want to enable the customers too.

**Comment by n-a-m-e** [comment]
Thank you, that is exactly what I needed

**Comment by rayedgar** [comment]
Ah! found the line of code that does exactly that!  ignore previous post.

**Comment by waynejb** [comment]
Added both sets of code to functions file.  Then go to actions booking date?  No change.  What did I miss?

**Comment by SophieWeb** [comment]
Thanks for including front-end settings about this in Booking Activities 1.16!
Should we get rid of the custom code in the functions.php file to prevent errors?

**Comment by yoancutillas** [comment]
_Released in Booking Activities 1.16._

You are most welcome!

Yes, you should remove the custom code related to this feature.

The only custom code that may remain (if it is useful to you) is:
```
// Allow grouped bookings to be cancelled and rescheduled (since 1.9.0)
add_filter( 'bookacti_allow_grouped_booking_changes', '__return_true' );

// Allow bookings to be cancelled and rescheduled even if the deadline has passed (since 1.9.0)
add_filter( 'bookacti_bypass_booking_changes_deadline', '__return_true' );
```

Everything else is now included in core:
- Reschedule to different activities: Go to Booking Activities > Calendar editor > the activity settings > Availability tab > "Can be rescheduled to"
- (With the [Prices and Credits](https://booking-activities.fr/en/downloads/prices-and-credits/) add-on) Ignore price check when rescheduling: Go to Booking Activities > Settings > Cancellation tab > "Allow rescheduling to an event with a different price" = ON
