### ISSUE TITLE
Grammar in "Create Booking Pass"

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#84]
Create Booking Pass

"Only him will be able to redeem it."

should be

"Only that person will be able to redeem it."

or

"Only he/she will be able to redeem it."

**Comment by yoancutillas** [comment]
Indeed, I will fix this in the next verison, thank you!

**Comment by yoancutillas** [comment]
Release in 1.4.16, currently in [beta](https://booking-activities.fr/en/blog/participate-in-booking-activities-and-add-ons-beta-tests/).
