### ISSUE TITLE
WooCommerce: Show Calendar with Month view instead of Day

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#86]
Hi,
Thanks for this fabulous plugin... I have a question as I couldn't find any reference to this by searching the Github or in your documentation. Is there a way to set the calendar displayed on WooCommerce product page to be by default the month view instead of the day view.  We don't have many events on daily basis and we don't want the customer to keep clicking the week view then month view to see the next available event!  Appreciate your support and thanks again for this amazing plugin.

**Comment by yoancutillas** [comment]
Hello, thanks a lot!

The calendar displays the "Week" view by default, or the "Day" view if the calendar is too small. You can set the threshold in Booking Activities > Settings > General tab > "Load the 'Day' view if the calendar width is less than".

You can set the "Month" view by default thanks to the [Display Pack](https://booking-activities.fr/en/downloads/display-pack/) add-on. The option will be in Booking Activities > Booking forms > _your form_ > Calendar settings > Calendar tab > "Default view".

There is also an option to make the calendar full width on WC product page in Booking Activities settings > WooCommerce tab > "Booking form location on product pages" = "Full width" (may not work with all themes).
