### ISSUE TITLE
Delete changes and create errors

### ISSUE THREAD

**Issue by rescueboy81** [bookingactivities/booking-activities#89]
Hello, I have found the tool useful for managing volunteers and their service shifts, but several errors are generated ...

- It does not save the changes in the configuration.
- If you make a couple of changes to the calendars, they stop working, and even if you try to place it as it was, it no longer works.
- I can't export data, only the header without data comes out.
- In Bookings, trying to configure the calendar view does not save the changes.

I have had to completely erase and reinstall to get it to work.

Please, if you can help me.

**Comment by yoancutillas** [comment]
Hello,
It is possible that a plugin or your theme prevents Booking Activities from working properly.

Please follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ 
for each issues.
