### ISSUE TITLE
Aucun affichage du produit de booking

### ISSUE THREAD

**Issue by Elariand** [bookingactivities/booking-activities#9]
Bonjour,

J'ai installé votre plugin (v1.4.3) depuis peu et il a l'air très intéressant et il semble correspondre exactement à ce que je recherche.
Cependant, même après avoir suivi votre documentation, je n'ai pas d'affichage des événements que j'ai créé sur ma page produit.
J'ai seulement une page avec mon calendrier, et les événements n'y sont pas affichés.

Je vous met quelques captures d'écran pour que vous puissiez comprendre un peu mieux.

Cordialement,

Thomas
![captureplannings](https://user-images.githubusercontent.com/3944912/38209460-c5bbde0c-36b4-11e8-93b5-0749255a16c1.PNG)
![captureproduit](https://user-images.githubusercontent.com/3944912/38209461-c5d5b8d6-36b4-11e8-8e90-10ecd96beb02.PNG)
![captureproduitaffichage](https://user-images.githubusercontent.com/3944912/38209462-c5f02eaa-36b4-11e8-91dd-9a8fab023814.PNG)

**Comment by bookingactivities** [comment]
Bonjour,

Merci pour votre intérêt envers Booking Activities.

Ce problème peut avoir de très nombreuses sources, j'ai crée une FAQ "Les évènements n’apparaissent pas sur le calendrier" qui vous permettra, je l'espère, de trouver la votre.

https://booking-activities.fr/fr/documentation/faq/

Cordialement,
Yoan Cutillas

**Comment by Elariand** [comment]
Bonjour,

Je viens de suivre toute ces procédures et rien de mieux qu'hier...
Voici l'url du produit en question : [http://adventurium-lyon.com/produit/privatisation/](http://adventurium-lyon.com/produit/privatisation/)

Voici aussi les infos et screens demandés : 
WordPress : 4.9.4–fr_FR
Booking Activities: Version 1.4.3
PHP (j'éditerai bientôt mon message avec ces informations)
MySQL (j'éditerai bientôt mon message avec ces informations)
![capture d ecran 2018-04-03 a 17 34 52](https://user-images.githubusercontent.com/3944912/38261295-1c1a4ba2-376a-11e8-8d5f-cad2ef1dbdc9.png)
![capture d ecran 2018-04-03 a 17 17 26](https://user-images.githubusercontent.com/3944912/38261296-1c343684-376a-11e8-8291-9786d06b0460.png)
![capture d ecran 2018-04-03 a 17 17 04](https://user-images.githubusercontent.com/3944912/38261298-1c52809e-376a-11e8-99d5-95267103412a.png)
![capture d ecran 2018-04-03 a 17 38 28](https://user-images.githubusercontent.com/3944912/38261302-1ed55b66-376a-11e8-9800-8a32c20fd4df.png)
![capture d ecran 2018-04-03 a 17 59 24](https://user-images.githubusercontent.com/3944912/38261306-2103d25a-376a-11e8-8998-fe47738ce61b.png)
![capture d ecran 2018-04-03 a 17 57 16](https://user-images.githubusercontent.com/3944912/38261307-21287b32-376a-11e8-8ecd-528b30dc78b5.png)
![capture d ecran 2018-04-03 a 17 54 29](https://user-images.githubusercontent.com/3944912/38261308-21433da0-376a-11e8-82e4-456fe685e446.png)
![capture d ecran 2018-04-03 a 17 54 20](https://user-images.githubusercontent.com/3944912/38261310-21d8fe80-376a-11e8-9941-06817b3a6b55.png)

Cordialement,

Thomas

**Comment by bookingactivities** [comment]
Bonjour,

Merci d'avoir suivi les instructions et de m'avoir envoyé les résultats.
Pouvez-vous :
- Réduire la date de fermeture de votre calendrier à 2019 ? Booking Activities subit le bug de l'an 2038, il ne peut donc pas gérer les dates au delà de 2037. De même si vous avez des évènements répétés au delà de 2037, il faut réduire leur date de fin de répétition.

Si cela ne fonctionne pas, essayez de :
- Créer un nouveau en planning en définissant uniquement le titre (laissez les autres paramètres par défaut). Créez une activité sur ce planning définissant uniquement le titre, la disponibilité (10) et la durée (1h). Créez un évènement à une date future à partir de cette activité. Affichez le calendrier avec ce shortcode [bookingactivities_form calendars="3"] (remplacez le 3 par l'id de votre planning). Dites moi si avec cette configuration basique l'évènement s'affiche ?

Enfin, en cas de nouvel échec :
- Utilisez un serveur MySQL en version 5.6 minimum au lieu de MariaDB. Je viens de tester avec MariaDB, tout semble fonctionner correctement. Mais tout le développement et les tests sont effectués avec MySQL, il est possible que j'ai manqué quelque chose.

Cordialement,

**Comment by dkolski** [comment]
Avez-vous essayé de ne pas utiliser le groupe d'événement pour voir si le problème ne venait pas de là  ?

**Comment by Elariand** [comment]
Bonjour,

Il semblerait que le problème vient du bug de l'année 2038 comme vous l'appelez.
J'ai réduis la date de fermeture de mon calendrier à 2019, puis j'ai créé de nouveaux événements.
Les nouveaux événements sont affichés alors que les anciens restent invisibles.
Je n'ai plus qu'à les recréer.
Merci pour votre réponse et votre temps.

A mon avis vous devriez mettre une option pour la date de fin de calendrier pour faire en sorte qu'il soit illimité.

Bonne journée,

Thomas.

**Comment by bookingactivities** [comment]
Bonjour,

Tout à fait, j'ajoute cette limitation à la prochaine version.
Merci à vous.

Cordialement,
