### ISSUE TITLE
CSS problem with Pick a schedule drop-down

### ISSUE THREAD

**Issue by blackhatwarrior** [bookingactivities/booking-activities#90]
In waterfall layout Pick a schedule drop-down values are not being displayed correctly after latest WordPress v5.6 update.

![image](https://user-images.githubusercontent.com/40344151/104736110-7c62d800-5768-11eb-94d4-2b596a7258c3.png)

**Comment by yoancutillas** [comment]
Thank you for your report, I will investigate.

**Comment by yoancutillas** [comment]
Fixed in 1.4.16 ([demo](https://demo.booking-activities.fr/en/shop/waterfall/)). It will be released next week.
