### ISSUE TITLE
No longer have calendar editing permissions

### ISSUE THREAD

**Issue by JustRightSites** [bookingactivities/booking-activities#91]
Prior to the last update a short list of users added specifically as managers to each calendar were able to edit those calendars.  Now they cannot.  When the calendar loads the "You are not allowed to do that" alert pops up.  no events are displayed and of course no edits are allowed.  In addition to adding the users as managers through the Booking Activities plugin, we are also using the "User Role Editor" plugin with all the bookacti tools assigned to the role that is then assigned to those managers.  Please advise.

Thanks, Pat L.

**Comment by yoancutillas** [comment]
Hello Pat,
Thanks for your report!
Can you update Booking Activities to 1.9.2? it should fix the issue.

**Comment by JustRightSites** [comment]
Hi,  We are running version 1.9.2 and were when I posted the issue.

 

 

--

Pat Levenson

Just Right Sites

 <http://www.plevenson.com/> www.JustRightSites.com

Phone: (561) 806-6370

e-Mail:  <mailto:pat@justrightsites.com> pat@justrightsites.com

**Comment by yoancutillas** [comment]
Hello, I have read your report (Feb 3), made a fix, and published it in 1.9.2 (Feb 4). Can you try again with version 1.9.2 and let me know if it works on your side?
