### ISSUE TITLE
Missing debug state in the availability check

### ISSUE THREAD

**Issue by resilva** [bookingactivities/booking-activities#93]
It seems that a debug variable has been introduced since version 1.9.0 and prevent some orders to be successfull, can you please review this and verify if it's a real mistake or not please ?

https://github.com/bookingactivities/booking-activities/blob/master/controller/controller-woocommerce-frontend.php#L1365

**Comment by yoancutillas** [comment]
Indeed, thanks for reporting!
I will fix it in the next version.

This prevents existing WC orders from being paid.

**Comment by yoancutillas** [comment]
Realeased in 1.9.3.
