### ISSUE TITLE
Persian calendar support (Update Fullcalendar to latest version)

### ISSUE THREAD

**Issue by drmkhani** [bookingactivities/booking-activities#95]
Dear all programmers
I need to code a "Persian calendar" instead of the default Gregorian calendar for booking in this plugin. Is there a way to do that?
Best wishes to all.

**Comment by yoancutillas** [comment]
Hello, 

The calendar library used by Booking Actvities is FullCalendar 3.10.2 with MomentJS 2.27, so first check if both FullCalendar 3.10.2 and MomentJS 2.27 are available in your locale here: 
- Fullcalendar: https://github.com/fullcalendar/fullcalendar/tree/v3.10.2/locale
- MomentJS: https://github.com/moment/moment/tree/2.27.0/locale

If they are, you can switch the calendar thanks to the "Site Language" option in Settings > General.

**Comment by drmkhani** [comment]
Thanks very much for your email. It actually is a Persian translation, but
not the real Persian calendar. Where can I find the calendar source code to
change it?

**Comment by yoancutillas** [comment]
Booking Activities doesn't use the latest FullCalendar version, so first, check if the calendar is correct in its latest version here: https://fullcalendar.io/docs/locale-demo

If not, it would be useful to report it to the author here: https://github.com/fullcalendar/fullcalendar/issues
Make sure that the issue doesn't exist yet by making some [quick searchs](https://github.com/fullcalendar/fullcalendar/issues?q=is%3Aissue+is%3Aopen+persian) first.

Else, the FullCalendar code used by Booking Activities is in [lib/fullcalendar/fullcalendar.min.js](https://github.com/bookingactivities/booking-activities/tree/1.10.1/lib/fullcalendar)
And it is enqueued in booking-activities.php L166-L172 : https://github.com/bookingactivities/booking-activities/blob/1.10.1/booking-activities.php#L166-L172

You can find the source code here: https://github.com/fullcalendar/fullcalendar/blob/v3.10.2/dist/fullcalendar.js
And the docs here: https://fullcalendar.io/docs/v3#toc
(make sure to check the code and the docs of the v3, not v5)

**Comment by drmkhani** [comment]
Thank you very much sir for your detailed information. I will check it out.

**Comment by drmkhani** [comment]
I checked the latest version of the "full-calendar." Thanks for the link
you sent to me. It fortunately contains the "fa" locale and it works
properly in the demo it has provided. But how can I get the "booking
activities" plugin to use this full version? It does not change to my
locale despite my wordpress website language which is set to Farsi
(Persian).!!!

**Comment by yoancutillas** [comment]
In that case, you can wait until Booking Activities supports FullCalendar v5.
It currently uses FullCalendar v3. This upgrade involves a lot of code refactoring, there is no estimated release date for the upgrade for now.

Alternately, you can try to fix the calendar with custom code. 
I don't know what changes are required, but you might be able to fix it by changing the "fa" locale settings in the [booking-activities/lib/fullcalendar/locale-all.js](https://github.com/bookingactivities/booking-activities/blob/1.10.1/lib/fullcalendar/locale-all.js) file. 
Or by changing the calendar settings on the [bookacti_calendar_init_data](https://github.com/bookingactivities/booking-activities/blob/1.10.1/js/booking-method-calendar.js#L189) hook (or [bookacti_calendar_editor_init_data](https://github.com/bookingactivities/booking-activities/blob/1.10.1/js/templates.js#L712) for the calendar editor)

**Comment by drmkhani** [comment]
Awesome, thanks! I will try these recommendations and let you know if I
have any questions.

**Comment by drmkhani** [comment]
Thanks for the guide to the codes. Unfortunately I was not able to change
the calendar to a Jalali (Persian) calendar. I think the only way would be
to wait until you upgrade to the latest full calendar version. I hope you
will do that soon. Thanks.

**Comment by yoancutillas** [comment]
Ok, sorry for that. However, the update involves a lot of code refactoring and testing, so I won't be able to treat that as a bug fix, but as a feature request.

Moreover, if I understand correctly, the Jalali calendar is not yet fully functionnal: 
- issue: https://github.com/fullcalendar/fullcalendar/issues/1813
- demo: https://fullcalendar.io/docs/locale-demo

can you confirm?

**Comment by drmkhani** [comment]
Hi. No it is functional. I recently checked it on their official website in
the demo section. The Jalali calendar worked fine.
Best regards.

**Comment by yoancutillas** [comment]
Released in 1.15.0
