### ISSUE TITLE
shopping cart booking

### ISSUE THREAD

**Issue by matteounitn** [bookingactivities/booking-activities#98]
Hello, i've got a question

i have a website with woocommerce, is it possible to set the booking calendar in the shopping cart ? 

For example:
i sell pizzas, someone orders 5 pizzas, in the shopping cart he/she orders the pizzas with a bookable calendar for 15:30/16:00, then he/she confirm by buying the 5 pizzas.

Thank you!

**Comment by yoancutillas** [comment]
Hello, no it is not possible to display the booking calendar in cart.
The booking calendar is located **on the product page** only.
The customer must go to the "Pizza" product page, select the "15:30/16:00" event, input the desired quantity, and then click "add to cart".

See that demo: https://demo.booking-activities.fr/en/shop/calendar/

**Comment by matteounitn** [comment]
> The customer must go to the "Pizza" product page, select the "15:30/16:00" event, input the desired quantity, and then click "add to cart".
So if i have 5 products, the customer must set the 15:30/16:00 event for all the different products?

**Comment by yoancutillas** [comment]
Yes, it might not meet your needs unfortunately:
The customer must select the "15:30/16:00" event for each product, and each will create a different booking. 
Moreover, the event availability will be decreased according to the quantity of products, not according to the number of customers. 

So if one customer orders 2 "Margherita" and 3 "Quattro Formaggi", he / she will need to 
- go to the "Margherita" product page, select the "15:30/16:00" event, change the quantity to "2", and then click "add to cart"
- go to the "Quattro Formaggi" product page (or switch the product variation ([demo](https://demo.booking-activities.fr/en/shop/variable-activity/))), select the "15:30/16:00" event, change the quantity to "3", and then click "add to cart"

The "15:30/16:00" event will be decreased by 5 (even though it is for the same customer), and the customer will have two distinct bookings.

**Comment by matteounitn** [comment]
That's unfortunate. 
Thank you for your time!
